2023-10-05 10:17:05 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-10-05 10:20:41 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:20:42 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-05 10:21:12 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:21:14 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-05 10:21:44 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:21:47 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-05 10:22:18 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:22:22 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-05 10:22:22 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/111506476/111506476_p1.jpg.
2023-10-05 10:22:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:22:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 10:23:24 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:23:26 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 10:23:56 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:23:59 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 10:24:29 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:24:33 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-05 10:24:33 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/26503290/くせ - 26503290.
2023-10-05 10:25:04 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:25:05 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 10:25:35 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:25:37 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 10:34:15 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:34:16 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 10:34:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:34:49 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 10:35:19 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:35:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 10:35:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:35:56 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-05 10:35:56 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/111524720/111524720_p60.jpg.
2023-10-05 10:36:27 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:36:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 10:38:30 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.pixiv.net', port=443): Read timed out. (read timeout=30)")': /ajax/illust/111530212
2023-10-05 10:41:45 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:41:46 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-05 10:46:24 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:46:25 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 10:46:56 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:46:58 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 10:47:29 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:47:32 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 10:48:02 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:48:06 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-05 10:48:06 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/101621391/101621391_p0.jpg.
2023-10-05 10:48:37 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 10:48:38 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 10:57:56 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2023-10-05 10:57:56 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2023-10-05 10:57:57 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 11:00:12 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.pixiv.net', port=443): Read timed out. (read timeout=30)")': /ajax/illust/111102725
2023-10-05 11:12:13 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:12:14 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 11:12:44 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:12:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 11:13:16 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:13:19 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 11:13:50 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:13:54 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-05 11:13:54 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/585981/あれっくす - 585981.
2023-10-05 11:14:24 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:14:25 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 11:36:36 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:36:37 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-05 11:37:07 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:37:09 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-05 11:37:40 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:37:43 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-05 11:38:13 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:38:17 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-05 11:38:17 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/79136582/79136582_p0.png.
2023-10-05 11:38:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:38:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 11:39:58 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /EwIvjkPF%2F889478%2F6219aa5b9f176a455e3943e5aacf002c8a34c813%2F651ea06f696b56ab0b074b9396a131d03dafe170?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5eNJNHy3o9C45WjSBfWjXUjWrsYrIPYijz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNTDnSkiPqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABppnsLsMU%2FeTwnHS6BStrZ2445Vny88DyyTNvfLyXhWaZ9NQrBR4%2Bquk94Cp%2FD2YZrOVRZOOzg%2FNBLMQPADoR8ORAFkhEjtJIERaf%2F81dz6XFb%2BYaRlf9A6AgC7jiQ7Nq5vbuWCcix0sSSef%2FFvaZ3pFNDVX%2F1pft2GSdWtapnzYgAA%3D%3D&uploadId=41D4222351DB49F78F368A44E8678E7A&x-oss-access-key-id=STS.NT8okF3PcTWHJ1giuvV44CFsh&x-oss-expires=1696509567&x-oss-signature=yfw2rzJb5O1EgUQjx2eq%2FBJZHQWJGXDTYFM974%2BcgQk%3D&x-oss-signature-version=OSS2
2023-10-05 11:40:30 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:40:31 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-05 11:41:02 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:41:04 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-05 11:41:34 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:41:37 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-05 11:42:07 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:42:11 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-05 11:42:11 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/79136582/79136582_p4.png.
2023-10-05 11:42:42 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:42:43 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 11:43:13 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:43:15 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 11:43:45 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:43:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 11:44:19 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:44:23 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-05 11:44:23 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/79136582/79136582_p5.png.
2023-10-05 11:44:53 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:44:54 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 11:45:24 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:45:26 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 11:46:30 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.pixiv.net', port=443): Read timed out. (read timeout=30)")': /ajax/illust/104786218
2023-10-05 11:51:26 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 11:51:27 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 11:51:42 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/09/18/07/21/59/111817051_p0.jpg
2023-10-05 11:57:47 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/25/00/00/56/111129900_p0.png
2023-10-05 12:02:58 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /jQNDBzB5%2F889478%2F64de00085a194b3267bb4945950242f04bdc5b80%2F651ea5d4104ffd2bbc5544beb83472e11075ecce?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5WGKOn6nY5m8bXfYF%2FelGENeMgZvYHoqTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNVLPLEePqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABa2Kz6GmiFAHWuERvAJ0qsCeFpw3RjmCmTTGJXJm90%2BGMFDbydb3bbtIl%2Fx7aDZENFAFBDmWtwJw3F8q39GCfVxgGNsdM5W%2Blepw3MPvD4HUoWOHTdZYj8%2FBqBJ%2BtkPb93GtZSe3CgBG02J%2FnE47yfmy5xrWzamNJmue3Nl7w1E8gAA%3D%3D&uploadId=5F438F6B06234406BDBAAF4B98F6CA29&x-oss-access-key-id=STS.NV3cSNpQGFw4byopaXtG5RDCK&x-oss-expires=1696510948&x-oss-signature=unC9rsYtPP1QqXnmZvq1H9wc73ylu3nJnosARfH77R8%3D&x-oss-signature-version=OSS2
2023-10-05 12:08:33 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/108793939/108793939_p0.gif, upload original page.
2023-10-05 12:08:34 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/108793939/108793939_p0.gif.
2023-10-05 12:15:29 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 12:15:30 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-05 12:16:01 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 12:16:03 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-05 12:16:33 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 12:16:36 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-05 12:17:06 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 12:17:10 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-05 12:17:10 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/101070379/101070379.json.txt.
2023-10-05 12:17:12 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-10-05 12:17:42 - ERROR - base.py - 94 - https://api.aliyundrive.com/token/refresh:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 12:17:43 - WARNING - base.py - 25 - Retry func _post_token_refresh 1 time.
2023-10-05 12:24:01 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 12:24:02 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 12:33:49 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/110258558/110258558_p0.gif, upload original page.
2023-10-05 12:33:49 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/110258558/110258558_p0.gif.
2023-10-05 12:43:23 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 12:43:24 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 12:43:54 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 12:43:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 12:44:26 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 12:44:29 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 12:45:00 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 12:45:04 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-05 12:45:04 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/109409304/109409304_p0.png.
2023-10-05 12:45:34 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 12:45:35 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 12:46:06 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 12:46:08 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 12:54:15 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2023-10-05 12:54:15 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2023-10-05 12:54:16 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-05 12:54:42 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2023-10-05 12:54:42 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2023-10-05 12:54:43 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-05 13:06:59 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:07:00 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-05 13:15:54 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://api.aliyundrive.com/adrive/v2/file/createWithFolders</td>
</tr>
<tr>
<td>Server:</td>
<td>security-pgw-90b2f6b7d69951d209f28a873243d040-sppll</td>
</tr>
<tr>
<td>Date:</td>
<td>2023/10/05 21:15:54</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

2023-10-05 13:15:54 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2023-10-05 13:15:55 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 13:20:58 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:20:59 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-05 13:21:29 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:21:31 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-05 13:22:01 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:22:05 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-05 13:22:35 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:22:39 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-05 13:22:39 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/90902138/90902138_p24.png.
2023-10-05 13:23:09 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:23:10 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 13:24:07 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:24:08 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 13:40:03 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/06/12/00/03/27/108936625_ugoira0.jpg
2023-10-05 13:41:42 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /QgfNetXq%2F889478%2F6447c6bda9bf2504ad9c46fbb2e7204fdd165be5%2F651ebcf7de47bdaf0a854543a5d253343510b068?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5bAItne1e5ZwqibMEnavVg4RuhZ2LfDlzz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNUv7Y0aPqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABjt%2B5sr7mhWMa28G2SHA%2FdK%2BJG1UA83Mk5AL1lvR%2Fn1OikZdblSGtIYJnFmczvv0Ta7pJxCGZoDTLm903d5R197faWOVA8PivL8bidskftrZUnJaBTFvxtgOueYChAAlTgaOfctkO%2B9iKEwE95YRHlBWjEiIsM9UiefSViezly2wgAA%3D%3D&uploadId=A6C15ED2E46B4DD0A7EB348B96D8CE72&x-oss-access-key-id=STS.NUuicj81xujp2okYXmJgu7rhu&x-oss-expires=1696516871&x-oss-signature=ywFRu3WHup2lueqn8ipDQJCYj6rHtFPIQ0je%2BCagu2w%3D&x-oss-signature-version=OSS2
2023-10-05 13:42:18 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:42:19 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-05 13:42:49 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:42:51 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-05 13:43:22 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:43:25 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-05 13:43:55 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:43:59 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-05 13:43:59 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/106740349/106740349_p0.png.
2023-10-05 13:44:30 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:44:31 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 13:45:01 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:45:03 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 13:45:33 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:45:36 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 13:46:07 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:46:11 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-05 13:46:11 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/29759565/まんなく - 29759565.
2023-10-05 13:46:41 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:46:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 13:47:12 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:47:14 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 13:47:45 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:47:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 13:48:18 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:48:22 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-05 13:48:22 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/109779105/109779105.json.txt.
2023-10-05 13:48:55 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:48:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 13:49:27 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:49:29 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 13:50:00 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:50:03 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 13:50:33 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:50:37 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-05 13:50:37 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/109779105/109779105_p0.png.
2023-10-05 13:51:07 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:51:08 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 13:51:39 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:51:41 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 13:52:11 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:52:14 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 13:52:44 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 13:52:48 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-05 13:52:48 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/585981/あれっくす - 585981.
2023-10-05 13:54:00 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2023-10-05 13:54:00 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2023-10-05 13:54:01 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 13:57:19 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/109140616/109140616_ugoira0.gif, upload original page.
2023-10-05 13:57:23 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2023-10-05 13:57:23 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2023-10-05 13:57:24 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 14:06:13 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://api.aliyundrive.com/adrive/v2/file/createWithFolders</td>
</tr>
<tr>
<td>Server:</td>
<td>security-pgw-90b2f6b7d69951d209f28a873243d040-8gg7n</td>
</tr>
<tr>
<td>Date:</td>
<td>2023/10/05 22:06:13</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

2023-10-05 14:06:13 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2023-10-05 14:06:14 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 14:12:43 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:12:44 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 14:13:15 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:13:17 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 14:13:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:13:50 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 14:14:20 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:14:24 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-05 14:14:24 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/109766227/109766227_p0.jpg.
2023-10-05 14:14:55 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:14:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 14:15:37 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/07/07/22/19/06/109471821_p0.png
2023-10-05 14:17:09 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-10-05 14:24:36 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:24:37 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-05 14:25:08 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:25:10 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-05 14:25:41 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:25:44 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-05 14:26:14 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:26:18 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-05 14:26:18 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/108105310/108105310_p1.jpg.
2023-10-05 14:26:49 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:26:50 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 14:27:20 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:27:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 14:27:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:27:55 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 14:28:26 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:28:30 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-05 14:28:30 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/108105310_mirage/108105310_p0.png.
2023-10-05 14:29:01 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:29:02 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 14:29:32 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:29:34 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 14:30:34 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.pixiv.net', port=443): Read timed out. (read timeout=30)")': /ajax/illust/111698605
2023-10-05 14:50:37 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:50:38 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-05 14:51:08 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:51:10 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-05 14:51:40 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:51:43 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-05 14:52:14 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:52:18 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-05 14:52:18 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/107253957/107253957_p0.jpg.
2023-10-05 14:52:48 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:52:49 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 14:53:45 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:53:47 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 14:54:17 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:54:20 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 14:54:50 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:54:54 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-05 14:54:54 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/107253957/107253957_p1.jpg.
2023-10-05 14:55:25 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:55:26 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 14:55:56 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:55:58 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 14:56:28 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 14:56:31 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 14:57:54 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/12/26/11/30/01/103931225_p0.jpg
2023-10-05 22:14:13 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-10-05 22:34:42 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/110258558/110258558_p0.gif, upload original page.
2023-10-05 22:34:43 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/110258558/110258558_p0.gif.
2023-10-05 22:39:16 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 22:39:17 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 22:39:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 22:39:49 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 22:40:19 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 22:40:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 22:40:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 22:40:56 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-05 22:40:56 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/109358538/109358538.json.txt.
2023-10-05 22:41:32 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 22:41:33 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 22:43:58 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/09/13/00/02/27/111673626_p0.png
2023-10-05 22:46:35 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/10/00/00/52/110683872_p0.jpg
2023-10-05 22:55:55 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 22:55:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 22:56:26 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 22:56:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 22:56:58 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 22:57:01 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 22:57:31 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 22:57:35 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-05 22:57:35 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/109744847/109744847.json.txt.
2023-10-05 22:58:09 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 22:58:10 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 23:14:08 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2021/09/17/02/50/08/92798432_p0.jpg
2023-10-05 23:26:14 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2021/10/27/00/02/34/93706504_p0.jpg
2023-10-05 23:32:43 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 23:32:44 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-05 23:34:22 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 23:34:23 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 23:34:53 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 23:34:55 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 23:35:25 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 23:35:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 23:36:00 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 23:36:04 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-05 23:36:04 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/108769067/108769067.json.txt.
2023-10-05 23:36:37 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 23:36:38 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 23:37:08 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 23:37:10 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 23:37:41 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 23:37:44 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 23:38:14 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 23:38:18 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-05 23:38:18 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/108769067/108769067_p0.jpg.
2023-10-05 23:38:48 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 23:38:49 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-05 23:39:20 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 23:39:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-05 23:39:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-05 23:39:55 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-05 23:44:39 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/108793939/108793939_p0.gif, upload original page.
2023-10-05 23:44:40 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/108793939/108793939_p0.gif.
2023-10-05 23:58:15 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/06/01/11/55/34/108623819_p0.png
2023-10-06 00:00:49 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:00:50 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 00:03:28 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:03:29 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-06 00:11:35 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:11:36 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 00:12:06 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:12:08 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 00:12:38 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:12:41 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 00:13:12 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:13:16 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 00:13:16 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/107210474/107210474_p2.png.
2023-10-06 00:13:16 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-10-06 00:13:46 - ERROR - base.py - 94 - https://api.aliyundrive.com/token/refresh:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:13:47 - WARNING - base.py - 25 - Retry func _post_token_refresh 1 time.
2023-10-06 00:16:32 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:16:33 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-06 00:17:05 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:17:07 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-06 00:18:16 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:18:17 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 00:18:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:18:49 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 00:19:20 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:19:23 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 00:19:53 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:19:57 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 00:19:57 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/111480211/111480211_p16.png.
2023-10-06 00:20:28 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:20:29 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 00:20:59 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:21:01 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 00:35:21 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/10/01/06/14/110686052_p0.jpg
2023-10-06 00:43:30 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/26/00/01/18/111157291_p0.jpg
2023-10-06 00:50:43 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:50:44 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-06 00:51:15 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:51:17 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-06 00:51:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:51:50 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-06 00:52:20 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:52:24 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-06 00:52:24 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/106465567/106465567_p6.png.
2023-10-06 00:52:56 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 00:52:57 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 00:54:33 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/09/23/17/00/07/111963558_p0.jpg
2023-10-06 01:03:38 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/109140616/109140616_ugoira0.gif, upload original page.
2023-10-06 01:05:14 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:05:15 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 01:05:46 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:05:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 01:06:19 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:06:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 01:06:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:06:56 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 01:06:56 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/110475025/110475025_p0.jpg.
2023-10-06 01:07:26 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd34b3a1be0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /adrive/v2/file/createWithFolders
2023-10-06 01:07:56 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd34b3a1d30>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /adrive/v2/file/createWithFolders
2023-10-06 01:11:49 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:11:50 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 01:12:21 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:12:23 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 01:12:54 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:12:57 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 01:13:27 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:13:31 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 01:13:31 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/111505067/111505067_p0.png.
2023-10-06 01:14:03 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:14:04 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 01:18:21 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:18:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 01:18:53 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:18:55 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 01:19:25 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd34b422e80>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /adrive/v2/file/createWithFolders
2023-10-06 01:19:55 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:19:58 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 01:20:28 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:20:32 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 01:20:32 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/108652433_mirage/108652433_p1.png.
2023-10-06 01:21:03 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:21:04 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 01:21:28 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/09/20/05/30/110675819_p0.jpg
2023-10-06 01:24:46 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:24:47 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 01:25:18 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:25:20 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 01:25:50 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:25:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 01:26:23 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:26:27 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 01:26:27 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/109113372/109113372.json.txt.
2023-10-06 01:27:00 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:27:01 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 01:45:39 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:45:40 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 01:46:10 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:46:12 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 01:46:43 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:46:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 01:47:16 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:47:20 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 01:47:20 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/111879494/111879494_p0.jpg.
2023-10-06 01:47:50 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:47:51 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 01:50:47 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/06/16/15/21/30/109057941_p0.png
2023-10-06 01:59:38 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 01:59:39 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 02:00:11 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 02:00:13 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 02:00:43 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 02:00:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 02:01:16 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 02:01:20 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 02:01:20 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/106899091_mirage/106899091_p0.png.
2023-10-06 02:01:51 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 02:01:52 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 10:16:49 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-10-06 10:17:14 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://api.aliyundrive.com/v2/file/complete</td>
</tr>
<tr>
<td>Server:</td>
<td>security-pgw-90b2f6b7d69951d209f28a873243d040-zxdd7</td>
</tr>
<tr>
<td>Date:</td>
<td>2023/10/06 18:17:13</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

2023-10-06 10:17:14 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2023-10-06 10:17:15 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-06 10:17:59 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2023-10-06 10:17:59 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2023-10-06 10:18:00 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-06 10:20:44 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 10:20:45 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 10:21:15 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 10:21:17 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 10:21:48 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 10:21:51 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 10:22:21 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 10:22:25 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 10:22:25 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/111480211/111480211_p49.png.
2023-10-06 10:22:56 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 10:22:57 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 10:23:40 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2023-10-06 10:23:40 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2023-10-06 10:23:41 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-06 10:31:36 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2023-10-06 10:31:36 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2023-10-06 10:31:37 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 10:33:09 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://api.aliyundrive.com/adrive/v2/file/createWithFolders</td>
</tr>
<tr>
<td>Server:</td>
<td>security-pgw-90b2f6b7d69951d209f28a873243d040-sdv7h</td>
</tr>
<tr>
<td>Date:</td>
<td>2023/10/06 18:33:08</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

2023-10-06 10:33:09 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2023-10-06 10:33:10 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 10:38:10 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 10:38:11 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 10:38:41 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 10:38:43 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 10:39:13 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 10:39:16 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 10:39:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 10:39:51 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 10:39:51 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/95894636/95894636_p13.png.
2023-10-06 10:40:21 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 10:40:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 10:59:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 10:59:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 11:01:26 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2023-10-06 11:01:26 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2023-10-06 11:01:27 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-06 11:03:37 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2023-10-06 11:03:37 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2023-10-06 11:03:38 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 11:05:59 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2023-10-06 11:05:59 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2023-10-06 11:06:00 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-06 11:07:56 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2023-10-06 11:07:56 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2023-10-06 11:07:57 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-06 11:24:16 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/03/19/13/48/110493671_p0.png
2023-10-06 11:25:50 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/01/10/09/58/40/95428285_p0.png
2023-10-06 11:28:49 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/06/00/00/43/110562016_p0.jpg
2023-10-06 11:29:22 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/05/13/00/07/52/98301521_p0.png
2023-10-06 11:39:26 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/108793939/108793939_p0.gif, upload original page.
2023-10-06 11:39:26 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/108793939/108793939_p0.gif.
2023-10-06 11:52:18 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 11:52:19 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 11:52:49 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 11:52:51 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 11:53:22 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 11:53:25 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 11:53:55 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 11:53:59 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 11:53:59 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/8956220/抠肉肚脐@Kuroduki - 8956220.
2023-10-06 11:54:29 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 11:54:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 12:04:15 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/07/16/01/19/12/109948691_p0.jpg
2023-10-06 12:07:20 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:07:21 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 12:07:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:07:54 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 12:08:24 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:08:27 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 12:08:57 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:09:01 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 12:09:01 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/5323203/TAYA - 5323203.
2023-10-06 12:09:31 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:09:32 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 12:10:03 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:10:05 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 12:10:35 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:10:38 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 12:11:08 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:11:12 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 12:11:12 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/104148485/104148485.json.txt.
2023-10-06 12:11:44 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:11:45 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 12:12:15 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:12:17 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 12:15:51 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-10-06 12:23:42 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:23:43 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 12:24:13 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:24:15 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 12:24:45 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:24:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 12:25:19 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:25:23 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 12:25:23 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/112199437/112199437.json.txt.
2023-10-06 12:25:55 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:25:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 12:29:49 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:29:50 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-06 12:34:08 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/05/05/17/43/54/107838386_p0.jpg
2023-10-06 12:36:25 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:36:26 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-06 12:36:56 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:36:58 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-06 12:37:29 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:37:32 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-06 12:38:02 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:38:06 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-06 12:38:06 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/109367453/109367453_p0.jpg.
2023-10-06 12:38:36 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:38:37 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 12:45:23 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/06/20/00/00/46/109168006_p0.png
2023-10-06 12:49:32 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:49:33 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-06 12:50:03 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:50:05 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-06 12:50:35 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:50:38 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-06 12:51:08 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:51:12 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-06 12:51:12 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/94945734/94945734_p1.jpg.
2023-10-06 12:51:43 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:51:44 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 12:52:15 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:52:17 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 12:52:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:52:50 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 12:53:20 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:53:24 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 12:53:24 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/94945734/94945734_p2.jpg.
2023-10-06 12:53:55 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:53:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 12:54:26 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:54:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 12:54:58 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 12:55:01 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 12:57:09 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:502:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://api.aliyundrive.com/v2/file/complete</td>
</tr>
<tr>
<td>Server:</td>
<td>security-pgw-90b2f6b7d69951d209f28a873243d040-p4hfq</td>
</tr>
<tr>
<td>Date:</td>
<td>2023/10/06 20:57:09</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

2023-10-06 12:57:09 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2023-10-06 12:57:10 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-06 12:57:10 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:502:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://api.aliyundrive.com/v2/file/complete</td>
</tr>
<tr>
<td>Server:</td>
<td>security-pgw-90b2f6b7d69951d209f28a873243d040-p4hfq</td>
</tr>
<tr>
<td>Date:</td>
<td>2023/10/06 20:57:10</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

2023-10-06 12:57:10 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2023-10-06 12:57:12 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-06 12:57:13 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:502:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://api.aliyundrive.com/v2/file/complete</td>
</tr>
<tr>
<td>Server:</td>
<td>security-pgw-90b2f6b7d69951d209f28a873243d040-p4hfq</td>
</tr>
<tr>
<td>Date:</td>
<td>2023/10/06 20:57:13</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

2023-10-06 12:57:13 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2023-10-06 12:57:16 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-06 13:03:41 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 13:03:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 13:13:32 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/109140616/109140616_ugoira0.gif, upload original page.
2023-10-06 13:19:40 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 13:19:41 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-06 13:20:12 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 13:20:14 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-06 13:20:44 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 13:20:47 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-06 13:21:17 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 13:21:21 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-06 13:21:21 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/88258846/88258846_p9.jpg.
2023-10-06 13:21:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 13:21:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 13:35:09 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/25/18/45/08/111147362_p0.jpg
2023-10-06 13:39:47 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/14/21/37/39/110829529_p0.jpg
2023-10-06 22:13:35 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-10-06 22:37:50 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 22:37:51 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 22:38:21 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 22:38:23 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 22:38:53 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 22:38:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 22:39:26 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 22:39:30 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 22:39:30 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/110294018/110294018_p1.png.
2023-10-06 22:40:01 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 22:40:02 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 22:40:32 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 22:40:34 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 22:44:21 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 22:44:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 22:44:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 22:44:54 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 22:45:24 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 22:45:27 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 22:45:58 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 22:46:02 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 22:46:02 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/55392960/ドロンタビ - 55392960.
2023-10-06 22:46:33 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 22:46:34 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 22:47:04 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 22:47:06 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 22:55:53 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 22:55:54 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 22:58:15 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 22:58:16 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-06 23:03:01 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:03:02 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-06 23:03:33 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:03:35 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-06 23:04:06 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:04:09 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-06 23:04:39 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:04:43 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-06 23:04:43 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/110354490/110354490_p0.png.
2023-10-06 23:05:13 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:05:14 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 23:05:44 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:05:47 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 23:37:27 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:37:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 23:37:59 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:38:01 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 23:38:32 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:38:35 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-06 23:39:05 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:39:09 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-06 23:39:09 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/112228330_mirage/112228330_p6.png.
2023-10-06 23:39:40 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:39:41 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 23:40:11 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:40:13 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-06 23:53:41 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:53:42 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-06 23:54:12 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:54:14 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-06 23:54:44 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:54:47 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-06 23:55:18 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:55:22 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-06 23:55:22 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/107035962/107035962_p0.png.
2023-10-06 23:55:54 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:55:55 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-06 23:56:25 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-06 23:56:27 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 00:12:36 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-10-07 00:21:36 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:21:37 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 00:22:07 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:22:09 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 00:22:39 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:22:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-07 00:23:13 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:23:17 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-07 00:23:17 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/867590/米白粕 - 867590.
2023-10-07 00:23:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:23:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 00:24:18 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:24:20 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 00:28:06 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:28:07 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 00:28:38 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:28:40 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 00:29:10 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:29:13 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-07 00:29:43 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:29:47 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-07 00:29:47 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/97529809/97529809_p19.jpg.
2023-10-07 00:30:18 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:30:19 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 00:30:49 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:30:51 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 00:32:31 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.pixiv.net', port=443): Read timed out. (read timeout=30)")': /ajax/illust/106310849
2023-10-07 00:34:39 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:34:40 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 00:35:10 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:35:12 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 00:35:42 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:35:45 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-07 00:36:16 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:36:20 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-07 00:36:20 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/111311210/111311210_p0.jpg.
2023-10-07 00:36:50 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:36:51 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 00:37:21 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:37:23 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 00:44:15 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:44:16 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 00:44:46 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:44:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 00:45:19 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:45:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-07 00:45:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:45:56 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-07 00:45:56 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/111454835_mirage/111454835_p6.png.
2023-10-07 00:46:27 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:46:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 00:46:58 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:47:00 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 00:47:31 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:47:34 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-07 00:48:04 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:48:08 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-07 00:48:08 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/111454835_mirage/111454835_p7.png.
2023-10-07 00:48:38 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.pixiv.net', port=443): Read timed out. (read timeout=30)")': /ajax/illust/110210917
2023-10-07 00:49:09 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:49:10 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 00:49:40 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 00:49:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 00:53:03 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/109140616/109140616_ugoira0.gif, upload original page.
2023-10-07 01:09:29 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 01:09:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 01:10:01 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 01:10:03 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 01:10:33 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 01:10:36 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-07 01:11:06 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 01:11:10 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-07 01:11:10 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/111976883/111976883_p1.png.
2023-10-07 01:11:41 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 01:11:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 01:12:12 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 01:12:14 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 01:13:20 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/108793939/108793939_p0.gif, upload original page.
2023-10-07 01:13:21 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/108793939/108793939_p0.gif.
2023-10-07 01:16:01 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 01:16:02 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 01:16:33 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 01:16:35 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 01:17:05 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 01:17:08 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-07 01:17:38 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 01:17:42 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-07 01:17:42 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/68481914/Qiandai以宇 - 68481914.
2023-10-07 01:18:12 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 01:18:13 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 01:18:44 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 01:18:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 01:19:16 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 01:19:19 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-07 01:19:50 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 01:19:54 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-07 01:19:54 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/110120505/110120505.json.txt.
2023-10-07 01:20:24 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.pixiv.net', port=443): Read timed out. (read timeout=30)")': /ajax/illust/110120505/pages
2023-10-07 01:20:56 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 01:20:57 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 01:21:28 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 01:21:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 10:14:29 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-10-07 10:23:16 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/09/26/11/05/12/101498435_p0.jpg
2023-10-07 10:24:36 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 10:24:37 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-07 10:25:07 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 10:25:09 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-07 10:25:39 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 10:25:42 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-07 10:26:14 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 10:26:18 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-07 10:26:18 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/108445711/108445711.json.txt.
2023-10-07 10:30:49 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/107454934/107454934_ugoira0.gif, upload original page.
2023-10-07 10:30:50 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/107454934/107454934_ugoira0.gif.
2023-10-07 10:42:39 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2021/02/23/00/00/03/87977808_p0.png
2023-10-07 10:45:03 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 10:45:04 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 10:45:34 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 10:45:36 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 10:46:07 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 10:46:10 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-07 10:46:40 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 10:46:44 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-07 10:46:44 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/111421057/111421057.json.txt.
2023-10-07 10:47:44 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 10:47:45 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 10:48:16 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 10:48:18 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 10:48:48 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 10:48:51 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-07 10:49:21 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 10:49:25 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-07 10:49:25 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/111421057/111421057_p0.png.
2023-10-07 10:49:57 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 10:49:58 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 10:50:28 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 10:50:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 11:01:00 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/07/06/00/06/36/109655380_p0.png
2023-10-07 11:12:46 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 11:12:47 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-07 11:13:20 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 11:13:22 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-07 11:13:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 11:13:55 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-07 11:14:26 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 11:14:30 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-07 11:14:30 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/110684528_mirage/110684528_p5.png.
2023-10-07 11:15:01 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 11:15:02 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 11:20:59 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/04/05/00/24/22/97412983_p0.png
2023-10-07 11:22:17 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 11:22:18 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 11:27:42 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/01/12/28/12/110428163_p0.jpg
2023-10-07 11:28:52 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/09/03/08/00/01/111401170_p0.jpg
2023-10-07 11:36:27 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2023-10-07 11:36:27 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2023-10-07 11:36:28 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-07 11:44:02 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 11:44:03 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-07 11:44:34 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 11:44:36 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-07 11:45:06 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 11:45:09 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-07 11:45:40 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 11:45:44 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-07 11:45:44 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/96308117/96308117.json.txt.
2023-10-07 11:46:18 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 11:46:19 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 11:46:49 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 11:46:51 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 11:47:22 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 11:47:25 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-07 11:47:55 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 11:47:59 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-07 11:47:59 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/96308117/96308117_p0.jpg.
2023-10-07 11:48:29 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 11:48:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 11:49:01 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 11:49:03 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 12:05:15 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:05:16 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 12:05:46 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:05:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 12:06:18 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:06:21 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-07 12:06:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:06:56 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-07 12:06:56 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/101596159/101596159_p0.png.
2023-10-07 12:07:26 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:07:27 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 12:08:23 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:08:24 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 12:12:22 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:12:23 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-07 12:12:54 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:12:56 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-07 12:13:26 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:13:29 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-07 12:13:59 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:14:03 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-07 12:14:03 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/103878768/103878768_p0.jpg.
2023-10-07 12:14:04 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-10-07 12:14:34 - ERROR - base.py - 94 - https://api.aliyundrive.com/token/refresh:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:14:35 - WARNING - base.py - 25 - Retry func _post_token_refresh 1 time.
2023-10-07 12:16:41 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2020/10/19/16/05/47/85111048_p0.png
2023-10-07 12:27:33 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/07/16/00/00/16/99749488_p0.png
2023-10-07 12:29:34 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:29:35 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 12:30:05 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:30:07 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 12:30:38 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:30:41 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-07 12:31:11 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:31:15 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-07 12:31:15 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/111963558/111963558.json.txt.
2023-10-07 12:31:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:31:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 12:46:45 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:46:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 12:47:16 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:47:18 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 12:47:49 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:47:52 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-07 12:48:22 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:48:26 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-07 12:48:26 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/12227191/AkiZero1510 - 12227191.
2023-10-07 12:48:57 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 12:48:58 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 13:00:55 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:00:56 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-10-07 13:01:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:01:54 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2023-10-07 13:02:24 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:02:27 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2023-10-07 13:02:57 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:03:01 - ERROR - base.py - 36 - All retries failed in func _post_file_complete.
2023-10-07 13:03:01 - ERROR - aliyundrive.py - 1088 - Failed to complete upload file tmp/111893586_mirage/111893586_p1.png.
2023-10-07 13:04:00 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:04:01 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 13:04:31 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:04:33 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 13:05:04 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:05:07 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-07 13:05:37 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:05:41 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-07 13:05:41 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/107177439/107177439.json.txt.
2023-10-07 13:06:15 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:06:16 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 13:11:41 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /cc8GmnYx%2F889478%2F63279ad3f1eb461b9e2a4ec8b26efa426311513e%2F652158efda101fd15b894b4fa29cbe64f4c5ec32?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5f9Le6GhKdl9pauexH61jZiesF0iIjvhjz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNTn4CnGOqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABFFrZhg59vCp%2FGRzGXym9ohGmxBXczuaXUgnPgQJeR55QSuihzchzvsYKWzwIJQFPlsmPDi5xrJ5tD8HDdrfPgDG7I4D7z3yyySQ54%2F%2BvVs0f3YtNTCJGaRKygsjmPZ4nSTjUhe6Mi20%2F40nUQCV6b2rKIil61oMp14OG6c9y2hEgAA%3D%3D&uploadId=E81FB3B2DC444BC99EF687AFA7B4916E&x-oss-access-key-id=STS.NTHfT2ixDATEy7K267vNXgMDd&x-oss-expires=1696687871&x-oss-signature=u77Y%2BZTDFITfOVkT3oLu7tNdWl%2B3UsFXtdBnBFySpGY%3D&x-oss-signature-version=OSS2
2023-10-07 13:15:07 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:15:08 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 13:15:39 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:15:41 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 13:16:11 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:16:14 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-07 13:16:44 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:16:48 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-07 13:16:48 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/111729784/111729784_p0.png.
2023-10-07 13:17:19 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:17:20 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 13:22:18 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/108793939/108793939_p0.gif, upload original page.
2023-10-07 13:22:18 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/108793939/108793939_p0.gif.
2023-10-07 13:28:41 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:28:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-07 13:29:13 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:29:15 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-07 13:29:45 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:29:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-07 13:30:18 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:30:22 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-07 13:30:22 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/109488026_mirage/109488026_p0.png.
2023-10-07 13:30:53 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-07 13:30:54 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
