2024-08-10 00:44:01 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817232506409292907e4cba","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:44:01 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:44:04 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-10 00:44:04 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817232506442023374e4cba","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:44:04 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:44:08 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-10 00:44:08 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-08-10 00:48:19 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fc17232508997421162e026b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:48:19 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:48:20 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-08-10 00:48:21 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fc17232509010201352e026b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:48:21 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:48:23 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-08-10 00:48:23 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fc17232509033161729e026b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:48:23 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:48:26 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-10 00:48:26 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fc17232509065882286e026b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:48:26 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:48:30 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-10 00:48:30 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/5668238/うさり*C104月-東ル32b - 5668238.
2024-08-10 00:48:49 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700a17232509291624445ecfde","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:48:49 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:48:50 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-08-10 00:48:50 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700a17232509304374618ecfde","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:48:50 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:48:52 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-08-10 00:48:52 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700a17232509327084963ecfde","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:48:52 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:48:55 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-10 00:48:56 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700a17232509360035462ecfde","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:48:56 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:49:00 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-10 00:49:00 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-08-10 00:49:05 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700a17232509452846805ecfde","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:49:05 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:49:06 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-08-10 00:49:06 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700a17232509465576963ecfde","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:49:06 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:49:08 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-08-10 00:49:08 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700a17232509488327209ecfde","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:49:08 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:49:12 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-10 00:49:12 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700a17232509521137616ecfde","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:49:12 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:49:16 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-10 00:49:16 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/27473831/nyeppu | ニェップ - 27473831.
2024-08-10 00:56:46 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801d17232514066642847e8503","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:56:46 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:56:47 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-08-10 00:56:48 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801d17232514079362968e8503","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:56:48 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:56:50 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-08-10 00:56:50 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801d17232514102093300e8503","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:56:50 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:56:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-10 00:56:53 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801d17232514135053774e8503","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:56:53 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:56:57 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-10 00:56:57 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/27473831/nyeppu | ニェップ - 27473831.
2024-08-10 00:59:08 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817232515480447420e4cb6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:59:08 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:59:09 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-08-10 00:59:09 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817232515493257617e4cb6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:59:09 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:59:11 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-08-10 00:59:11 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817232515516017877e4cb6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:59:11 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:59:14 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-10 00:59:15 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817232515548798236e4cb6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 00:59:15 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 00:59:19 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-10 00:59:19 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/27473831/nyeppu | ニェップ - 27473831.
2024-08-10 01:00:24 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700c17232516246275836e0264","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:00:24 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:00:25 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-08-10 01:00:26 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700c17232516259006054e0264","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:00:26 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:00:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-08-10 01:00:28 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700c17232516281696481e0264","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:00:28 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:00:31 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-10 01:00:31 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700c17232516314626989e0264","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:00:31 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:00:35 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-10 01:00:35 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/5668238/うさり*C104月-東ル32b - 5668238.
2024-08-10 01:03:08 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802017232517884732135e67b6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:03:08 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:03:09 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-08-10 01:03:09 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802017232517897532344e67b6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:03:09 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:03:11 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-08-10 01:03:12 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802017232517920312637e67b6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:03:12 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:03:15 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-10 01:03:15 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802017232517953133138e67b6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:03:15 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:03:19 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-10 01:03:19 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-08-10 01:03:53 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802017232518333018061e67b6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:03:53 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:03:54 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-08-10 01:03:54 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802017232518345768262e67b6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:03:54 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:03:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-08-10 01:03:57 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802017232518368538535e67b6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:03:57 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:04:00 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-10 01:04:00 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802017232518401338991e67b6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:04:00 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:04:04 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-10 01:04:04 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/5668238/うさり*C104月-東ル32b - 5668238.
2024-08-10 01:06:31 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/12/23/18/31/30/103832862_p0.png
2024-08-10 01:07:31 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801f17232520515028810e7f06","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:07:31 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:07:32 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-08-10 01:07:32 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801f17232520527778933e7f06","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:07:32 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:07:34 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-08-10 01:07:35 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801f17232520550491153e7f06","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:07:35 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:07:38 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-10 01:07:38 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801f17232520583521506e7f06","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:07:38 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:07:42 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-10 01:07:42 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-08-10 01:08:35 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702117232521156847672e4d1a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:08:35 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:08:36 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-08-10 01:08:37 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702117232521169617835e4d1a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:08:37 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:08:39 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-08-10 01:08:39 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702117232521192368117e4d1a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:08:39 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:08:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-10 01:08:42 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702117232521225128535e4d1a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:08:42 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:08:46 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-10 01:08:46 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-08-10 01:09:02 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702117232521422533308e4d1a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:09:02 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:09:03 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-08-10 01:09:03 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702117232521435293512e4d1a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:09:03 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:09:05 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-08-10 01:09:05 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702117232521457993823e4d1a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:09:05 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:09:08 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-10 01:09:09 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702117232521490984301e4d1a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:09:09 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:09:13 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-10 01:09:13 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/5668238/うさり*C104月-東ル32b - 5668238.
2024-08-10 01:09:21 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702117232521616186069e4d1a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:09:21 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:09:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-08-10 01:09:23 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702117232521628956251e4d1a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:09:23 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:09:25 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-08-10 01:09:25 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702117232521651746554e4d1a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:09:25 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:09:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-10 01:09:28 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702117232521684527091e4d1a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-10 01:09:28 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-10 01:09:32 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-10 01:09:32 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/27473831/nyeppu | ニェップ - 27473831.
2024-08-10 10:18:49 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-08-10 10:19:51 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /wKSgXlpr%2F889478%2F66b73ea8065cee8926cc45b2a009d64a22f4b158%2F66b73ea8ed77a16bb49f4e978c77860cd18d0dce?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5flMer%2BvepHjrOKaBH6jVQZafpgjqzx0zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNSWteGqrq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneUxePzw6si4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iK1aJDvXtuMkagAFbFD7PH6ywR18D5V%2Bwz21BinzSu6Fsw8Y%2BjsB0kmfzKA0i47HAQDHrS8K8Dn8ZJNJeiMEjHjuPBPgXZygH%2Fz5%2FRz7sRaWZiAcu3E%2F%2Fdpb%2F9RpAYH%2F90rN7btKLWZMBmx9XTKrGmQsueCPs3J%2FQHn82iIjPOFbIXKLpvbtlV7P7zyAA&uploadId=EFA8F7B901DB488ABB9B130E195F1E41&x-oss-access-key-id=STS.NTPzPJP5f9qaj7KiTLeuLaiZ1&x-oss-expires=1723288761&x-oss-signature=xO4b8HzO0JKzscDTy5I0JezXyU1TjQ4PhHezj%2BBM1sU%3D&x-oss-signature-version=OSS2
2024-08-10 10:27:40 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /GvXv6aGi%2F889478%2F66828a6df758ad2c311f427e9616740022be47e8%2F66b7407ec8cb4168175447e7b3e1ec0d0ae42414?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5flMer%2BvepHjrOKaBH6jVQZafpgjqzx0zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNSWteGqrq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneUxePzw6si4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iK1aJDvXtuMkagAFbFD7PH6ywR18D5V%2Bwz21BinzSu6Fsw8Y%2BjsB0kmfzKA0i47HAQDHrS8K8Dn8ZJNJeiMEjHjuPBPgXZygH%2Fz5%2FRz7sRaWZiAcu3E%2F%2Fdpb%2F9RpAYH%2F90rN7btKLWZMBmx9XTKrGmQsueCPs3J%2FQHn82iIjPOFbIXKLpvbtlV7P7zyAA&uploadId=4BFE09D401F24B9DB76EC5094C8E6248&x-oss-access-key-id=STS.NTPzPJP5f9qaj7KiTLeuLaiZ1&x-oss-expires=1723289230&x-oss-signature=8%2F2vbMHiriLF%2BziZt5oXRRDA3x0wUh527RnpY46X1BE%3D&x-oss-signature-version=OSS2
2024-08-10 10:39:27 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /DmwagSi0%2F889478%2F66376a3dd9538f4f52b84f7da155743f15d028d4%2F66b7434147a1ec758dbb44fabed2caa627de1c4c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5flMer%2BvepHjrOKaBH6jVQZafpgjqzx0zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNSWteGqrq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneUxePzw6si4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iK1aJDvXtuMkagAFbFD7PH6ywR18D5V%2Bwz21BinzSu6Fsw8Y%2BjsB0kmfzKA0i47HAQDHrS8K8Dn8ZJNJeiMEjHjuPBPgXZygH%2Fz5%2FRz7sRaWZiAcu3E%2F%2Fdpb%2F9RpAYH%2F90rN7btKLWZMBmx9XTKrGmQsueCPs3J%2FQHn82iIjPOFbIXKLpvbtlV7P7zyAA&uploadId=4FA1EC2F0A9A4401BE664277B46A00DC&x-oss-access-key-id=STS.NTPzPJP5f9qaj7KiTLeuLaiZ1&x-oss-expires=1723289937&x-oss-signature=Yi6IwDmatj8BuT0PhpuTzhmwus3x2ySCdqImJl%2Bt7ts%3D&x-oss-signature-version=OSS2
2024-08-10 10:46:48 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /Gzlw5ZAo%2F889478%2F66867fead7772ea6cddb45b2919e15eab9480b60%2F66b744f98540741e8b0541af85d24f8e6196ff4c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5flMer%2BvepHjrOKaBH6jVQZafpgjqzx0zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNSWteGqrq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneUxePzw6si4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iK1aJDvXtuMkagAFbFD7PH6ywR18D5V%2Bwz21BinzSu6Fsw8Y%2BjsB0kmfzKA0i47HAQDHrS8K8Dn8ZJNJeiMEjHjuPBPgXZygH%2Fz5%2FRz7sRaWZiAcu3E%2F%2Fdpb%2F9RpAYH%2F90rN7btKLWZMBmx9XTKrGmQsueCPs3J%2FQHn82iIjPOFbIXKLpvbtlV7P7zyAA&uploadId=CE25DD81233C4E82AD0EB8571FD9791A&x-oss-access-key-id=STS.NTPzPJP5f9qaj7KiTLeuLaiZ1&x-oss-expires=1723290378&x-oss-signature=KIIRDeCl9iTf6prLfSvU5ULUnjQOvETzGHP7PUt7EQ8%3D&x-oss-signature-version=OSS2
2024-08-10 10:53:54 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /709WS1li%2F889478%2F65fc1644606fa16906b248d0976ed5b8cc5958bb%2F66b746a4d1f6b0df9d2e4e928581f8909ee8eaf4?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5flMer%2BvepHjrOKaBH6jVQZafpgjqzx0zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNSWteGqrq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneUxePzw6si4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iK1aJDvXtuMkagAFbFD7PH6ywR18D5V%2Bwz21BinzSu6Fsw8Y%2BjsB0kmfzKA0i47HAQDHrS8K8Dn8ZJNJeiMEjHjuPBPgXZygH%2Fz5%2FRz7sRaWZiAcu3E%2F%2Fdpb%2F9RpAYH%2F90rN7btKLWZMBmx9XTKrGmQsueCPs3J%2FQHn82iIjPOFbIXKLpvbtlV7P7zyAA&uploadId=0562D1572C07465C997FDD6630A50702&x-oss-access-key-id=STS.NTPzPJP5f9qaj7KiTLeuLaiZ1&x-oss-expires=1723290804&x-oss-signature=g2dFavUzH7FKKqQuDjK4HPbrc9vh4kEx4x9oSGtBkPU%3D&x-oss-signature-version=OSS2
2024-08-10 11:00:15 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /92wvaWAQ%2F889478%2F66b6a0055bdd564d99004e98ae137729302ac246%2F66b74821c339a855f4d64a32b7b285de1af6166d?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5flMer%2BvepHjrOKaBH6jVQZafpgjqzx0zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNSWteGqrq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneUxePzw6si4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iK1aJDvXtuMkagAFbFD7PH6ywR18D5V%2Bwz21BinzSu6Fsw8Y%2BjsB0kmfzKA0i47HAQDHrS8K8Dn8ZJNJeiMEjHjuPBPgXZygH%2Fz5%2FRz7sRaWZiAcu3E%2F%2Fdpb%2F9RpAYH%2F90rN7btKLWZMBmx9XTKrGmQsueCPs3J%2FQHn82iIjPOFbIXKLpvbtlV7P7zyAA&uploadId=12CD54B017CA46F4A3F06C9E348828D5&x-oss-access-key-id=STS.NTPzPJP5f9qaj7KiTLeuLaiZ1&x-oss-expires=1723291185&x-oss-signature=d84XoeoM%2Bu0Z3r67j4gfoQ%2BpjmW6HUGRNM2a1umbg%2Bk%3D&x-oss-signature-version=OSS2
2024-08-10 11:07:37 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /1JhiKSmX%2F889478%2F65ed9d3647ece34d2c854f4d846ddbde84886f9e%2F66b749dbf8af6923bad44706a107d9f0eeca4f7c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5flMer%2BvepHjrOKaBH6jVQZafpgjqzx0zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNSWteGqrq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneUxePzw6si4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iK1aJDvXtuMkagAFbFD7PH6ywR18D5V%2Bwz21BinzSu6Fsw8Y%2BjsB0kmfzKA0i47HAQDHrS8K8Dn8ZJNJeiMEjHjuPBPgXZygH%2Fz5%2FRz7sRaWZiAcu3E%2F%2Fdpb%2F9RpAYH%2F90rN7btKLWZMBmx9XTKrGmQsueCPs3J%2FQHn82iIjPOFbIXKLpvbtlV7P7zyAA&uploadId=018D6C66FAD546D98FD297D1CC6CBBB4&x-oss-access-key-id=STS.NTPzPJP5f9qaj7KiTLeuLaiZ1&x-oss-expires=1723291627&x-oss-signature=BbfwFODuXs6mrzX5LmyU3zts7Q07Tod3%2FZnmrpUBpEg%3D&x-oss-signature-version=OSS2
2024-08-10 11:13:57 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /7rxu1wD3%2F889478%2F66b74b57a3cc024cd18243089ab99d50026f199c%2F66b74b572904c3e8d35f43d38eb0a1c2082948d2?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5flMer%2BvepHjrOKaBH6jVQZafpgjqzx0zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNSWteGqrq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneUxePzw6si4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iK1aJDvXtuMkagAFbFD7PH6ywR18D5V%2Bwz21BinzSu6Fsw8Y%2BjsB0kmfzKA0i47HAQDHrS8K8Dn8ZJNJeiMEjHjuPBPgXZygH%2Fz5%2FRz7sRaWZiAcu3E%2F%2Fdpb%2F9RpAYH%2F90rN7btKLWZMBmx9XTKrGmQsueCPs3J%2FQHn82iIjPOFbIXKLpvbtlV7P7zyAA&uploadId=92D68AA857B041F78DBBC893FFED9682&x-oss-access-key-id=STS.NTPzPJP5f9qaj7KiTLeuLaiZ1&x-oss-expires=1723292007&x-oss-signature=YxoB%2FlWvS4dlAOH38EG09hgRKJfwdG7NIHr9AARKIAc%3D&x-oss-signature-version=OSS2
2024-08-10 11:20:54 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /y5yvgqu1%2F889478%2F66b74cf84a582586c4f5491dbc1a652fe0e40456%2F66b74cf8561c63ec00cb48fd9656e6ec3779799a?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=E941C11B2B684EEBB180484763FDF2B2&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723292424&x-oss-signature=EbQrsAp9CUkEEn9V4Jp7qe4ZvV2cIkekyAqrI4O3W%2BI%3D&x-oss-signature-version=OSS2
2024-08-10 11:27:05 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /ZWOXl2Hx%2F889478%2F65fac68cc2af616ea92440429a7e40199af287e1%2F66b74e6adca4009af48c458d8ef7cddd1a0eb07a?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=5627EDC0BDA54D2D9D8D8FCA48CC15C2&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723292794&x-oss-signature=P2BbneGuYvhn43bsP7y%2FvRmvsqmEBrpoj83s4vEuURI%3D&x-oss-signature-version=OSS2
2024-08-10 11:30:02 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/02/25/14/42/26/116379483_p0.png
2024-08-10 11:34:43 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /ElcECmFC%2F889478%2F66a37cf5d102d51a82f5460188c53a86b53f1267%2F66b75035d6a9563ec3fc42578db08d9e64db0e27?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=ACCBD552CAF849DB8252C29CC20B0A37&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723293253&x-oss-signature=R%2BkG4YDBvnTer9cbWZRB11R5%2BOyUqnZbiX52tTVeCMc%3D&x-oss-signature-version=OSS2
2024-08-10 11:39:11 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/05/02/11/25/03/118351781_p0.jpg
2024-08-10 11:42:17 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /JCOdzCZR%2F889478%2F66b751fae3e3eb8f2a3e4a13927cf02c6cb53f69%2F66b751fa337d4a8767424ba09b64b7c0904883a4?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=5E93A71E0A6B438BAEE9130BCF27FD92&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723293706&x-oss-signature=ftpVQxBUrFqLTJIso5mueMIahWW13V9pLN%2BNqu6rURw%3D&x-oss-signature-version=OSS2
2024-08-10 11:50:34 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /5ECiUmeG%2F889478%2F65fec3e372d5a1f678e247cda58749eb9617e46a%2F66b753ec1d6eabb77911468cbf5f8aa120d75fa8?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=FDC4632A72A741C3A734C79B12B30130&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723294204&x-oss-signature=Tzql6ja3xHMn45kfD0Snv4Xo0NJkLk6APnmZNT8xSHw%3D&x-oss-signature-version=OSS2
2024-08-10 11:55:46 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/09/14/01/05/06/111700523_p0.jpg
2024-08-10 11:58:30 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /pd4zvBHe%2F889478%2F65a141d72d1ced588f384604a7d589c493e5617f%2F66b755c8a5d6ecb97d844fc4a329e111bc606e45?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=C91198EE32D84A4F8B7B753AC4DC73DB&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723294680&x-oss-signature=OGwpTn88wkcKfu%2BNfNqDm1mD6f3yy81zhXbpLNpNg4g%3D&x-oss-signature-version=OSS2
2024-08-10 12:06:10 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /dWncrEDs%2F889478%2F66b4b0a31db824f71cb2480db1a0c81c67cf2cd4%2F66b7579477d8bba90f3d4ce4a4181ff931987a75?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=4501A36BC72B4708A9D9688BBFF79406&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723295140&x-oss-signature=LmbqsyF60fcHwafRgsT%2BgtYV%2FB7JITCvZWI%2BmEDpQvI%3D&x-oss-signature-version=OSS2
2024-08-10 12:13:25 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /7ncRKG3Q%2F889478%2F66b75947c78ca432979e4227bc52e19856cb2fbb%2F66b759477d689b9aafad4cf98123a23cc90e0ea2?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=E24309A3663D474FB70DD641B0B3A715&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723295575&x-oss-signature=azj9oCJhaNgFZ81tmTAjZ9afFxf%2FcjG641eZt6HtoPQ%3D&x-oss-signature-version=OSS2
2024-08-10 12:17:49 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-08-10 12:18:46 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /UtD1NP1a%2F889478%2F66b75a887c68191e8f914dc2bbfe98c025b45b30%2F66b75a88b2c16ac7180e40078dd68dc813cfa46e?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=B72C3FDBBAD34A188E334FB46A6B3B6C&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723295896&x-oss-signature=rJ9LHTtT3AxCxLccVvEQio2f0e7aO445ZLMh8Xk%2BBF8%3D&x-oss-signature-version=OSS2
2024-08-10 12:23:50 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/26/17/06/23/114573429_p0.jpg
2024-08-10 12:24:53 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /EZRLtJC2%2F889478%2F66b75bef1fbba069419a4133bd85ab636a5f6f62%2F66b75bef4925611e77fa4108a3f9fdd4af19b549?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=67D5A42BF2BA4D48A7BC86EFFAF0B8A5&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723296255&x-oss-signature=weV%2FP%2BDWAMhEjooYUWPHPOPMzCf90uMtazwJUW8dTRM%3D&x-oss-signature-version=OSS2
2024-08-10 12:31:50 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /gajvAhnS%2F889478%2F663610f2d055e01e61644e46bcc5918cdf274e82%2F66b75d8a76e2a447f8864d1c9ea9f426a11e6476?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=D1AD9F19D2C842FB99FD1E4CD423948D&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723296666&x-oss-signature=jPNUhx2G5vIVjN%2Fy7W9x5%2F8MKYMp3dE8G2EJksD2eVo%3D&x-oss-signature-version=OSS2
2024-08-10 12:38:36 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /d2WuNe0l%2F889478%2F666c335912067aee71c04de194d31968307b4f00%2F66b75f2e4f8f3c40ad9640abbc7db61afdd6a7bf?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=6CA846AC6A244A5A9808BB580B55C54F&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723297086&x-oss-signature=wstF4fmDKXGnXbUtwWSPhPhF1fnBQvH%2BcvAhIHFDwKE%3D&x-oss-signature-version=OSS2
2024-08-10 12:45:44 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /5YyaTBdj%2F889478%2F65ec490272f8140afc8b4a3995ab2b1e39288129%2F66b760d8e52c324c078a499280518408a61589de?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=2622019549AA4D0BB5D5C9FF3B73D4C9&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723297513&x-oss-signature=6Lwd%2BxOJ%2Bw1MwlvUoVNnw8Z%2Fjd5b7bpbpkZRfqLudKg%3D&x-oss-signature-version=OSS2
2024-08-10 12:45:46 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/5YyaTBdj%2F889478%2F65ec490272f8140afc8b4a3995ab2b1e39288129%2F66b760d8e52c324c078a499280518408a61589de?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=2622019549AA4D0BB5D5C9FF3B73D4C9&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723297513&x-oss-signature=6Lwd%2BxOJ%2Bw1MwlvUoVNnw8Z%2Fjd5b7bpbpkZRfqLudKg%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>66B760F912E6123931BD668B</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"B3450C8E07F5C172E1BF606DA4036BA6"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2024-08-10 12:45:47 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/5YyaTBdj%2F889478%2F65ec490272f8140afc8b4a3995ab2b1e39288129%2F66b760d8e52c324c078a499280518408a61589de?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=2622019549AA4D0BB5D5C9FF3B73D4C9&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723297513&x-oss-signature=6Lwd%2BxOJ%2Bw1MwlvUoVNnw8Z%2Fjd5b7bpbpkZRfqLudKg%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>66B760FAB858D8363378613D</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"B3450C8E07F5C172E1BF606DA4036BA6"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2024-08-10 12:45:47 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/5YyaTBdj%2F889478%2F65ec490272f8140afc8b4a3995ab2b1e39288129%2F66b760d8e52c324c078a499280518408a61589de?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=2622019549AA4D0BB5D5C9FF3B73D4C9&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723297513&x-oss-signature=6Lwd%2BxOJ%2Bw1MwlvUoVNnw8Z%2Fjd5b7bpbpkZRfqLudKg%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>66B760FBF8DE43383317388D</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"B3450C8E07F5C172E1BF606DA4036BA6"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2024-08-10 12:45:47 - ERROR - aliyundrive.py - 1077 - File tmp/116254048/116254048_p1.jpg Part 1 upload failed.
2024-08-10 12:46:22 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/08/06/01/10/44/121220896_p0.jpg
2024-08-10 12:51:50 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /KNOGepEL%2F889478%2F66b762469627c1a02e0b4fd5ac6fb7e90af07f44%2F66b76246e361561b362843f3ae6ae6ac5065dc95?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=515AB6E28DEE483FB83D69E4478BA128&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723297879&x-oss-signature=JgAaYNCwQUXYs2xKzOiG5%2Bv8NWI7ntZYACx1EvsGLW0%3D&x-oss-signature-version=OSS2
2024-08-10 12:58:22 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /T7ukkZ4o%2F889478%2F66a4cb2939feab0a9e314fe2a1dfc84e4d401dfd%2F66b763cfe92f75b7bbf34c8ca215a87c1494fe31?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=B49F6B56B2C64DACBCC052A212E9D3EE&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723298271&x-oss-signature=w8w0phnlvxv4x78KJxhKJHZl8m3cDPpwP%2FMR2ESiVRc%3D&x-oss-signature-version=OSS2
2024-08-10 13:04:21 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /yTdr0sIa%2F889478%2F667957ad769c20a779b74e16a836d7496097bb88%2F66b765379cb4206a9ec0440c93abcd249769c638?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=B2C8655CF254493CAF4CADA6FA4A107E&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723298631&x-oss-signature=JmZyMTo6Qd5jkuy%2Fxh7S1xAN13%2F%2FFisjkCad0aJnrys%3D&x-oss-signature-version=OSS2
2024-08-10 13:04:53 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /yTdr0sIa%2F889478%2F667957ad769c20a779b74e16a836d7496097bb88%2F66b765379cb4206a9ec0440c93abcd249769c638?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=B2C8655CF254493CAF4CADA6FA4A107E&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723298631&x-oss-signature=JmZyMTo6Qd5jkuy%2Fxh7S1xAN13%2F%2FFisjkCad0aJnrys%3D&x-oss-signature-version=OSS2
2024-08-10 13:05:25 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /yTdr0sIa%2F889478%2F667957ad769c20a779b74e16a836d7496097bb88%2F66b765379cb4206a9ec0440c93abcd249769c638?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=B2C8655CF254493CAF4CADA6FA4A107E&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723298631&x-oss-signature=JmZyMTo6Qd5jkuy%2Fxh7S1xAN13%2F%2FFisjkCad0aJnrys%3D&x-oss-signature-version=OSS2
2024-08-10 13:14:11 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /hzCq2Epu%2F889478%2F66b76785df7368088cc543e89263c09496c60a57%2F66b76785a1c67ca49c664c99a77ab8e361db2a5d?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f3M%2FyD25lAgZXTc2L7hkIBXPpgobbeqjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXyxa2Grq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3MC0Smsi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iAy6tHvXtuMkagAEhKKM6pUXdbXr%2FqR4sL75%2Fuz7h3LwzAr3ByM%2FRoPFrzisCM2d9QT4CJH9fo3AoYlOCvmXtb19St639Gy7tx%2FBC0WM1neQ80d0g%2F4%2BBz%2BS5o1jhu0o5Ztjc5iHFWtXhbacne5yuy0N3LmTIiuhpsNNxNYdQTw8F0MQSNys84mzMbyAA&uploadId=5BD689F086DA48EEA8828C38B5E1E5FF&x-oss-access-key-id=STS.NTBxF76Fa6W8qDJbBTPuLNsuH&x-oss-expires=1723299221&x-oss-signature=uZL4dKyLzJUyt7SWVXpZ6tRqUXmXxArtJG%2B4PlTAmgg%3D&x-oss-signature-version=OSS2
2024-08-10 13:19:07 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/04/26/00/25/44/118158582_p0.jpg
2024-08-10 22:16:23 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-08-10 22:39:12 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/06/26/00/00/29/119974390_p0.jpg
2024-08-10 22:55:21 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/04/11/22/27/48/117751617_p0.jpg
2024-08-10 23:19:43 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/04/13/23/14/57/117811633_p0.png
2024-08-10 23:52:08 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/14/14/42/44/115159866_p0.png
2024-08-11 00:14:33 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/10/31/16/42/32/113007875_p0.jpg
2024-08-11 00:15:27 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-08-11 00:24:59 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/07/02/20/45/40/120182066_p0.jpg
2024-08-11 00:41:04 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/02/29/17/07/34/116494071_p0.jpg
2024-08-11 00:42:21 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/03/21/14/39/44/117116137_p0.png
2024-08-11 10:17:45 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-08-11 10:36:56 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/07/07/19/12/09/120325517_p0.png
2024-08-11 10:48:33 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /OrGREd2i%2F889478%2F66b4aa07b2c738eddfb34848aa46495992530868%2F66b896e3bd0bed2527384321808e596b66af3d6a?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5fyL%2FTTla9l1oiSVxHAjkc4PsUahLzpsjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVf0ETyrq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnewz7UTzvci4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iBFm6oPXtuMkagAE%2FuNGU0cDBFcZc7TTrqXdG1h5Uode%2FkEB3F%2FeJaVot0TDzGtvpqM34CGfUobSKurNFQcy2HB0mqV88XV5Jzv1FAwzHy1ofXrkZfZ6DVmq%2Fho79MC967zpVE0vnVibAQ0oVx6baGghGBWzvbH5OGizc4rvnQa1I2I%2BtxCjUBmqFNiAA&uploadId=62A9F1B5416343DBA432BE463694237B&x-oss-access-key-id=STS.NTGdNgxpDaJyU7qjGm2J6kyBP&x-oss-expires=1723376883&x-oss-signature=ZsWhuUKVHuz2gxkXINH%2F%2BqclvcQoFMW9ePg3qCRT9UI%3D&x-oss-signature-version=OSS2
2024-08-11 10:56:31 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/04/27/19/54/28/118207002_p0.jpg
2024-08-11 11:04:33 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /V4qrXp6A%2F889478%2F665854886737a81a44204a04b13348d548bfe319%2F66b89a918bbdb8fc74fc428a9b4aab84d5ae7862?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5fyL%2FTTla9l1oiSVxHAjkc4PsUahLzpsjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVf0ETyrq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnewz7UTzvci4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iBFm6oPXtuMkagAE%2FuNGU0cDBFcZc7TTrqXdG1h5Uode%2FkEB3F%2FeJaVot0TDzGtvpqM34CGfUobSKurNFQcy2HB0mqV88XV5Jzv1FAwzHy1ofXrkZfZ6DVmq%2Fho79MC967zpVE0vnVibAQ0oVx6baGghGBWzvbH5OGizc4rvnQa1I2I%2BtxCjUBmqFNiAA&uploadId=3D07E776DE38437A99B48E5F15457E49&x-oss-access-key-id=STS.NTGdNgxpDaJyU7qjGm2J6kyBP&x-oss-expires=1723377825&x-oss-signature=NFZp5WwrOBHxcwvldLnKhu1uQyB%2FCHH9cThALeEPlu4%3D&x-oss-signature-version=OSS2
2024-08-11 11:04:37 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/V4qrXp6A%2F889478%2F665854886737a81a44204a04b13348d548bfe319%2F66b89a918bbdb8fc74fc428a9b4aab84d5ae7862?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5fyL%2FTTla9l1oiSVxHAjkc4PsUahLzpsjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVf0ETyrq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnewz7UTzvci4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iBFm6oPXtuMkagAE%2FuNGU0cDBFcZc7TTrqXdG1h5Uode%2FkEB3F%2FeJaVot0TDzGtvpqM34CGfUobSKurNFQcy2HB0mqV88XV5Jzv1FAwzHy1ofXrkZfZ6DVmq%2Fho79MC967zpVE0vnVibAQ0oVx6baGghGBWzvbH5OGizc4rvnQa1I2I%2BtxCjUBmqFNiAA&uploadId=3D07E776DE38437A99B48E5F15457E49&x-oss-access-key-id=STS.NTGdNgxpDaJyU7qjGm2J6kyBP&x-oss-expires=1723377825&x-oss-signature=NFZp5WwrOBHxcwvldLnKhu1uQyB%2FCHH9cThALeEPlu4%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>66B89AC386F9953836662DEB</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"079E8E1B01F1F258B6091FA2B6587710"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2024-08-11 11:04:38 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/V4qrXp6A%2F889478%2F665854886737a81a44204a04b13348d548bfe319%2F66b89a918bbdb8fc74fc428a9b4aab84d5ae7862?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5fyL%2FTTla9l1oiSVxHAjkc4PsUahLzpsjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVf0ETyrq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnewz7UTzvci4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iBFm6oPXtuMkagAE%2FuNGU0cDBFcZc7TTrqXdG1h5Uode%2FkEB3F%2FeJaVot0TDzGtvpqM34CGfUobSKurNFQcy2HB0mqV88XV5Jzv1FAwzHy1ofXrkZfZ6DVmq%2Fho79MC967zpVE0vnVibAQ0oVx6baGghGBWzvbH5OGizc4rvnQa1I2I%2BtxCjUBmqFNiAA&uploadId=3D07E776DE38437A99B48E5F15457E49&x-oss-access-key-id=STS.NTGdNgxpDaJyU7qjGm2J6kyBP&x-oss-expires=1723377825&x-oss-signature=NFZp5WwrOBHxcwvldLnKhu1uQyB%2FCHH9cThALeEPlu4%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>66B89AC56CD79F36318FDFE0</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"079E8E1B01F1F258B6091FA2B6587710"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2024-08-11 11:04:39 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/V4qrXp6A%2F889478%2F665854886737a81a44204a04b13348d548bfe319%2F66b89a918bbdb8fc74fc428a9b4aab84d5ae7862?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5fyL%2FTTla9l1oiSVxHAjkc4PsUahLzpsjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVf0ETyrq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnewz7UTzvci4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iBFm6oPXtuMkagAE%2FuNGU0cDBFcZc7TTrqXdG1h5Uode%2FkEB3F%2FeJaVot0TDzGtvpqM34CGfUobSKurNFQcy2HB0mqV88XV5Jzv1FAwzHy1ofXrkZfZ6DVmq%2Fho79MC967zpVE0vnVibAQ0oVx6baGghGBWzvbH5OGizc4rvnQa1I2I%2BtxCjUBmqFNiAA&uploadId=3D07E776DE38437A99B48E5F15457E49&x-oss-access-key-id=STS.NTGdNgxpDaJyU7qjGm2J6kyBP&x-oss-expires=1723377825&x-oss-signature=NFZp5WwrOBHxcwvldLnKhu1uQyB%2FCHH9cThALeEPlu4%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>66B89AC655B15630374252A3</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"079E8E1B01F1F258B6091FA2B6587710"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2024-08-11 11:04:39 - ERROR - aliyundrive.py - 1077 - File tmp/119113204/119113204_p0.jpg Part 1 upload failed.
2024-08-11 11:18:28 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /x7SRKqLY%2F889478%2F66b89de66808375c7ca74a32ba3c0eb5cd72232a%2F66b89de66969a94d2fef4f3a9bc6a882797e7b9d?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WGGs%2FVmLh43aGhc3SAtG08Tv9glfH80Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNST5ADurq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneU3MMjJtCObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuimMI7zfXtuMkagAGIAqhaTl1I70XYXXUfd7XGi5iMf1jr8Y3Rjj7RDq5inqM1G7eFE2ZIVOJtZM3MxcYq6ncKr%2BTcZKkx0A6ThzZzBPESNLTK20xaRbngGvBvqi7%2BhMS7II0EkqObaTXzrx7GbSoSbJC3hGVL1ya1ZiLt9cxZjroaGPY0H1FdxcUAmSAA&uploadId=3CA0E227CC6546C093B7397BDC0E474B&x-oss-access-key-id=STS.NV3QuaugYjcJqR1PmiBpLz4W3&x-oss-expires=1723378678&x-oss-signature=CTNrcRE%2FhsTzQnfZhKVPEQ%2Ft2u8%2FCSwPOYQIDGwn5T4%3D&x-oss-signature-version=OSS2
2024-08-11 11:21:18 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/06/08/09/12/03/119443572_p0.png
2024-08-11 11:28:45 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /udioyz4b%2F889478%2F66755d9548ed8eaa4240463db745067800999888%2F66b8a0382a3af3e4629c4fe3a8a83eeb3cbb8da0?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5WGGs%2FVmLh43aGhc3SAtG08Tv9glfH80Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNST5ADurq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneU3MMjJtCObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuimMI7zfXtuMkagAGIAqhaTl1I70XYXXUfd7XGi5iMf1jr8Y3Rjj7RDq5inqM1G7eFE2ZIVOJtZM3MxcYq6ncKr%2BTcZKkx0A6ThzZzBPESNLTK20xaRbngGvBvqi7%2BhMS7II0EkqObaTXzrx7GbSoSbJC3hGVL1ya1ZiLt9cxZjroaGPY0H1FdxcUAmSAA&uploadId=B79B3AB4BA144ABAADC02AF05D140FBD&x-oss-access-key-id=STS.NV3QuaugYjcJqR1PmiBpLz4W3&x-oss-expires=1723379272&x-oss-signature=MDPihRJLxiDe%2F5ZI4AeqGPMf7yGA29Yef3QNWCWTjAs%3D&x-oss-signature-version=OSS2
2024-08-11 11:35:36 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /GqFrp0aM%2F889478%2F66b7446f28eabe7ed15f40619b48e7d4116b1daf%2F66b8a1ea5fd735742dad415d9baeac8d27110429?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WGGs%2FVmLh43aGhc3SAtG08Tv9glfH80Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNST5ADurq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneU3MMjJtCObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuimMI7zfXtuMkagAGIAqhaTl1I70XYXXUfd7XGi5iMf1jr8Y3Rjj7RDq5inqM1G7eFE2ZIVOJtZM3MxcYq6ncKr%2BTcZKkx0A6ThzZzBPESNLTK20xaRbngGvBvqi7%2BhMS7II0EkqObaTXzrx7GbSoSbJC3hGVL1ya1ZiLt9cxZjroaGPY0H1FdxcUAmSAA&uploadId=836FCC2518D9494485759723597677B2&x-oss-access-key-id=STS.NV3QuaugYjcJqR1PmiBpLz4W3&x-oss-expires=1723379706&x-oss-signature=Iwu%2Bub8u6urHQQszOvvwr9mT9bf%2FZXw3Efxk8IIVvc4%3D&x-oss-signature-version=OSS2
2024-08-11 11:40:15 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/06/16/00/01/08/119671898_p0.jpg
2024-08-11 11:45:05 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/05/06/01/13/47/98137710_p0.jpg
2024-08-11 11:50:48 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /nq4g3GAQ%2F889478%2F66b8a5791fe132f2c65446d183f04ffb7d6f66b3%2F66b8a579552f410afaf44673a8485c4a7cf1d6cd?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WGGs%2FVmLh43aGhc3SAtG08Tv9glfH80Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNST5ADurq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneU3MMjJtCObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuimMI7zfXtuMkagAGIAqhaTl1I70XYXXUfd7XGi5iMf1jr8Y3Rjj7RDq5inqM1G7eFE2ZIVOJtZM3MxcYq6ncKr%2BTcZKkx0A6ThzZzBPESNLTK20xaRbngGvBvqi7%2BhMS7II0EkqObaTXzrx7GbSoSbJC3hGVL1ya1ZiLt9cxZjroaGPY0H1FdxcUAmSAA&uploadId=6806F2D04AFB460A842B8E60E5868ED2&x-oss-access-key-id=STS.NV3QuaugYjcJqR1PmiBpLz4W3&x-oss-expires=1723380618&x-oss-signature=GJZNKdpcIWY40a7jMJ9hNYbD9AoKpZD6i7n5Je%2BNTKc%3D&x-oss-signature-version=OSS2
2024-08-11 11:57:33 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/05/12/00/00/23/118643992_p0.jpg
2024-08-11 12:02:35 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /uAx5WegB%2F889478%2F65faccc0766e1c6a8e0d49dda452a56fa784c590%2F66b8a8354c35ebcb24464645bb9c60bdecc7170b?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WGGs%2FVmLh43aGhc3SAtG08Tv9glfH80Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNST5ADurq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneU3MMjJtCObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuimMI7zfXtuMkagAGIAqhaTl1I70XYXXUfd7XGi5iMf1jr8Y3Rjj7RDq5inqM1G7eFE2ZIVOJtZM3MxcYq6ncKr%2BTcZKkx0A6ThzZzBPESNLTK20xaRbngGvBvqi7%2BhMS7II0EkqObaTXzrx7GbSoSbJC3hGVL1ya1ZiLt9cxZjroaGPY0H1FdxcUAmSAA&uploadId=5BCB6D22CDEA48BDB063296FED1F144B&x-oss-access-key-id=STS.NV3QuaugYjcJqR1PmiBpLz4W3&x-oss-expires=1723381317&x-oss-signature=bpHxfS8DgxHy7HpfjH3njB24wpuRCQL4CBVrnj%2B2cos%3D&x-oss-signature-version=OSS2
2024-08-11 12:16:56 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /YyKzIfHY%2F889478%2F6698f6e8521fbeda3d114093b1d1c161d5f90580%2F66b8ab9a88fb08c94880478fa71e358e52a793d0?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WGGs%2FVmLh43aGhc3SAtG08Tv9glfH80Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNST5ADurq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneU3MMjJtCObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuimMI7zfXtuMkagAGIAqhaTl1I70XYXXUfd7XGi5iMf1jr8Y3Rjj7RDq5inqM1G7eFE2ZIVOJtZM3MxcYq6ncKr%2BTcZKkx0A6ThzZzBPESNLTK20xaRbngGvBvqi7%2BhMS7II0EkqObaTXzrx7GbSoSbJC3hGVL1ya1ZiLt9cxZjroaGPY0H1FdxcUAmSAA&uploadId=3480218FA6FE460C8856476AD78815B6&x-oss-access-key-id=STS.NV3QuaugYjcJqR1PmiBpLz4W3&x-oss-expires=1723382186&x-oss-signature=AWWtCvZGhQ%2BhHEsryCptuSD3O3agfGgDADo9gkIcqzk%3D&x-oss-signature-version=OSS2
2024-08-11 12:16:59 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-08-11 12:29:42 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /HXju971B%2F889478%2F66639ec1bbd6946ad4044819984224f73ec31a0a%2F66b8ae9847c71d456dd14e4081e0f37b1bc751b2?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WGGs%2FVmLh43aGhc3SAtG08Tv9glfH80Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNST5ADurq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneU3MMjJtCObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuimMI7zfXtuMkagAGIAqhaTl1I70XYXXUfd7XGi5iMf1jr8Y3Rjj7RDq5inqM1G7eFE2ZIVOJtZM3MxcYq6ncKr%2BTcZKkx0A6ThzZzBPESNLTK20xaRbngGvBvqi7%2BhMS7II0EkqObaTXzrx7GbSoSbJC3hGVL1ya1ZiLt9cxZjroaGPY0H1FdxcUAmSAA&uploadId=6E9FA793917E4E51958C168776FB4E3B&x-oss-access-key-id=STS.NV3QuaugYjcJqR1PmiBpLz4W3&x-oss-expires=1723382952&x-oss-signature=gClDaUCBLKlH8505mIzNasNj%2FDrX%2BWlOoe9wtXB%2Fjdg%3D&x-oss-signature-version=OSS2
2024-08-11 12:38:12 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/04/19/18/25/18/117973663_p0.jpg
2024-08-11 12:43:36 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /ZoHKGYg8%2F889478%2F65a132ad4f5b435658364ddebeb48bc712bb8cc7%2F66b8b1dac70b53b3ec7940aeb8896b1224d11d95?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WGGs%2FVmLh43aGhc3SAtG08Tv9glfH80Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNST5ADurq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneU3MMjJtCObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuimMI7zfXtuMkagAGIAqhaTl1I70XYXXUfd7XGi5iMf1jr8Y3Rjj7RDq5inqM1G7eFE2ZIVOJtZM3MxcYq6ncKr%2BTcZKkx0A6ThzZzBPESNLTK20xaRbngGvBvqi7%2BhMS7II0EkqObaTXzrx7GbSoSbJC3hGVL1ya1ZiLt9cxZjroaGPY0H1FdxcUAmSAA&uploadId=BF5577B4B81A40B9B6D3059E94ABB494&x-oss-access-key-id=STS.NV3QuaugYjcJqR1PmiBpLz4W3&x-oss-expires=1723383786&x-oss-signature=50qb%2BVW1GCt%2BL%2B4JmO%2F%2B9%2FmRARqvMLDF4tQq2XTTVo0%3D&x-oss-signature-version=OSS2
2024-08-11 12:59:36 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /plThq06o%2F889478%2F63fddef0682dce8a9f914be4a78d0b272f593f98%2F66b8b599950d2be7f544446a821c01e79376c231?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WGGs%2FVmLh43aGhc3SAtG08Tv9glfH80Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNST5ADurq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneU3MMjJtCObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuimMI7zfXtuMkagAGIAqhaTl1I70XYXXUfd7XGi5iMf1jr8Y3Rjj7RDq5inqM1G7eFE2ZIVOJtZM3MxcYq6ncKr%2BTcZKkx0A6ThzZzBPESNLTK20xaRbngGvBvqi7%2BhMS7II0EkqObaTXzrx7GbSoSbJC3hGVL1ya1ZiLt9cxZjroaGPY0H1FdxcUAmSAA&uploadId=A54C2B8B9D134EB99F6E58972B5746CC&x-oss-access-key-id=STS.NV3QuaugYjcJqR1PmiBpLz4W3&x-oss-expires=1723384745&x-oss-signature=Dt8VWRy1U2LLG1mR0jFYOUPNjS%2FlXSVkjYUmlTFM%2F7g%3D&x-oss-signature-version=OSS2
2024-08-11 12:59:39 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/plThq06o%2F889478%2F63fddef0682dce8a9f914be4a78d0b272f593f98%2F66b8b599950d2be7f544446a821c01e79376c231?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WGGs%2FVmLh43aGhc3SAtG08Tv9glfH80Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNST5ADurq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneU3MMjJtCObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuimMI7zfXtuMkagAGIAqhaTl1I70XYXXUfd7XGi5iMf1jr8Y3Rjj7RDq5inqM1G7eFE2ZIVOJtZM3MxcYq6ncKr%2BTcZKkx0A6ThzZzBPESNLTK20xaRbngGvBvqi7%2BhMS7II0EkqObaTXzrx7GbSoSbJC3hGVL1ya1ZiLt9cxZjroaGPY0H1FdxcUAmSAA&uploadId=A54C2B8B9D134EB99F6E58972B5746CC&x-oss-access-key-id=STS.NV3QuaugYjcJqR1PmiBpLz4W3&x-oss-expires=1723384745&x-oss-signature=Dt8VWRy1U2LLG1mR0jFYOUPNjS%2FlXSVkjYUmlTFM%2F7g%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>66B8B5B9243EF03330F03163</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"5F8AF4EC344BF7F4D03F42623BBC8116"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2024-08-11 12:59:40 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/plThq06o%2F889478%2F63fddef0682dce8a9f914be4a78d0b272f593f98%2F66b8b599950d2be7f544446a821c01e79376c231?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WGGs%2FVmLh43aGhc3SAtG08Tv9glfH80Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNST5ADurq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneU3MMjJtCObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuimMI7zfXtuMkagAGIAqhaTl1I70XYXXUfd7XGi5iMf1jr8Y3Rjj7RDq5inqM1G7eFE2ZIVOJtZM3MxcYq6ncKr%2BTcZKkx0A6ThzZzBPESNLTK20xaRbngGvBvqi7%2BhMS7II0EkqObaTXzrx7GbSoSbJC3hGVL1ya1ZiLt9cxZjroaGPY0H1FdxcUAmSAA&uploadId=A54C2B8B9D134EB99F6E58972B5746CC&x-oss-access-key-id=STS.NV3QuaugYjcJqR1PmiBpLz4W3&x-oss-expires=1723384745&x-oss-signature=Dt8VWRy1U2LLG1mR0jFYOUPNjS%2FlXSVkjYUmlTFM%2F7g%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>66B8B5BB90232A3138F7053E</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"5F8AF4EC344BF7F4D03F42623BBC8116"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2024-08-11 12:59:42 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/plThq06o%2F889478%2F63fddef0682dce8a9f914be4a78d0b272f593f98%2F66b8b599950d2be7f544446a821c01e79376c231?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WGGs%2FVmLh43aGhc3SAtG08Tv9glfH80Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNST5ADurq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneU3MMjJtCObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuimMI7zfXtuMkagAGIAqhaTl1I70XYXXUfd7XGi5iMf1jr8Y3Rjj7RDq5inqM1G7eFE2ZIVOJtZM3MxcYq6ncKr%2BTcZKkx0A6ThzZzBPESNLTK20xaRbngGvBvqi7%2BhMS7II0EkqObaTXzrx7GbSoSbJC3hGVL1ya1ZiLt9cxZjroaGPY0H1FdxcUAmSAA&uploadId=A54C2B8B9D134EB99F6E58972B5746CC&x-oss-access-key-id=STS.NV3QuaugYjcJqR1PmiBpLz4W3&x-oss-expires=1723384745&x-oss-signature=Dt8VWRy1U2LLG1mR0jFYOUPNjS%2FlXSVkjYUmlTFM%2F7g%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>66B8B5BC816E64333163ABCC</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"5F8AF4EC344BF7F4D03F42623BBC8116"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2024-08-11 12:59:42 - ERROR - aliyundrive.py - 1077 - File tmp/105503771/105503771_p15.jpg Part 1 upload failed.
2024-08-11 13:01:19 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/02/14/53/58/114781707_p0.png
2024-08-11 13:02:43 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/04/13/00/30/07/117783120_p0.jpg
2024-08-11 13:06:58 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/03/23/00/47/27/117159689_p0.jpg
2024-08-11 13:14:38 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /970IMMtA%2F889478%2F66b8b92067fa486e0ab84085ae94578a6af3edec%2F66b8b9200b2078161ba844c680fd1adf4b27e894?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WGGs%2FVmLh43aGhc3SAtG08Tv9glfH80Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNST5ADurq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneU3MMjJtCObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuimMI7zfXtuMkagAGIAqhaTl1I70XYXXUfd7XGi5iMf1jr8Y3Rjj7RDq5inqM1G7eFE2ZIVOJtZM3MxcYq6ncKr%2BTcZKkx0A6ThzZzBPESNLTK20xaRbngGvBvqi7%2BhMS7II0EkqObaTXzrx7GbSoSbJC3hGVL1ya1ZiLt9cxZjroaGPY0H1FdxcUAmSAA&uploadId=754FC027C5F749C9BDDE765550CA4F02&x-oss-access-key-id=STS.NV3QuaugYjcJqR1PmiBpLz4W3&x-oss-expires=1723385648&x-oss-signature=YoYXX7A5opQgMvG03y0DsSw6BjHD0R%2BRu2%2BkiFZdFEg%3D&x-oss-signature-version=OSS2
2024-08-11 13:32:07 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-08-11 13:32:08 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-08-11 13:35:59 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /CgEk72WM%2F889478%2F66b8be210f2fd94697024c009723fdead1eb70b9%2F66b8be21a206a108918340dc9bb328aa4c616154?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WGGs%2FVmLh43aGhc3SAtG08Tv9glfH80Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNST5ADurq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneU3MMjJtCObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuimMI7zfXtuMkagAGIAqhaTl1I70XYXXUfd7XGi5iMf1jr8Y3Rjj7RDq5inqM1G7eFE2ZIVOJtZM3MxcYq6ncKr%2BTcZKkx0A6ThzZzBPESNLTK20xaRbngGvBvqi7%2BhMS7II0EkqObaTXzrx7GbSoSbJC3hGVL1ya1ZiLt9cxZjroaGPY0H1FdxcUAmSAA&uploadId=545997B2D1B542DD9EC55057A5657B42&x-oss-access-key-id=STS.NV3QuaugYjcJqR1PmiBpLz4W3&x-oss-expires=1723386929&x-oss-signature=yeUJvsMPePHFMKMr1GL2KczxjmSmFjCGBWes15%2B6M%2FM%3D&x-oss-signature-version=OSS2
2024-08-11 13:36:30 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /CgEk72WM%2F889478%2F66b8be210f2fd94697024c009723fdead1eb70b9%2F66b8be21a206a108918340dc9bb328aa4c616154?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WGGs%2FVmLh43aGhc3SAtG08Tv9glfH80Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNST5ADurq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneU3MMjJtCObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuimMI7zfXtuMkagAGIAqhaTl1I70XYXXUfd7XGi5iMf1jr8Y3Rjj7RDq5inqM1G7eFE2ZIVOJtZM3MxcYq6ncKr%2BTcZKkx0A6ThzZzBPESNLTK20xaRbngGvBvqi7%2BhMS7II0EkqObaTXzrx7GbSoSbJC3hGVL1ya1ZiLt9cxZjroaGPY0H1FdxcUAmSAA&uploadId=545997B2D1B542DD9EC55057A5657B42&x-oss-access-key-id=STS.NV3QuaugYjcJqR1PmiBpLz4W3&x-oss-expires=1723386929&x-oss-signature=yeUJvsMPePHFMKMr1GL2KczxjmSmFjCGBWes15%2B6M%2FM%3D&x-oss-signature-version=OSS2
2024-08-11 13:40:50 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/05/13/00/24/02/118680479_p0.jpg
2024-08-11 13:41:41 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/03/14/10/00/01/116903005_p0.png
2024-08-11 13:53:51 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /M8xDX8zz%2F889478%2F65fac94ac4ac0f8e11a645a4a07278b4410cc88b%2F66b8c250bcbea95cef134aa3a09e676f21c26a50?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WGGs%2FVmLh43aGhc3SAtG08Tv9glfH80Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNST5ADurq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneU3MMjJtCObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuimMI7zfXtuMkagAGIAqhaTl1I70XYXXUfd7XGi5iMf1jr8Y3Rjj7RDq5inqM1G7eFE2ZIVOJtZM3MxcYq6ncKr%2BTcZKkx0A6ThzZzBPESNLTK20xaRbngGvBvqi7%2BhMS7II0EkqObaTXzrx7GbSoSbJC3hGVL1ya1ZiLt9cxZjroaGPY0H1FdxcUAmSAA&uploadId=2B7A4755705D4928AD20D185006B6180&x-oss-access-key-id=STS.NV3QuaugYjcJqR1PmiBpLz4W3&x-oss-expires=1723388000&x-oss-signature=NuL989Wo0pFQPvQJ%2FSTbRM%2BFpGYgGvkIyxqkUIaCA90%3D&x-oss-signature-version=OSS2
2024-08-11 22:17:28 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-08-11 22:22:02 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/07/14/00/00/28/120503348_p0.jpg
2024-08-11 23:01:15 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/07/13/04/38/00/120478202_p0.jpg
2024-08-11 23:35:13 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/04/21/13/45/19/118030834_p0.jpg
2024-08-11 23:35:28 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/04/29/08/00/04/118256483_p0.jpg
2024-08-11 23:52:12 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/12/06/19/15/39/103390989_p0.png
2024-08-12 00:16:29 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
