2024-12-21 22:46:37 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /4k4UDcF9%2F889478%2F66697832db1b3b589eb846eeaa057ebc715df088%2F6767452fabbedefa47b44f4d953009dd94826f60?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WDDdPu1IdM9oqqVh%2BEsjg%2FY9tOq67ghTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVesTmSAq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew%2F5X%2FUW17uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiinnYT%2FXtuMkagAGKqOHb%2FtBi3lRl%2F660AtRI8sNJEIjL1woyhRE4GAuqHPQWfJSsnfmJrJKA5Y7GejrDnyzO9hmn7n7FdxUheiDAcA6Bsiv82C1maNU0dJxIIFauNrjMP%2Fhf1x6fxwMxVhI%2FotO4Mb0OyuN84Ibmq%2Bh10guX%2B24yCuPtJ%2BrwdMoOkiAA&uploadId=C2A44DD53EB149C1BB01925E42C73B4D&x-oss-access-key-id=STS.NV6FiZ9XmAHAT95V8joTbDkKg&x-oss-expires=1734824767&x-oss-signature=WyRDdhtSdRN%2FPXJyyAoDp%2BGpw14p8YHD9J%2Fa%2Fb3K4gY%3D&x-oss-signature-version=OSS2
2024-12-21 22:50:48 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-12-21 22:50:49 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-12-21 22:59:46 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /cUs6271J%2F889478%2F65ba1eac9aba5c6614cc4eb39ebc702ef875b6f6%2F67674840f09de8319c1d4f97b10267ca3b0961c4?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5WDDdPu1IdM9oqqVh%2BEsjg%2FY9tOq67ghTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVesTmSAq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew%2F5X%2FUW17uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiinnYT%2FXtuMkagAGKqOHb%2FtBi3lRl%2F660AtRI8sNJEIjL1woyhRE4GAuqHPQWfJSsnfmJrJKA5Y7GejrDnyzO9hmn7n7FdxUheiDAcA6Bsiv82C1maNU0dJxIIFauNrjMP%2Fhf1x6fxwMxVhI%2FotO4Mb0OyuN84Ibmq%2Bh10guX%2B24yCuPtJ%2BrwdMoOkiAA&uploadId=91590FE5E91C43E8959CC44FEB5501FC&x-oss-access-key-id=STS.NV6FiZ9XmAHAT95V8joTbDkKg&x-oss-expires=1734825552&x-oss-signature=SbqJpgORb9yw%2FjN4e6X2lY0AXuQqRZrZ1F6NO%2Fc9O3o%3D&x-oss-signature-version=OSS2
2024-12-21 23:10:06 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/113838114/113838114_p0.gif, upload original page.
2024-12-21 23:13:51 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /F1c1Gr7Y%2F889478%2F6705d70944b8879f1a244bf8aeae631ba3909054%2F67674b913e03579a48b443cb822a15a889636a65?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WDDdPu1IdM9oqqVh%2BEsjg%2FY9tOq67ghTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVesTmSAq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew%2F5X%2FUW17uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiinnYT%2FXtuMkagAGKqOHb%2FtBi3lRl%2F660AtRI8sNJEIjL1woyhRE4GAuqHPQWfJSsnfmJrJKA5Y7GejrDnyzO9hmn7n7FdxUheiDAcA6Bsiv82C1maNU0dJxIIFauNrjMP%2Fhf1x6fxwMxVhI%2FotO4Mb0OyuN84Ibmq%2Bh10guX%2B24yCuPtJ%2BrwdMoOkiAA&uploadId=643DC029136645048917437451985FAF&x-oss-access-key-id=STS.NV6FiZ9XmAHAT95V8joTbDkKg&x-oss-expires=1734826401&x-oss-signature=nTI%2F0nWPlqeGsq5xCBOekjeLToLdhhFGG3FzaQ%2BR9N0%3D&x-oss-signature-version=OSS2
2024-12-21 23:16:34 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-12-21 23:16:35 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-12-21 23:26:50 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /9TS0kiPm%2F889478%2F67666f744a6b56b182ad4cb8a0906fb2abed0164%2F67674e9bd40003b74cb447d2959de7285af4c8de?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WDDdPu1IdM9oqqVh%2BEsjg%2FY9tOq67ghTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVesTmSAq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew%2F5X%2FUW17uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiinnYT%2FXtuMkagAGKqOHb%2FtBi3lRl%2F660AtRI8sNJEIjL1woyhRE4GAuqHPQWfJSsnfmJrJKA5Y7GejrDnyzO9hmn7n7FdxUheiDAcA6Bsiv82C1maNU0dJxIIFauNrjMP%2Fhf1x6fxwMxVhI%2FotO4Mb0OyuN84Ibmq%2Bh10guX%2B24yCuPtJ%2BrwdMoOkiAA&uploadId=59E4BF1EA9D048A388AED3512C162A10&x-oss-access-key-id=STS.NV6FiZ9XmAHAT95V8joTbDkKg&x-oss-expires=1734827179&x-oss-signature=FHJDesLVt1UY8T%2F6O8AZqiqwg%2FGtY3kKwY3S0LGAOcE%3D&x-oss-signature-version=OSS2
2024-12-21 23:30:23 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/07/30/10/58/30/110364999_p0.jpg
2024-12-21 23:39:47 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /LEdR6qjE%2F889478%2F6740753a741538c54dbd4439a408611fdf8da8b9%2F676751a4b2f964321ea9416b9eefc4d202288b10?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WDDdPu1IdM9oqqVh%2BEsjg%2FY9tOq67ghTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVesTmSAq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew%2F5X%2FUW17uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiinnYT%2FXtuMkagAGKqOHb%2FtBi3lRl%2F660AtRI8sNJEIjL1woyhRE4GAuqHPQWfJSsnfmJrJKA5Y7GejrDnyzO9hmn7n7FdxUheiDAcA6Bsiv82C1maNU0dJxIIFauNrjMP%2Fhf1x6fxwMxVhI%2FotO4Mb0OyuN84Ibmq%2Bh10guX%2B24yCuPtJ%2BrwdMoOkiAA&uploadId=F7F32874E535411F9A001F78D7C4810B&x-oss-access-key-id=STS.NV6FiZ9XmAHAT95V8joTbDkKg&x-oss-expires=1734827956&x-oss-signature=JrrfWuKA3kBMjvgOTgmkNBPdIqrkp72dVwm%2FLHP3KzQ%3D&x-oss-signature-version=OSS2
2024-12-21 23:52:24 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /ECgU9ZYF%2F889478%2F676663594790b5df3ca54eb6819ba3ba95f49474%2F6767549925f58e85c461415aa845a025180af73f?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WDDdPu1IdM9oqqVh%2BEsjg%2FY9tOq67ghTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVesTmSAq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew%2F5X%2FUW17uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiinnYT%2FXtuMkagAGKqOHb%2FtBi3lRl%2F660AtRI8sNJEIjL1woyhRE4GAuqHPQWfJSsnfmJrJKA5Y7GejrDnyzO9hmn7n7FdxUheiDAcA6Bsiv82C1maNU0dJxIIFauNrjMP%2Fhf1x6fxwMxVhI%2FotO4Mb0OyuN84Ibmq%2Bh10guX%2B24yCuPtJ%2BrwdMoOkiAA&uploadId=D7E416DB37DE4EC09C5060205ED42B92&x-oss-access-key-id=STS.NV6FiZ9XmAHAT95V8joTbDkKg&x-oss-expires=1734828713&x-oss-signature=KkOXCvRuxgSA%2BP63ULzZHLVOWkPKQuIGk%2FFJJcJc9bo%3D&x-oss-signature-version=OSS2
2024-12-22 00:05:44 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /2joBT6SB%2F889478%2F6750d73893006c96acc44950a2094460157f8e7e%2F676757ba0057657f30b848b0923bfbbcb099df85?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WDDdPu1IdM9oqqVh%2BEsjg%2FY9tOq67ghTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVesTmSAq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew%2F5X%2FUW17uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiinnYT%2FXtuMkagAGKqOHb%2FtBi3lRl%2F660AtRI8sNJEIjL1woyhRE4GAuqHPQWfJSsnfmJrJKA5Y7GejrDnyzO9hmn7n7FdxUheiDAcA6Bsiv82C1maNU0dJxIIFauNrjMP%2Fhf1x6fxwMxVhI%2FotO4Mb0OyuN84Ibmq%2Bh10guX%2B24yCuPtJ%2BrwdMoOkiAA&uploadId=AEE79D987818427BB6ECBD2D1D59BC97&x-oss-access-key-id=STS.NV6FiZ9XmAHAT95V8joTbDkKg&x-oss-expires=1734829514&x-oss-signature=312A%2B2jj2u2h7NiT6h5N1teAdOR4YMi3UG4AT4cR1ZY%3D&x-oss-signature-version=OSS2
2024-12-22 00:11:11 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-12-22 00:19:30 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /tRsNhlQf%2F889478%2F6766570b1c3471a604ea495b9a8f393d09d441ba%2F67675af4ce1f649a390045ef83ae88d4e2bdf6f9?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WDDdPu1IdM9oqqVh%2BEsjg%2FY9tOq67ghTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVesTmSAq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew%2F5X%2FUW17uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiinnYT%2FXtuMkagAGKqOHb%2FtBi3lRl%2F660AtRI8sNJEIjL1woyhRE4GAuqHPQWfJSsnfmJrJKA5Y7GejrDnyzO9hmn7n7FdxUheiDAcA6Bsiv82C1maNU0dJxIIFauNrjMP%2Fhf1x6fxwMxVhI%2FotO4Mb0OyuN84Ibmq%2Bh10guX%2B24yCuPtJ%2BrwdMoOkiAA&uploadId=904532EE23B94B32A53442F5929B84B7&x-oss-access-key-id=STS.NV6FiZ9XmAHAT95V8joTbDkKg&x-oss-expires=1734830340&x-oss-signature=4kddimdChrC1cPf3vR1N3JuUgmsKn%2Bc4%2FkmYFrU390M%3D&x-oss-signature-version=OSS2
2024-12-22 00:23:43 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/08/17/19/28/27/121578673_p0.jpg
2024-12-22 00:31:18 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-12-22 00:31:19 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-12-22 00:34:39 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /LnFQyMGq%2F889478%2F651e8fc7da6a128b39934bb78335c79c9ce0ac53%2F67675e81259d67e62c724e1c9ddb882826d1d2f9?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WDDdPu1IdM9oqqVh%2BEsjg%2FY9tOq67ghTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVesTmSAq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew%2F5X%2FUW17uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiinnYT%2FXtuMkagAGKqOHb%2FtBi3lRl%2F660AtRI8sNJEIjL1woyhRE4GAuqHPQWfJSsnfmJrJKA5Y7GejrDnyzO9hmn7n7FdxUheiDAcA6Bsiv82C1maNU0dJxIIFauNrjMP%2Fhf1x6fxwMxVhI%2FotO4Mb0OyuN84Ibmq%2Bh10guX%2B24yCuPtJ%2BrwdMoOkiAA&uploadId=4A23F3956905400A8A2FBB7890C65B13&x-oss-access-key-id=STS.NV6FiZ9XmAHAT95V8joTbDkKg&x-oss-expires=1734831249&x-oss-signature=GBDS1uKcBRPic5n6lEg5kPaUESZG01TDvFou3s401Uw%3D&x-oss-signature-version=OSS2
2024-12-22 05:12:54 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-12-22 05:51:41 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/08/11/18/52/45/121393232_p0.png
2024-12-22 06:00:59 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /OQ3wKxJ5%2F889478%2F67011a456c36eea58a6d40ad93b4a2ca26fc6117%2F6767aafd8970c6c35a9e4b93947af08ab99533a1?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f%2FAfDNh4lS1vSTenD6oG0nOeZ%2B24j5rjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWOwMWOAq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA3xSziu17uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSimq2IUfXtuMkagAGL9j2K08aufMPuaznu32qwHMEOPU06eI1NFRwJ85ySHNVlJOKoThXPEW%2B6Lzqroc2l3Zxeki7rZcPxTY%2FDBdVffcQbqpz7n0msRo48xq15gvZFV5P1k0HsJXCSboOuzgYlyvQtNKyXua6Io6yhzkdk07QloEQcaG66tXngCa%2F8SyAA&uploadId=9A8A97EAB7B74556B227EC40E149908E&x-oss-access-key-id=STS.NTJJJyjVsa6xxVKDmr5iR4MRL&x-oss-expires=1734850829&x-oss-signature=A%2FN2Hg3ef8rwkkImyZYvJ9z1IicpWRHmshSmYS3E7j0%3D&x-oss-signature-version=OSS2
2024-12-22 06:01:46 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/08/02/00/01/03/121091464_p0.jpg
2024-12-22 06:05:04 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/11/04/17/12/05/123990875_p0.jpg
2024-12-22 06:08:41 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/12/16/18/17/15/125244678_p0.png
2024-12-22 06:12:07 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/12/09/20/21/29/125042709_p0.jpg
2024-12-22 06:15:05 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/07/15/18/09/23/120557655_p0.png
2024-12-22 06:52:03 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/12/07/18/20/40/124976732_p0.jpg
2024-12-22 07:11:55 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-12-22 07:21:40 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/06/26/17/30/21/119990504_p0.png
2024-12-22 07:27:39 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/10/17/00/41/00/123397511_p0.png
2024-12-22 07:42:37 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /TpicjcmA%2F889478%2F666c30956145eb208a3b4fffb43bcfb8d623d28c%2F6767c2cf763100d4707548d0a71cb08d80929968?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5DYOPzOlL5g1PusVlDBpkRsYcdInpLggzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVaDIFqAq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew5bJzC32i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i8z3tLvXtuMkagAGGumRWAknuxty7mX6RTEtU26lS2vPgGvcjPuhDZbDZZ3WgIEw9MfGm6l2uV57DsoJHuPbAVvD2BXZFWksNGz1BODLiJt7LFseHzIj92FvgC4hRgpVnyHgTX0YjTjuph3xIFh6L1%2Fz%2FMk6TSHYlzs3%2F%2B6vgX5TL8X7cGqyNTtYUQSAA&uploadId=FB77CF7296764943A90DE44AC91C5F6B&x-oss-access-key-id=STS.NSmsFzyaAc9GTvpBD9mHdqWKa&x-oss-expires=1734856927&x-oss-signature=DuXxkCAfkxMuIo%2BVC7s6Sgpuxurtz4i4M8Jvgos23lg%3D&x-oss-signature-version=OSS2
2024-12-22 07:49:58 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/BIkCth2L%2F889478%2F66eeb2401b537742eae54244b4e492afcd577a8e%2F6767c4a60de29c87120841c18c23ce4a74919764?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5DYOPzOlL5g1PusVlDBpkRsYcdInpLggzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVaDIFqAq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew5bJzC32i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i8z3tLvXtuMkagAGGumRWAknuxty7mX6RTEtU26lS2vPgGvcjPuhDZbDZZ3WgIEw9MfGm6l2uV57DsoJHuPbAVvD2BXZFWksNGz1BODLiJt7LFseHzIj92FvgC4hRgpVnyHgTX0YjTjuph3xIFh6L1%2Fz%2FMk6TSHYlzs3%2F%2B6vgX5TL8X7cGqyNTtYUQSAA&uploadId=E52C8C776B974FA9A481F9A4D70E0F0E&x-oss-access-key-id=STS.NSmsFzyaAc9GTvpBD9mHdqWKa&x-oss-expires=1734857398&x-oss-signature=smYMAabUgcYrsNjZtIuDFLBv7Q3ByX3edJrRdWtCPC0%3D&x-oss-signature-version=OSS2:502:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>ServiceUnavailable</Code>
  <Message>Sorry, the page you are looking for is currently unavailable. Please try again later.</Message>
  <RequestId>6767C4A6415F1638370F2758</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
</Error>

2024-12-22 22:12:15 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-12-22 23:08:27 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/11/09/19/15/24/124135822_p0.jpg
2024-12-22 23:08:39 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/05/07/13/49/00/118516921_p0.jpg
2024-12-22 23:56:13 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/09/10/19/00/08/111610491_p0.jpg
2024-12-23 00:02:48 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/09/16/22/01/55/122498645_p0.jpg
2024-12-23 00:04:21 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/07/16/00/01/06/120569961_p0.png
2024-12-23 00:09:38 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/11/27/18/16/20/113758089_p0.jpg
2024-12-23 00:11:16 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
