2025-02-05 00:14:53 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060f117387144932618880e459e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:14:53 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:14:54 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-02-05 00:14:54 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060f117387144945288961e459e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:14:54 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:14:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-02-05 00:14:56 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060f117387144967731078e459e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:14:56 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:14:59 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-02-05 00:15:00 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060f117387145000191267e459e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:15:00 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:15:04 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-02-05 00:15:04 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/56627683/SWKL:D - 56627683.
2025-02-05 00:15:22 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701017387145228134213efee8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:15:22 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:15:23 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-02-05 00:15:24 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701017387145240514291efee8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:15:24 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:15:26 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-02-05 00:15:26 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701017387145262894475efee8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:15:26 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:15:29 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-02-05 00:15:29 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701017387145295294782efee8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:15:29 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:15:33 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-02-05 00:15:33 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/56627683/SWKL:D - 56627683.
2025-02-05 00:21:10 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/125207062/125207062_p0.gif, upload original page.
2025-02-05 00:21:10 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/125207062/125207062_p1.gif, upload original page.
2025-02-05 00:21:11 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/125207062/125207062_p2.gif, upload original page.
2025-02-05 00:21:11 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/125207062/125207062_p0.gif.
2025-02-05 00:21:11 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/125207062/125207062_p1.gif.
2025-02-05 00:21:11 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/125207062/125207062_p2.gif.
2025-02-05 00:21:29 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701517387148897624630e9d2e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:21:29 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:21:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-02-05 00:21:31 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701517387148910074748e9d2e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:21:31 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:21:33 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-02-05 00:21:33 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701517387148932735054e9d2e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:21:33 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:21:36 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-02-05 00:21:36 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701517387148965225495e9d2e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:21:36 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:21:40 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-02-05 00:21:40 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/56627683/SWKL:D - 56627683.
2025-02-05 00:24:06 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700917387150465052711e1e08","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:24:06 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:24:07 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-02-05 00:24:07 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700917387150477502804e1e08","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:24:07 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:24:09 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-02-05 00:24:10 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700917387150499982963e1e08","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:24:10 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:24:13 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-02-05 00:24:13 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700917387150532423262e1e08","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:24:13 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:24:17 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-02-05 00:24:17 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/56627683/SWKL:D - 56627683.
2025-02-05 00:25:42 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/12/18/23/36/20/125311062_p0.jpg
2025-02-05 00:33:45 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817387156256554893e578f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:33:45 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:33:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-02-05 00:33:47 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817387156268975028e578f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:33:47 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:33:49 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-02-05 00:33:49 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817387156291455405e578f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:33:49 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:33:52 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-02-05 00:33:52 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817387156323885754e578f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:33:52 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:33:56 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-02-05 00:33:56 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/56627683/SWKL:D - 56627683.
2025-02-05 00:38:39 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701417387159196686694ecfe3","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:38:39 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:38:40 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-02-05 00:38:41 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701417387159209136828ecfe3","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:38:41 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:38:43 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-02-05 00:38:43 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701417387159231697108ecfe3","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:38:43 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:38:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-02-05 00:38:46 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701417387159264207504ecfe3","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:38:46 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:38:50 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-02-05 00:38:50 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/56627683/SWKL:D - 56627683.
2025-02-05 00:40:39 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0c917387160395632951e49eb","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:40:39 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:40:40 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-02-05 00:40:40 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0c917387160408043091e49eb","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:40:40 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:40:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-02-05 00:40:43 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0c917387160430533303e49eb","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:40:43 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:40:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-02-05 00:40:46 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701a17387160467283113e3604","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:40:46 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:40:50 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-02-05 00:40:50 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/56627683/SWKL:D - 56627683.
2025-02-05 00:45:05 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060f617387163058146884ecb91","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:45:05 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:45:06 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-02-05 00:45:07 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060f617387163070617014ecb91","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:45:07 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:45:09 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-02-05 00:45:09 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060f617387163093297281ecb91","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:45:09 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:45:12 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-02-05 00:45:12 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060f617387163125747726ecb91","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:45:12 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:45:16 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-02-05 00:45:16 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/56627683/SWKL:D - 56627683.
2025-02-05 00:50:57 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0c917387166572578573e49de","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:50:57 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:50:58 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-02-05 00:50:58 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0c917387166584928721e49de","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:50:58 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:51:00 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-02-05 00:51:00 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0c917387166607328934e49de","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:51:00 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:51:03 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-02-05 00:51:04 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0c917387166639771312e49de","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2025-02-05 00:51:04 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-02-05 00:51:08 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-02-05 00:51:08 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/56627683/SWKL:D - 56627683.
2025-02-05 01:00:27 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2025/02/02/00/00/55/126798609_p0.jpg
2025-02-05 22:13:13 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2025-02-05 22:31:23 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/10/29/00/00/23/123770652_p0.png
2025-02-05 22:33:08 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/10/09/18/43/22/123176639_p0.png
2025-02-05 22:37:40 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/12/14/00/04/40/125160338_p0.jpg
2025-02-05 22:46:50 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/125207062/125207062_p0.gif, upload original page.
2025-02-05 22:46:50 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/125207062/125207062_p1.gif, upload original page.
2025-02-05 22:46:51 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/125207062/125207062_p2.gif, upload original page.
2025-02-05 22:46:51 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/125207062/125207062_p0.gif.
2025-02-05 22:46:51 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/125207062/125207062_p1.gif.
2025-02-05 22:46:51 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/125207062/125207062_p2.gif.
2025-02-05 23:02:50 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/17/17/26/51/115245312_p0.png
2025-02-05 23:10:06 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/10/26/00/00/09/102233016_p0.jpg
2025-02-05 23:25:14 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/11/08/11/34/14/124096782_p0.jpg
2025-02-05 23:39:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-05 23:39:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-02-05 23:40:20 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-05 23:40:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-02-05 23:40:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-05 23:40:55 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-02-05 23:41:26 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-05 23:41:30 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-02-05 23:41:30 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/122142461/122142461.json.txt.
2025-02-05 23:42:02 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-05 23:42:03 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-02-05 23:42:33 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-05 23:42:35 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-02-05 23:43:06 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-05 23:43:09 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-02-05 23:43:39 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-05 23:43:43 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-02-05 23:43:43 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/122142461/122142461_p0.jpg.
2025-02-05 23:44:14 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-05 23:44:15 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-02-05 23:44:45 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-05 23:44:47 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-02-05 23:45:17 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-05 23:45:20 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-02-05 23:45:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-05 23:45:56 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-02-05 23:45:56 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/3975343/freng - 3975343.
2025-02-05 23:46:26 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-05 23:46:27 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-02-05 23:46:58 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-05 23:47:00 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-02-05 23:47:30 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-05 23:47:33 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-02-05 23:53:49 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2025/02/03/00/02/21/126839449_p0.png
2025-02-05 23:55:36 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/12/09/17/21/54/125037946_p0.png
2025-02-05 23:58:01 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/113838114/113838114_p0.gif, upload original page.
2025-02-06 00:03:20 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2025/01/19/20/04/05/126374562_p0.jpg
2025-02-06 00:07:12 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/03/23/09/01/56/117167001_p0.jpg
2025-02-06 00:12:14 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2025-02-06 00:24:14 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2025/01/08/02/19/42/126010346_p0.jpg
2025-02-06 00:36:00 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /lPflFigB%2F889478%2F65bcde2790fd076c9c9943ea899e994ec3534d4f%2F67a403d1eb7ca3cd3ee64618934d8d6140ac0b61?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=08EF03B276704F83BF7DE538D6611F30&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738805729&x-oss-signature=v%2BaeGDvpQXjBj5FZhJAbhGuVToPJ6fUcPHeHmr%2B1iCQ%3D&x-oss-signature-version=OSS2
2025-02-06 00:36:02 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/lPflFigB%2F889478%2F65bcde2790fd076c9c9943ea899e994ec3534d4f%2F67a403d1eb7ca3cd3ee64618934d8d6140ac0b61?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=08EF03B276704F83BF7DE538D6611F30&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738805729&x-oss-signature=v%2BaeGDvpQXjBj5FZhJAbhGuVToPJ6fUcPHeHmr%2B1iCQ%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67A403F1624C19313459333E</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"367A6EE5428BA218A7AB27A131524CA6"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-02-06 00:36:02 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/lPflFigB%2F889478%2F65bcde2790fd076c9c9943ea899e994ec3534d4f%2F67a403d1eb7ca3cd3ee64618934d8d6140ac0b61?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=08EF03B276704F83BF7DE538D6611F30&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738805729&x-oss-signature=v%2BaeGDvpQXjBj5FZhJAbhGuVToPJ6fUcPHeHmr%2B1iCQ%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67A403F2D8670635374C376A</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"367A6EE5428BA218A7AB27A131524CA6"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-02-06 00:36:03 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/lPflFigB%2F889478%2F65bcde2790fd076c9c9943ea899e994ec3534d4f%2F67a403d1eb7ca3cd3ee64618934d8d6140ac0b61?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=08EF03B276704F83BF7DE538D6611F30&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738805729&x-oss-signature=v%2BaeGDvpQXjBj5FZhJAbhGuVToPJ6fUcPHeHmr%2B1iCQ%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67A403F231A034333499D528</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"367A6EE5428BA218A7AB27A131524CA6"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-02-06 00:36:03 - ERROR - aliyundrive.py - 1077 - File tmp/115458651/115458651.json.txt Part 1 upload failed.
2025-02-06 00:38:28 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-06 00:38:29 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-02-06 00:38:59 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-06 00:39:01 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-02-06 00:39:31 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-06 00:39:34 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-02-06 00:40:05 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-06 00:40:09 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-02-06 00:40:09 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/124646683/124646683_p0.png.
2025-02-06 00:40:40 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-02-06 00:40:41 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-02-06 00:45:13 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/08/24/00/00/27/121769880_p0.jpg
2025-02-06 01:25:58 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /3rOUfin1%2F889478%2F67092e25ec129a93ff2e4bd3b912ea76bbb6d622%2F67a40f7419f19b2ff3d449b7a7bce945cbe6035f?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=3A9D570B3EB54087AE9BA5A1D45AB305&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738808708&x-oss-signature=Lx4BbedfY5q%2BsZu3PYxYQmR1BbCM7M67VzWLD1SLync%3D&x-oss-signature-version=OSS2
2025-02-06 01:26:02 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/3rOUfin1%2F889478%2F67092e25ec129a93ff2e4bd3b912ea76bbb6d622%2F67a40f7419f19b2ff3d449b7a7bce945cbe6035f?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=3A9D570B3EB54087AE9BA5A1D45AB305&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738808708&x-oss-signature=Lx4BbedfY5q%2BsZu3PYxYQmR1BbCM7M67VzWLD1SLync%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67A40FA80B40B232399EF7E8</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"6AAE93347ED23A245026028A98AF919E"</PartEtag>
  <PartNumber>2</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-02-06 01:26:04 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/3rOUfin1%2F889478%2F67092e25ec129a93ff2e4bd3b912ea76bbb6d622%2F67a40f7419f19b2ff3d449b7a7bce945cbe6035f?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=3A9D570B3EB54087AE9BA5A1D45AB305&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738808708&x-oss-signature=Lx4BbedfY5q%2BsZu3PYxYQmR1BbCM7M67VzWLD1SLync%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67A40FAB1EDCAE34300E79DE</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"6AAE93347ED23A245026028A98AF919E"</PartEtag>
  <PartNumber>2</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-02-06 01:26:07 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/3rOUfin1%2F889478%2F67092e25ec129a93ff2e4bd3b912ea76bbb6d622%2F67a40f7419f19b2ff3d449b7a7bce945cbe6035f?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=3A9D570B3EB54087AE9BA5A1D45AB305&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738808708&x-oss-signature=Lx4BbedfY5q%2BsZu3PYxYQmR1BbCM7M67VzWLD1SLync%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67A40FACB6508C34378EDD82</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"6AAE93347ED23A245026028A98AF919E"</PartEtag>
  <PartNumber>2</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-02-06 01:26:07 - ERROR - aliyundrive.py - 1077 - File tmp/122547455/122547455_p17.png Part 2 upload failed.
2025-02-06 01:26:08 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-02-06 01:26:09 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-02-06 01:29:15 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /Kh2bcekI%2F889478%2F67092e431f8e6cc4f0304629ad29c6535862acc2%2F67a4104d86c14a90e8674c2a91d71534ac74e9f5?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=7FF92629E6A3467AA1234EFD4E075077&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738808925&x-oss-signature=XJ0Vn3pu7bUj4nBiJ%2B3W7AqGpu6EBcjzT4sGUu6wJDM%3D&x-oss-signature-version=OSS2
2025-02-06 01:33:39 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /HMCOcU89%2F889478%2F67a345383f19dca708194aa1b03d50259552d336%2F67a411555745e2f971b74400a43eb1a3abaccdf8?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=CFE846FBC0C84B9A9E5401591E369DB3&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738809189&x-oss-signature=yBnm%2FD%2Bbx5UBKuZuz9Zg%2FKcfLP0FyaVECiXodXAKAuc%3D&x-oss-signature-version=OSS2
2025-02-06 01:35:03 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /O5Ywey7f%2F889478%2F65d08c52a11652a4adff464d95e517b0111b7aaf%2F67a411a97fbace0fb3c940448680ff2967019518?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=0B2F04A1AB7B434893D8BE9EADB410C2&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738809273&x-oss-signature=ZZe3z%2FNgrtPRbYkIxXYVcMLEYqP1Kl8%2BoAS7hIrDMzg%3D&x-oss-signature-version=OSS2
2025-02-06 01:37:10 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /k9r43j2T%2F889478%2F677e0d45502dcdf21beb41eebfd0afe03c98f6bc%2F67a412282302d4416a2846eaaff43f85bcd6f73c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=3B4919A8ADF14F5DBFC8B87E4E5DE6CE&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738809400&x-oss-signature=239ZaC8c0ynhUJCES%2BBqb%2BZ2jier7xsXjJqv2Nq%2Bhj4%3D&x-oss-signature-version=OSS2
2025-02-06 01:37:37 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/k9r43j2T%2F889478%2F677e0d45502dcdf21beb41eebfd0afe03c98f6bc%2F67a412282302d4416a2846eaaff43f85bcd6f73c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=3B4919A8ADF14F5DBFC8B87E4E5DE6CE&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738809400&x-oss-signature=239ZaC8c0ynhUJCES%2BBqb%2BZ2jier7xsXjJqv2Nq%2Bhj4%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67A412477C050B30399E3795</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"59F08B49F675AA36335AB605F5BF67CE"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-02-06 01:37:44 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/k9r43j2T%2F889478%2F677e0d45502dcdf21beb41eebfd0afe03c98f6bc%2F67a412282302d4416a2846eaaff43f85bcd6f73c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=3B4919A8ADF14F5DBFC8B87E4E5DE6CE&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738809400&x-oss-signature=239ZaC8c0ynhUJCES%2BBqb%2BZ2jier7xsXjJqv2Nq%2Bhj4%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67A412627C050B3039037295</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"59F08B49F675AA36335AB605F5BF67CE"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-02-06 01:37:48 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/k9r43j2T%2F889478%2F677e0d45502dcdf21beb41eebfd0afe03c98f6bc%2F67a412282302d4416a2846eaaff43f85bcd6f73c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=3B4919A8ADF14F5DBFC8B87E4E5DE6CE&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738809400&x-oss-signature=239ZaC8c0ynhUJCES%2BBqb%2BZ2jier7xsXjJqv2Nq%2Bhj4%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67A4126873F4E531336581D6</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"59F08B49F675AA36335AB605F5BF67CE"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-02-06 01:37:48 - ERROR - aliyundrive.py - 1077 - File tmp/125978453/125978453_p0.jpg Part 1 upload failed.
2025-02-06 01:38:25 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /zD1jlnRy%2F889478%2F6752357cfda83d742715407b8c3029245c9d6dcb%2F67a412737fe45852cd7947ffa3618147eff1f3c5?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=F448D187E4184251B282771421B83387&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738809475&x-oss-signature=mo%2FpCc%2FM0bzb69HCgRecvZGhI%2FvTJqPEiUf%2Bqht84FY%3D&x-oss-signature-version=OSS2
2025-02-06 01:40:49 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /6RJpc9CB%2F889478%2F671678a72b1a7621e25441168d434b2b4131ee09%2F67a4130208261dfb194d47d6aceda4203e7d198e?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=2EAD15395EBF44C4B89C5C3C88258AD3&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738809618&x-oss-signature=rC95zICqRka0KzFdharkUQuTZKoFMfu0qmMvzoLQ6OI%3D&x-oss-signature-version=OSS2
2025-02-06 01:41:20 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /6RJpc9CB%2F889478%2F671678a72b1a7621e25441168d434b2b4131ee09%2F67a4130208261dfb194d47d6aceda4203e7d198e?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bTOPSMu4pr1busVET0iVYQdulPu7Pfpzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUicFX3xq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7HW4Ql77uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSixR4Z3%2FXtuMkagAE2qxWTmWkvCNIFnOco5h8hTsO26%2BqDiCrfQ2thJ6fY9I0DOaEGD9e7pqd9WrTCqD7B1GntIDtpbjRC%2BVvwV1vTsrbABoJ6md2PsaoHeIEUo2hIAI4Y2V2vmri9nfVwaZrFP6gNfxOR4glIqjhBUyB%2Fz77tq1prMTD63D3r%2Fb%2F4qyAA&uploadId=2EAD15395EBF44C4B89C5C3C88258AD3&x-oss-access-key-id=STS.NUfsN8VUJbyGVbEmVEzfcTvtE&x-oss-expires=1738809618&x-oss-signature=rC95zICqRka0KzFdharkUQuTZKoFMfu0qmMvzoLQ6OI%3D&x-oss-signature-version=OSS2
