2023-06-15 22:14:28 - WARNING - aliyundrive.py - 820 - Token is about to expire, try to auto refresh.
2023-06-15 22:31:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-15 22:31:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-06-15 22:48:40 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/06/03/14/31/22/108683773_p0.jpg
2023-06-15 22:52:09 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/12/23/00/00/19/103816502_p0.jpg
2023-06-16 10:16:28 - WARNING - aliyundrive.py - 820 - Token is about to expire, try to auto refresh.
2023-06-16 10:27:14 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-16 10:27:15 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-06-16 10:27:45 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-16 10:27:47 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-06-16 10:28:17 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-16 10:28:20 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-06-16 10:28:51 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-16 10:28:55 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-06-16 10:28:55 - ERROR - aliyundrive.py - 1034 - Failed to get create info of file tmp/98726093/98726093.json.txt.
2023-06-16 10:29:27 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-16 10:29:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-06-16 10:49:30 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/03/11/17/33/54/106114864_p0.jpg
2023-06-16 11:09:34 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /ajax/illust/106058359
2023-06-16 11:38:44 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/04/29/00/00/12/97947478_p0.png
2023-06-16 11:46:28 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/107454934/107454934_ugoira0.gif, upload original page.
2023-06-16 11:46:28 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/107454934/107454934_ugoira0.gif.
2023-06-16 11:56:29 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/02/18/14/19/11/105430019_p0.png
2023-06-16 12:15:30 - WARNING - aliyundrive.py - 820 - Token is about to expire, try to auto refresh.
2023-06-16 22:14:16 - WARNING - aliyundrive.py - 820 - Token is about to expire, try to auto refresh.
2023-06-16 22:20:56 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/01/21/00/00/06/104675991_p0.png
2023-06-16 22:34:37 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-16 22:34:38 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-06-16 22:40:02 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/06/12/20/59/20/108958356_p0.png
2023-06-16 23:05:19 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/05/29/23/58/45/108557574_p0.png
2023-06-16 23:16:29 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-16 23:16:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-06-16 23:34:29 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/02/26/00/51/52/105711534_p0.jpg
2023-06-16 23:37:35 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/05/29/13/01/45/108541730_p0.jpg
2023-06-16 23:40:50 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/107454934/107454934_ugoira0.gif, upload original page.
2023-06-16 23:40:50 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/107454934/107454934_ugoira0.gif.
2023-06-17 00:03:33 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/04/16/10/35/06/107221625_p0.jpg
2023-06-17 10:15:19 - WARNING - aliyundrive.py - 820 - Token is about to expire, try to auto refresh.
2023-06-17 10:50:43 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 10:50:44 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-06-17 10:51:15 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 10:51:17 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-06-17 10:51:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 10:51:50 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-06-17 10:52:20 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 10:52:24 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-06-17 10:52:24 - ERROR - aliyundrive.py - 1034 - Failed to get create info of file tmp/102006529/102006529.json.txt.
2023-06-17 10:52:56 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 10:52:57 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-06-17 11:01:33 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/108150135/108150135_ugoira0.gif, upload original page.
2023-06-17 11:01:34 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/108150135/108150135_ugoira0.gif.
2023-06-17 11:21:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 11:21:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-06-17 11:22:18 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 11:22:20 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-06-17 11:22:50 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 11:22:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-06-17 11:23:24 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 11:23:28 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-06-17 11:23:28 - ERROR - aliyundrive.py - 1034 - Failed to get create info of file tmp/94970370/94970370_p0.png.
2023-06-17 11:23:58 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 11:23:59 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-06-17 11:24:29 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 11:24:31 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-06-17 11:41:49 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /ajax/illust/104568886/pages
2023-06-17 11:46:51 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 11:46:52 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-06-17 11:47:22 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 11:47:24 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-06-17 11:47:54 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 11:47:57 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-06-17 11:48:27 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 11:48:31 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-06-17 11:48:31 - ERROR - aliyundrive.py - 1034 - Failed to get create info of file tmp/103278518/103278518_p1.png.
2023-06-17 11:49:02 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 11:49:03 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-06-17 11:59:17 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 11:59:18 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-06-17 11:59:48 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 11:59:50 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-06-17 12:00:21 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 12:00:24 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-06-17 12:00:54 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 12:00:58 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-06-17 12:00:58 - ERROR - aliyundrive.py - 1034 - Failed to get create info of file tmp/106525134/106525134.json.txt.
2023-06-17 12:01:29 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 12:01:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-06-17 12:03:38 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 12:03:39 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-06-17 12:04:09 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 12:04:11 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-06-17 12:04:41 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-06-17 12:04:44 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-06-17 12:06:48 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/06/17/10/19/24/109082075_p0.jpg
2023-06-17 12:07:03 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/10/23/00/31/41/102152635_p0.jpg
2023-06-17 12:14:19 - WARNING - aliyundrive.py - 820 - Token is about to expire, try to auto refresh.
