2023-12-25 14:22:55 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /Qtcx9td4%2F889478%2F65898fd94e8a16ba8786431ea1b2adb3b02dee3b%2F65898fd9f13f42f4a8d440a89bb5a04c4ac794d5?partNumber=2&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5bAJO%2F%2Fub0Z%2F4yoUhLS00g%2FRL1KgKLJtzz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNR2nVz%2F1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABLtUNjGbCvqj24LHg3XoOYSxm6X05GUYIyjmCBMnK%2BG5dfcC5tUeSksNtJLcre12zjN%2Bhw%2F6uhhq04PUorUSigFUG7T2QaCuGfOb9QgiKUjsv%2Ff%2BQBkwp8ltGMG3cRGTd1vWoueUlSsHTPjQUzlSc%2Bk%2B3U2fvrWvchbMifuVS6KkgAA%3D%3D&uploadId=2E8D9A015288479B86D2205FA901D64C&x-oss-access-key-id=STS.NUuoUKTb8HNCP4c7HjH2fogbU&x-oss-expires=1703517673&x-oss-signature=VcToptIVulemBktS9kHfN5kG6AetH3IUaGEZpTqT2xA%3D&x-oss-signature-version=OSS2
2023-12-25 14:31:15 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /ZVKjhUP4%2F889478%2F6563c353bc9bcff6781b4d409f31a0e0636fe81a%2F6589921586a5eb42afb44a79ba45aaf7561d5491?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5bmGuPdvOdn8YXab0vVtW0lW%2F10jITlhjz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNQuRWD%2F1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABZ%2FFLz%2B3a7q44W8fniO3879hiZmG92G9OYmYPnb9WI2ENcEmb655agaSpwe48GAaVKb6gE2nj%2FiRkMtK84As0M5kJBcul4t%2FSk4zx0NQgV%2FWjhkRHc9Uqbf71t8kKtOX%2BL5yqOnvhnFn4Wu3E94mM4HDh4CmPzdoWNHop%2FH%2BADC0gAA%3D%3D&uploadId=E32DB4587B5F47908706B526E1F8CEB5&x-oss-access-key-id=STS.NUSQYiQ8FFG1mmdQmpWrXcANd&x-oss-expires=1703518245&x-oss-signature=Y1bOYXNzMXN27tG6ne3ZOk2xlcIVpWqSIFCZzKUHU8g%3D&x-oss-signature-version=OSS2
2023-12-25 14:31:46 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /ZVKjhUP4%2F889478%2F6563c353bc9bcff6781b4d409f31a0e0636fe81a%2F6589921586a5eb42afb44a79ba45aaf7561d5491?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5bmGuPdvOdn8YXab0vVtW0lW%2F10jITlhjz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNQuRWD%2F1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABZ%2FFLz%2B3a7q44W8fniO3879hiZmG92G9OYmYPnb9WI2ENcEmb655agaSpwe48GAaVKb6gE2nj%2FiRkMtK84As0M5kJBcul4t%2FSk4zx0NQgV%2FWjhkRHc9Uqbf71t8kKtOX%2BL5yqOnvhnFn4Wu3E94mM4HDh4CmPzdoWNHop%2FH%2BADC0gAA%3D%3D&uploadId=E32DB4587B5F47908706B526E1F8CEB5&x-oss-access-key-id=STS.NUSQYiQ8FFG1mmdQmpWrXcANd&x-oss-expires=1703518245&x-oss-signature=Y1bOYXNzMXN27tG6ne3ZOk2xlcIVpWqSIFCZzKUHU8g%3D&x-oss-signature-version=OSS2
2023-12-25 14:32:17 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /ZVKjhUP4%2F889478%2F6563c353bc9bcff6781b4d409f31a0e0636fe81a%2F6589921586a5eb42afb44a79ba45aaf7561d5491?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5bmGuPdvOdn8YXab0vVtW0lW%2F10jITlhjz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNQuRWD%2F1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABZ%2FFLz%2B3a7q44W8fniO3879hiZmG92G9OYmYPnb9WI2ENcEmb655agaSpwe48GAaVKb6gE2nj%2FiRkMtK84As0M5kJBcul4t%2FSk4zx0NQgV%2FWjhkRHc9Uqbf71t8kKtOX%2BL5yqOnvhnFn4Wu3E94mM4HDh4CmPzdoWNHop%2FH%2BADC0gAA%3D%3D&uploadId=E32DB4587B5F47908706B526E1F8CEB5&x-oss-access-key-id=STS.NUSQYiQ8FFG1mmdQmpWrXcANd&x-oss-expires=1703518245&x-oss-signature=Y1bOYXNzMXN27tG6ne3ZOk2xlcIVpWqSIFCZzKUHU8g%3D&x-oss-signature-version=OSS2
2023-12-25 14:39:13 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /TmYijPe7%2F889478%2F657ae9af9d10fcb07f404a22923a88128561d81f%2F658993f3bc8c5c2c92664127a7e5d2f6bd2e9c4d?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5b2OfnM3LRZ8KyySGPJsjMHful%2BhZbssTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNVS4UD%2F1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABagknJgI4i4anGwp51xWfL51TabJP3Vtt1z34iGTkTWpEmXshOK%2BEn%2B%2BtuoBWAW%2B6qgQxi8IA8K1Scw4yBMNZL3Lnpi32w95Lw7PtrEbZbtyB%2FpW2RyOuQNg6kY0SF6Ex48S51SmFdqNi1jAron%2FhDfXMaIEfrgMk05KYweKup7AgAA%3D%3D&uploadId=1465AE9591034C788B277A48BA280095&x-oss-access-key-id=STS.NUCrCx1kxGnYJExV3RrfRjSGS&x-oss-expires=1703518723&x-oss-signature=F6kizUk6enP9mrnRVMzz7SwQE6E7ImrWDJr12yNHYZ8%3D&x-oss-signature-version=OSS2
2023-12-25 14:39:49 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/TmYijPe7%2F889478%2F657ae9af9d10fcb07f404a22923a88128561d81f%2F658993f3bc8c5c2c92664127a7e5d2f6bd2e9c4d?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5b2OfnM3LRZ8KyySGPJsjMHful%2BhZbssTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNVS4UD%2F1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABagknJgI4i4anGwp51xWfL51TabJP3Vtt1z34iGTkTWpEmXshOK%2BEn%2B%2BtuoBWAW%2B6qgQxi8IA8K1Scw4yBMNZL3Lnpi32w95Lw7PtrEbZbtyB%2FpW2RyOuQNg6kY0SF6Ex48S51SmFdqNi1jAron%2FhDfXMaIEfrgMk05KYweKup7AgAA%3D%3D&uploadId=1465AE9591034C788B277A48BA280095&x-oss-access-key-id=STS.NUCrCx1kxGnYJExV3RrfRjSGS&x-oss-expires=1703518723&x-oss-signature=F6kizUk6enP9mrnRVMzz7SwQE6E7ImrWDJr12yNHYZ8%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>6589941321BA9B3038F02CF4</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"B3C21B0E296B06A8DB004FC57C8E0D73"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-25 14:40:19 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /TmYijPe7%2F889478%2F657ae9af9d10fcb07f404a22923a88128561d81f%2F658993f3bc8c5c2c92664127a7e5d2f6bd2e9c4d?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5b2OfnM3LRZ8KyySGPJsjMHful%2BhZbssTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNVS4UD%2F1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABagknJgI4i4anGwp51xWfL51TabJP3Vtt1z34iGTkTWpEmXshOK%2BEn%2B%2BtuoBWAW%2B6qgQxi8IA8K1Scw4yBMNZL3Lnpi32w95Lw7PtrEbZbtyB%2FpW2RyOuQNg6kY0SF6Ex48S51SmFdqNi1jAron%2FhDfXMaIEfrgMk05KYweKup7AgAA%3D%3D&uploadId=1465AE9591034C788B277A48BA280095&x-oss-access-key-id=STS.NUCrCx1kxGnYJExV3RrfRjSGS&x-oss-expires=1703518723&x-oss-signature=F6kizUk6enP9mrnRVMzz7SwQE6E7ImrWDJr12yNHYZ8%3D&x-oss-signature-version=OSS2
2023-12-25 14:40:28 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/TmYijPe7%2F889478%2F657ae9af9d10fcb07f404a22923a88128561d81f%2F658993f3bc8c5c2c92664127a7e5d2f6bd2e9c4d?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5b2OfnM3LRZ8KyySGPJsjMHful%2BhZbssTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNVS4UD%2F1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABagknJgI4i4anGwp51xWfL51TabJP3Vtt1z34iGTkTWpEmXshOK%2BEn%2B%2BtuoBWAW%2B6qgQxi8IA8K1Scw4yBMNZL3Lnpi32w95Lw7PtrEbZbtyB%2FpW2RyOuQNg6kY0SF6Ex48S51SmFdqNi1jAron%2FhDfXMaIEfrgMk05KYweKup7AgAA%3D%3D&uploadId=1465AE9591034C788B277A48BA280095&x-oss-access-key-id=STS.NUCrCx1kxGnYJExV3RrfRjSGS&x-oss-expires=1703518723&x-oss-signature=F6kizUk6enP9mrnRVMzz7SwQE6E7ImrWDJr12yNHYZ8%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>65899454C59AB23035CF8D6A</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"B3C21B0E296B06A8DB004FC57C8E0D73"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-25 14:40:52 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/TmYijPe7%2F889478%2F657ae9af9d10fcb07f404a22923a88128561d81f%2F658993f3bc8c5c2c92664127a7e5d2f6bd2e9c4d?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5b2OfnM3LRZ8KyySGPJsjMHful%2BhZbssTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNVS4UD%2F1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABagknJgI4i4anGwp51xWfL51TabJP3Vtt1z34iGTkTWpEmXshOK%2BEn%2B%2BtuoBWAW%2B6qgQxi8IA8K1Scw4yBMNZL3Lnpi32w95Lw7PtrEbZbtyB%2FpW2RyOuQNg6kY0SF6Ex48S51SmFdqNi1jAron%2FhDfXMaIEfrgMk05KYweKup7AgAA%3D%3D&uploadId=1465AE9591034C788B277A48BA280095&x-oss-access-key-id=STS.NUCrCx1kxGnYJExV3RrfRjSGS&x-oss-expires=1703518723&x-oss-signature=F6kizUk6enP9mrnRVMzz7SwQE6E7ImrWDJr12yNHYZ8%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>6589945CC59AB23035AF956A</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"B3C21B0E296B06A8DB004FC57C8E0D73"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-25 14:40:52 - ERROR - aliyundrive.py - 1077 - File tmp/110401574/110401574_p3.jpg Part 1 upload failed.
2023-12-25 14:42:33 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /MTOkJENH%2F889478%2F657ae9b513da612644a4486bb5b5bf905682c693%2F658994af688dec10a9d94d2096876ac77e2113e8?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5DeOO%2F3g49S5bSydVKAnTI0QOJ%2FrPKfsTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNWvTHTj1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABM9N40xKBj6wzBSdrSDMkx%2BxCprU%2FlqTpPikD%2B7nB6WHYHiUoekZlyNFynFZkSRpZi9J7KvKOx0a0VrgV9zZ4tuwqNE28SYZlZs%2BiX7AsaFx6NaNWuOyfYdQ2HEgxIsEeXV%2BPh9z1HhSLii6Pd%2FftntVgH9gitDJVv8EbX1f%2BxW8gAA%3D%3D&uploadId=D268E96173E341D290378CA14838DE8C&x-oss-access-key-id=STS.NSksUCnPsRvYwt1y2aLmSC74S&x-oss-expires=1703518911&x-oss-signature=ntyj3%2FCZrFlZ%2BhegV0QmfYBOFm%2FJL7qZZt2W6hNWa%2F0%3D&x-oss-signature-version=OSS2
2023-12-25 14:42:59 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/MTOkJENH%2F889478%2F657ae9b513da612644a4486bb5b5bf905682c693%2F658994af688dec10a9d94d2096876ac77e2113e8?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5DeOO%2F3g49S5bSydVKAnTI0QOJ%2FrPKfsTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNWvTHTj1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABM9N40xKBj6wzBSdrSDMkx%2BxCprU%2FlqTpPikD%2B7nB6WHYHiUoekZlyNFynFZkSRpZi9J7KvKOx0a0VrgV9zZ4tuwqNE28SYZlZs%2BiX7AsaFx6NaNWuOyfYdQ2HEgxIsEeXV%2BPh9z1HhSLii6Pd%2FftntVgH9gitDJVv8EbX1f%2BxW8gAA%3D%3D&uploadId=D268E96173E341D290378CA14838DE8C&x-oss-access-key-id=STS.NSksUCnPsRvYwt1y2aLmSC74S&x-oss-expires=1703518911&x-oss-signature=ntyj3%2FCZrFlZ%2BhegV0QmfYBOFm%2FJL7qZZt2W6hNWa%2F0%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>658994DAF8DE4330380F301C</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"A43C8FB54792E9B8C465EC9FE9BE8C07"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-25 14:43:20 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/MTOkJENH%2F889478%2F657ae9b513da612644a4486bb5b5bf905682c693%2F658994af688dec10a9d94d2096876ac77e2113e8?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5DeOO%2F3g49S5bSydVKAnTI0QOJ%2FrPKfsTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNWvTHTj1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABM9N40xKBj6wzBSdrSDMkx%2BxCprU%2FlqTpPikD%2B7nB6WHYHiUoekZlyNFynFZkSRpZi9J7KvKOx0a0VrgV9zZ4tuwqNE28SYZlZs%2BiX7AsaFx6NaNWuOyfYdQ2HEgxIsEeXV%2BPh9z1HhSLii6Pd%2FftntVgH9gitDJVv8EbX1f%2BxW8gAA%3D%3D&uploadId=D268E96173E341D290378CA14838DE8C&x-oss-access-key-id=STS.NSksUCnPsRvYwt1y2aLmSC74S&x-oss-expires=1703518911&x-oss-signature=ntyj3%2FCZrFlZ%2BhegV0QmfYBOFm%2FJL7qZZt2W6hNWa%2F0%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>658994F3F8DE433038BF461C</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"A43C8FB54792E9B8C465EC9FE9BE8C07"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-25 14:43:52 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/MTOkJENH%2F889478%2F657ae9b513da612644a4486bb5b5bf905682c693%2F658994af688dec10a9d94d2096876ac77e2113e8?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5DeOO%2F3g49S5bSydVKAnTI0QOJ%2FrPKfsTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNWvTHTj1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABM9N40xKBj6wzBSdrSDMkx%2BxCprU%2FlqTpPikD%2B7nB6WHYHiUoekZlyNFynFZkSRpZi9J7KvKOx0a0VrgV9zZ4tuwqNE28SYZlZs%2BiX7AsaFx6NaNWuOyfYdQ2HEgxIsEeXV%2BPh9z1HhSLii6Pd%2FftntVgH9gitDJVv8EbX1f%2BxW8gAA%3D%3D&uploadId=D268E96173E341D290378CA14838DE8C&x-oss-access-key-id=STS.NSksUCnPsRvYwt1y2aLmSC74S&x-oss-expires=1703518911&x-oss-signature=ntyj3%2FCZrFlZ%2BhegV0QmfYBOFm%2FJL7qZZt2W6hNWa%2F0%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>65899508F8DE4330380C571C</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"A43C8FB54792E9B8C465EC9FE9BE8C07"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-25 14:43:52 - ERROR - aliyundrive.py - 1077 - File tmp/110401574/110401574_p6.jpg Part 1 upload failed.
2023-12-25 14:45:15 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /wZEwR0Se%2F889478%2F657ae9bbb1bc1166bbec47f4b805f32035e47bb6%2F6589955d18bc3ab2c250444e82eeb45094a09df0?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5bbA9Hmg5FD0qaganzCoHI4e8lKp7SZ0zz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNU%2FPMj%2F1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABJU%2BMc15kx4uUUGe3M8ZtxNS7MdEj56ElLM0PaHTSAZ7Z4LaqGjZPTn%2BpJ1z1yHTjnoS5tgm7RebnbcVwZUDKvwqyytp9N8zSLN7L5zC3Y7NM%2BzyorjTurZ6E9HON1BmAT5%2BtbVBjyPqWjpznbvGpt2bm3gPfehFX6JhLweeVFacgAA%3D%3D&uploadId=87722CAFB9384FA4A1896D2AB62EA220&x-oss-access-key-id=STS.NUnHkRnNbedKhZsDrmwFfHq21&x-oss-expires=1703519085&x-oss-signature=%2BrlsC9PASDjgcFkNr9hf6IHWhp%2Btmco4Wlf2lde7dSU%3D&x-oss-signature-version=OSS2
2023-12-25 14:45:37 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/wZEwR0Se%2F889478%2F657ae9bbb1bc1166bbec47f4b805f32035e47bb6%2F6589955d18bc3ab2c250444e82eeb45094a09df0?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5bbA9Hmg5FD0qaganzCoHI4e8lKp7SZ0zz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNU%2FPMj%2F1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABJU%2BMc15kx4uUUGe3M8ZtxNS7MdEj56ElLM0PaHTSAZ7Z4LaqGjZPTn%2BpJ1z1yHTjnoS5tgm7RebnbcVwZUDKvwqyytp9N8zSLN7L5zC3Y7NM%2BzyorjTurZ6E9HON1BmAT5%2BtbVBjyPqWjpznbvGpt2bm3gPfehFX6JhLweeVFacgAA%3D%3D&uploadId=87722CAFB9384FA4A1896D2AB62EA220&x-oss-access-key-id=STS.NUnHkRnNbedKhZsDrmwFfHq21&x-oss-expires=1703519085&x-oss-signature=%2BrlsC9PASDjgcFkNr9hf6IHWhp%2Btmco4Wlf2lde7dSU%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>6589957D78E74A3331BF54C5</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"C9487EC66CEC46487DF65A7D11A81396"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-25 14:45:43 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/wZEwR0Se%2F889478%2F657ae9bbb1bc1166bbec47f4b805f32035e47bb6%2F6589955d18bc3ab2c250444e82eeb45094a09df0?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5bbA9Hmg5FD0qaganzCoHI4e8lKp7SZ0zz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNU%2FPMj%2F1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABJU%2BMc15kx4uUUGe3M8ZtxNS7MdEj56ElLM0PaHTSAZ7Z4LaqGjZPTn%2BpJ1z1yHTjnoS5tgm7RebnbcVwZUDKvwqyytp9N8zSLN7L5zC3Y7NM%2BzyorjTurZ6E9HON1BmAT5%2BtbVBjyPqWjpznbvGpt2bm3gPfehFX6JhLweeVFacgAA%3D%3D&uploadId=87722CAFB9384FA4A1896D2AB62EA220&x-oss-access-key-id=STS.NUnHkRnNbedKhZsDrmwFfHq21&x-oss-expires=1703519085&x-oss-signature=%2BrlsC9PASDjgcFkNr9hf6IHWhp%2Btmco4Wlf2lde7dSU%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>6589959178E74A3331E266C5</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"C9487EC66CEC46487DF65A7D11A81396"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-25 14:46:11 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/wZEwR0Se%2F889478%2F657ae9bbb1bc1166bbec47f4b805f32035e47bb6%2F6589955d18bc3ab2c250444e82eeb45094a09df0?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5bbA9Hmg5FD0qaganzCoHI4e8lKp7SZ0zz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNU%2FPMj%2F1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABJU%2BMc15kx4uUUGe3M8ZtxNS7MdEj56ElLM0PaHTSAZ7Z4LaqGjZPTn%2BpJ1z1yHTjnoS5tgm7RebnbcVwZUDKvwqyytp9N8zSLN7L5zC3Y7NM%2BzyorjTurZ6E9HON1BmAT5%2BtbVBjyPqWjpznbvGpt2bm3gPfehFX6JhLweeVFacgAA%3D%3D&uploadId=87722CAFB9384FA4A1896D2AB62EA220&x-oss-access-key-id=STS.NUnHkRnNbedKhZsDrmwFfHq21&x-oss-expires=1703519085&x-oss-signature=%2BrlsC9PASDjgcFkNr9hf6IHWhp%2Btmco4Wlf2lde7dSU%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>6589959878E74A3331D36BC5</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"C9487EC66CEC46487DF65A7D11A81396"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-25 14:46:11 - ERROR - aliyundrive.py - 1077 - File tmp/110401574_mirage/110401574_p0.png Part 1 upload failed.
2023-12-25 14:50:20 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/02/00/00/17/113872017_p0.png
2023-12-25 14:50:31 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/04/05/00/00/02/106871841_p0.jpg
2023-12-25 14:57:30 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /slPHkrvz%2F889478%2F64e9e2bfb3867c0fc33046d0a9f92119f975b809%2F6589983cf24883267ac34eabaa0adc0487f06162?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fSPoL52Kp205KnMHb1o1EgeuZvl6HelDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNW%2FXZT%2F1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABgoY7R5bDh01M9E1wcaWEEa0UQEjwz14LVdjlVYs91uYZkjaGjzJ6WbO3hKry0iPn3ivPS%2BP7A3cY0mntUhAOuadFrOCp2wLUQb8OFqPUuF0eVazLiBofsxf8PF0BaDpg3Bf%2FKBeP6wP8ty4WcXSoHuE9nZoH%2FA1AQE7cc63UUT8gAA%3D%3D&uploadId=416761FB30A54083A4F6080A86F80DCF&x-oss-access-key-id=STS.NTgu8M5uWdPL2PDGQuviCxduv&x-oss-expires=1703519820&x-oss-signature=%2F8AQXIgMX3BuOSOLcuBtCRFE55qYb1uKLhQ7DEoVqFU%3D&x-oss-signature-version=OSS2
2023-12-25 15:05:50 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/11/25/00/00/04/113680860_p0.jpg
2023-12-25 15:16:45 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-25 15:16:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-25 15:26:21 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /TkbSb10B%2F889478%2F651576bf641e3b26b6b64c9e8df3898235124734%2F65899effbf332c06acdd4a7e8205a1b44dcbad73?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fRE%2FuAmIlDxoWbUWCCpmoySudijpWZiTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNRzWBjj1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABKwag4YK3jZUFHHvvtop4WkU00Lo%2F4KzhYUQuKPUbKwLlPqHc34tP9r8Wx8BMNue26rqO5vjI8e7eSTbrf5uVKnT9roExUs8q%2B8TyW%2BR0YKAzU%2BnzPsQk5d1NGWWRiJkHHSAzxviwYtyKj3VNbGVocVDaTsatczBjorOKQouOZzMgAA%3D%3D&uploadId=ED65D0BBB04E4B0BBBA55D10BEEC600A&x-oss-access-key-id=STS.NTdXA4uVbqGpSF3BjgFhNaP2k&x-oss-expires=1703521551&x-oss-signature=C%2Fz6%2BFOzYQ7dG7K7%2Bu7%2FO2fLPn6Z5UiGAbpwQeQAC3Q%3D&x-oss-signature-version=OSS2
2023-12-25 15:26:43 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/TkbSb10B%2F889478%2F651576bf641e3b26b6b64c9e8df3898235124734%2F65899effbf332c06acdd4a7e8205a1b44dcbad73?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fRE%2FuAmIlDxoWbUWCCpmoySudijpWZiTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNRzWBjj1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABKwag4YK3jZUFHHvvtop4WkU00Lo%2F4KzhYUQuKPUbKwLlPqHc34tP9r8Wx8BMNue26rqO5vjI8e7eSTbrf5uVKnT9roExUs8q%2B8TyW%2BR0YKAzU%2BnzPsQk5d1NGWWRiJkHHSAzxviwYtyKj3VNbGVocVDaTsatczBjorOKQouOZzMgAA%3D%3D&uploadId=ED65D0BBB04E4B0BBBA55D10BEEC600A&x-oss-access-key-id=STS.NTdXA4uVbqGpSF3BjgFhNaP2k&x-oss-expires=1703521551&x-oss-signature=C%2Fz6%2BFOzYQ7dG7K7%2Bu7%2FO2fLPn6Z5UiGAbpwQeQAC3Q%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>65899F1EE1532C3738D2DDF2</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"261CF9D117D1B7D4E3167B7E3C9F3DCC"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-25 15:27:05 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/TkbSb10B%2F889478%2F651576bf641e3b26b6b64c9e8df3898235124734%2F65899effbf332c06acdd4a7e8205a1b44dcbad73?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fRE%2FuAmIlDxoWbUWCCpmoySudijpWZiTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNRzWBjj1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABKwag4YK3jZUFHHvvtop4WkU00Lo%2F4KzhYUQuKPUbKwLlPqHc34tP9r8Wx8BMNue26rqO5vjI8e7eSTbrf5uVKnT9roExUs8q%2B8TyW%2BR0YKAzU%2BnzPsQk5d1NGWWRiJkHHSAzxviwYtyKj3VNbGVocVDaTsatczBjorOKQouOZzMgAA%3D%3D&uploadId=ED65D0BBB04E4B0BBBA55D10BEEC600A&x-oss-access-key-id=STS.NTdXA4uVbqGpSF3BjgFhNaP2k&x-oss-expires=1703521551&x-oss-signature=C%2Fz6%2BFOzYQ7dG7K7%2Bu7%2FO2fLPn6Z5UiGAbpwQeQAC3Q%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>65899F33E1532C373854EEF2</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"261CF9D117D1B7D4E3167B7E3C9F3DCC"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-25 15:27:27 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/TkbSb10B%2F889478%2F651576bf641e3b26b6b64c9e8df3898235124734%2F65899effbf332c06acdd4a7e8205a1b44dcbad73?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fRE%2FuAmIlDxoWbUWCCpmoySudijpWZiTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNRzWBjj1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABKwag4YK3jZUFHHvvtop4WkU00Lo%2F4KzhYUQuKPUbKwLlPqHc34tP9r8Wx8BMNue26rqO5vjI8e7eSTbrf5uVKnT9roExUs8q%2B8TyW%2BR0YKAzU%2BnzPsQk5d1NGWWRiJkHHSAzxviwYtyKj3VNbGVocVDaTsatczBjorOKQouOZzMgAA%3D%3D&uploadId=ED65D0BBB04E4B0BBBA55D10BEEC600A&x-oss-access-key-id=STS.NTdXA4uVbqGpSF3BjgFhNaP2k&x-oss-expires=1703521551&x-oss-signature=C%2Fz6%2BFOzYQ7dG7K7%2Bu7%2FO2fLPn6Z5UiGAbpwQeQAC3Q%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>65899F49E1532C3738A000F3</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"261CF9D117D1B7D4E3167B7E3C9F3DCC"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-25 15:27:27 - ERROR - aliyundrive.py - 1077 - File tmp/111563794_mirage/111563794_p0.png Part 1 upload failed.
2023-12-25 15:28:03 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /sSR1NRX6%2F889478%2F64c4fa09b85f8656ce2e4a7da4f2da5f339d05ed%2F65899f65ed208570ef5347c193fa35283181c308?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fWEdOHqIlb84maOm3UlEg%2BOch%2F2%2F3apDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNXW3KTb1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABZOoBKGdoLmPdCEmVUrDvpC2yGLqXrp%2FnJxoFWSOU6byw9r4Lv21oC2KcVkt8pBZ6rgLBrsPeA%2FEDYJCdmXH1QrZPaRT9pT34OJRmzlKXdBGS%2B5YVl8OSNnMXpJOhKCpjDc0r4wYZzt2xuSiQxDPnpYJo%2FKiEmUY6rwBogHra3a0gAA%3D%3D&uploadId=1442CC9FCB0F46E0BB9255962BB4470B&x-oss-access-key-id=STS.NTcZi3EVzDKq8KepHk5GS48qF&x-oss-expires=1703521653&x-oss-signature=yNfB2fHwwzqMLNhsI2rQNeIk2zhtqjM0uOTreRmADKg%3D&x-oss-signature-version=OSS2
2023-12-25 15:28:34 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /sSR1NRX6%2F889478%2F64c4fa09b85f8656ce2e4a7da4f2da5f339d05ed%2F65899f65ed208570ef5347c193fa35283181c308?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fWEdOHqIlb84maOm3UlEg%2BOch%2F2%2F3apDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNXW3KTb1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABZOoBKGdoLmPdCEmVUrDvpC2yGLqXrp%2FnJxoFWSOU6byw9r4Lv21oC2KcVkt8pBZ6rgLBrsPeA%2FEDYJCdmXH1QrZPaRT9pT34OJRmzlKXdBGS%2B5YVl8OSNnMXpJOhKCpjDc0r4wYZzt2xuSiQxDPnpYJo%2FKiEmUY6rwBogHra3a0gAA%3D%3D&uploadId=1442CC9FCB0F46E0BB9255962BB4470B&x-oss-access-key-id=STS.NTcZi3EVzDKq8KepHk5GS48qF&x-oss-expires=1703521653&x-oss-signature=yNfB2fHwwzqMLNhsI2rQNeIk2zhtqjM0uOTreRmADKg%3D&x-oss-signature-version=OSS2
2023-12-25 15:29:05 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /sSR1NRX6%2F889478%2F64c4fa09b85f8656ce2e4a7da4f2da5f339d05ed%2F65899f65ed208570ef5347c193fa35283181c308?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fWEdOHqIlb84maOm3UlEg%2BOch%2F2%2F3apDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNXW3KTb1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABZOoBKGdoLmPdCEmVUrDvpC2yGLqXrp%2FnJxoFWSOU6byw9r4Lv21oC2KcVkt8pBZ6rgLBrsPeA%2FEDYJCdmXH1QrZPaRT9pT34OJRmzlKXdBGS%2B5YVl8OSNnMXpJOhKCpjDc0r4wYZzt2xuSiQxDPnpYJo%2FKiEmUY6rwBogHra3a0gAA%3D%3D&uploadId=1442CC9FCB0F46E0BB9255962BB4470B&x-oss-access-key-id=STS.NTcZi3EVzDKq8KepHk5GS48qF&x-oss-expires=1703521653&x-oss-signature=yNfB2fHwwzqMLNhsI2rQNeIk2zhtqjM0uOTreRmADKg%3D&x-oss-signature-version=OSS2
2023-12-25 15:29:36 - ERROR - base.py - 94 - https://cn-beijing-data.aliyundrive.net/sSR1NRX6%2F889478%2F64c4fa09b85f8656ce2e4a7da4f2da5f339d05ed%2F65899f65ed208570ef5347c193fa35283181c308?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fWEdOHqIlb84maOm3UlEg%2BOch%2F2%2F3apDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNXW3KTb1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABZOoBKGdoLmPdCEmVUrDvpC2yGLqXrp%2FnJxoFWSOU6byw9r4Lv21oC2KcVkt8pBZ6rgLBrsPeA%2FEDYJCdmXH1QrZPaRT9pT34OJRmzlKXdBGS%2B5YVl8OSNnMXpJOhKCpjDc0r4wYZzt2xuSiQxDPnpYJo%2FKiEmUY6rwBogHra3a0gAA%3D%3D&uploadId=1442CC9FCB0F46E0BB9255962BB4470B&x-oss-access-key-id=STS.NTcZi3EVzDKq8KepHk5GS48qF&x-oss-expires=1703521653&x-oss-signature=yNfB2fHwwzqMLNhsI2rQNeIk2zhtqjM0uOTreRmADKg%3D&x-oss-signature-version=OSS2:HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Max retries exceeded with url: /sSR1NRX6%2F889478%2F64c4fa09b85f8656ce2e4a7da4f2da5f339d05ed%2F65899f65ed208570ef5347c193fa35283181c308?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fWEdOHqIlb84maOm3UlEg%2BOch%2F2%2F3apDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNXW3KTb1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABZOoBKGdoLmPdCEmVUrDvpC2yGLqXrp%2FnJxoFWSOU6byw9r4Lv21oC2KcVkt8pBZ6rgLBrsPeA%2FEDYJCdmXH1QrZPaRT9pT34OJRmzlKXdBGS%2B5YVl8OSNnMXpJOhKCpjDc0r4wYZzt2xuSiQxDPnpYJo%2FKiEmUY6rwBogHra3a0gAA%3D%3D&uploadId=1442CC9FCB0F46E0BB9255962BB4470B&x-oss-access-key-id=STS.NTcZi3EVzDKq8KepHk5GS48qF&x-oss-expires=1703521653&x-oss-signature=yNfB2fHwwzqMLNhsI2rQNeIk2zhtqjM0uOTreRmADKg%3D&x-oss-signature-version=OSS2 (Caused by ProtocolError('Connection aborted.', timeout('The write operation timed out')))
2023-12-25 15:30:06 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /sSR1NRX6%2F889478%2F64c4fa09b85f8656ce2e4a7da4f2da5f339d05ed%2F65899f65ed208570ef5347c193fa35283181c308?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fWEdOHqIlb84maOm3UlEg%2BOch%2F2%2F3apDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNXW3KTb1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABZOoBKGdoLmPdCEmVUrDvpC2yGLqXrp%2FnJxoFWSOU6byw9r4Lv21oC2KcVkt8pBZ6rgLBrsPeA%2FEDYJCdmXH1QrZPaRT9pT34OJRmzlKXdBGS%2B5YVl8OSNnMXpJOhKCpjDc0r4wYZzt2xuSiQxDPnpYJo%2FKiEmUY6rwBogHra3a0gAA%3D%3D&uploadId=1442CC9FCB0F46E0BB9255962BB4470B&x-oss-access-key-id=STS.NTcZi3EVzDKq8KepHk5GS48qF&x-oss-expires=1703521653&x-oss-signature=yNfB2fHwwzqMLNhsI2rQNeIk2zhtqjM0uOTreRmADKg%3D&x-oss-signature-version=OSS2
2023-12-25 15:33:09 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /BIv5gWgx%2F889478%2F64aa9ac634cf0e2367d64899b97542cd1db8e970%2F6589a0972bbbf78ce22e465a94a4e1556e1c5d75?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fTP%2FL%2B2LFq55WeTlCFqnoHafhgqa2SuDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNTTGGzb1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABUL%2Bus3V2F3aK2Ru7D2MqcRAQmWjynj3l%2BIQoeMBBdmeq7FhgYg9Q%2FGKH0m%2BVXV5kyJ%2B1%2BUd5IocHpoymXYcm5jGFDwzxkwNGVquMBD%2BOsuIlqk8j%2FGZ2%2B8lAtds0%2B3D%2FlFw%2F4IpJ6PbNodLElEorqa%2F8LNfJqAiL0xGaum%2FlYGggAA%3D%3D&uploadId=E13FD1924744401FA6C0816D7122FD5F&x-oss-access-key-id=STS.NTftHJ5nKPWuLv4NzRewLFh9Z&x-oss-expires=1703521959&x-oss-signature=DzhL01GcItK32ySXtjfrdgzK7xOQSMCJjRSx5SaDjHM%3D&x-oss-signature-version=OSS2
2023-12-25 15:33:40 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /BIv5gWgx%2F889478%2F64aa9ac634cf0e2367d64899b97542cd1db8e970%2F6589a0972bbbf78ce22e465a94a4e1556e1c5d75?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fTP%2FL%2B2LFq55WeTlCFqnoHafhgqa2SuDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNTTGGzb1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABUL%2Bus3V2F3aK2Ru7D2MqcRAQmWjynj3l%2BIQoeMBBdmeq7FhgYg9Q%2FGKH0m%2BVXV5kyJ%2B1%2BUd5IocHpoymXYcm5jGFDwzxkwNGVquMBD%2BOsuIlqk8j%2FGZ2%2B8lAtds0%2B3D%2FlFw%2F4IpJ6PbNodLElEorqa%2F8LNfJqAiL0xGaum%2FlYGggAA%3D%3D&uploadId=E13FD1924744401FA6C0816D7122FD5F&x-oss-access-key-id=STS.NTftHJ5nKPWuLv4NzRewLFh9Z&x-oss-expires=1703521959&x-oss-signature=DzhL01GcItK32ySXtjfrdgzK7xOQSMCJjRSx5SaDjHM%3D&x-oss-signature-version=OSS2
2023-12-25 15:39:27 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /KEh8oaDh%2F889478%2F64622d2af0cae302a97a4ce3a1d4a4c4e19981d0%2F6589a1f3699fddc1c58f4028ac008b2a64d3c5fd?partNumber=2&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5feIP%2Fbh6tOhKWFZB7X01kfdt4au6TnpDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNVCMQzb1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABZGTExmCjncZjiqKd%2BVZQq6mSLnJmvOn3HcNB%2Fz4q36iqnkgSPa0%2BNmCB%2FcbXV9G9ahZCVr3Reo%2FD3m8kO8EInSFHfu5BOhkfm%2FmDXrSTXJ9cR4o%2BoUNcCv665xNVMq7aEmXkFoezWLUpoLNb%2Foop1tWFjlZhgYzRSSONAqR4SbggAA%3D%3D&uploadId=95E82EA9EA254C0F9C46574CA0F20F9E&x-oss-access-key-id=STS.NTkkEojto3gnf8f7YJzQ6TaLF&x-oss-expires=1703522307&x-oss-signature=4pD4qaRyAz9QPK%2FP1qzzjYI%2BCLpHIcsi9wJjoAez5Q0%3D&x-oss-signature-version=OSS2
2023-12-25 15:39:34 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/KEh8oaDh%2F889478%2F64622d2af0cae302a97a4ce3a1d4a4c4e19981d0%2F6589a1f3699fddc1c58f4028ac008b2a64d3c5fd?partNumber=2&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5feIP%2Fbh6tOhKWFZB7X01kfdt4au6TnpDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNVCMQzb1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABZGTExmCjncZjiqKd%2BVZQq6mSLnJmvOn3HcNB%2Fz4q36iqnkgSPa0%2BNmCB%2FcbXV9G9ahZCVr3Reo%2FD3m8kO8EInSFHfu5BOhkfm%2FmDXrSTXJ9cR4o%2BoUNcCv665xNVMq7aEmXkFoezWLUpoLNb%2Foop1tWFjlZhgYzRSSONAqR4SbggAA%3D%3D&uploadId=95E82EA9EA254C0F9C46574CA0F20F9E&x-oss-access-key-id=STS.NTkkEojto3gnf8f7YJzQ6TaLF&x-oss-expires=1703522307&x-oss-signature=4pD4qaRyAz9QPK%2FP1qzzjYI%2BCLpHIcsi9wJjoAez5Q0%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>6589A230CE3E4E3637B8EDB2</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"EFEC936A5D9AC402AA06EABB074F1968"</PartEtag>
  <PartNumber>2</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-25 15:39:37 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/KEh8oaDh%2F889478%2F64622d2af0cae302a97a4ce3a1d4a4c4e19981d0%2F6589a1f3699fddc1c58f4028ac008b2a64d3c5fd?partNumber=2&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5feIP%2Fbh6tOhKWFZB7X01kfdt4au6TnpDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNVCMQzb1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABZGTExmCjncZjiqKd%2BVZQq6mSLnJmvOn3HcNB%2Fz4q36iqnkgSPa0%2BNmCB%2FcbXV9G9ahZCVr3Reo%2FD3m8kO8EInSFHfu5BOhkfm%2FmDXrSTXJ9cR4o%2BoUNcCv665xNVMq7aEmXkFoezWLUpoLNb%2Foop1tWFjlZhgYzRSSONAqR4SbggAA%3D%3D&uploadId=95E82EA9EA254C0F9C46574CA0F20F9E&x-oss-access-key-id=STS.NTkkEojto3gnf8f7YJzQ6TaLF&x-oss-expires=1703522307&x-oss-signature=4pD4qaRyAz9QPK%2FP1qzzjYI%2BCLpHIcsi9wJjoAez5Q0%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>6589A236CE3E4E363784F2B2</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"EFEC936A5D9AC402AA06EABB074F1968"</PartEtag>
  <PartNumber>2</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-25 15:39:40 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/KEh8oaDh%2F889478%2F64622d2af0cae302a97a4ce3a1d4a4c4e19981d0%2F6589a1f3699fddc1c58f4028ac008b2a64d3c5fd?partNumber=2&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5feIP%2Fbh6tOhKWFZB7X01kfdt4au6TnpDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNVCMQzb1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABZGTExmCjncZjiqKd%2BVZQq6mSLnJmvOn3HcNB%2Fz4q36iqnkgSPa0%2BNmCB%2FcbXV9G9ahZCVr3Reo%2FD3m8kO8EInSFHfu5BOhkfm%2FmDXrSTXJ9cR4o%2BoUNcCv665xNVMq7aEmXkFoezWLUpoLNb%2Foop1tWFjlZhgYzRSSONAqR4SbggAA%3D%3D&uploadId=95E82EA9EA254C0F9C46574CA0F20F9E&x-oss-access-key-id=STS.NTkkEojto3gnf8f7YJzQ6TaLF&x-oss-expires=1703522307&x-oss-signature=4pD4qaRyAz9QPK%2FP1qzzjYI%2BCLpHIcsi9wJjoAez5Q0%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>6589A239CE3E4E363759F4B2</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"EFEC936A5D9AC402AA06EABB074F1968"</PartEtag>
  <PartNumber>2</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-25 15:39:40 - ERROR - aliyundrive.py - 1077 - File tmp/107063778/107063778_p0.png Part 2 upload failed.
2023-12-25 15:43:38 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /RpJk3UeP%2F889478%2F65252521d9a7edd9884447a5b41ab246ce3156db%2F6589a30b307249bb03d8407696fa43d878596b5d?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fzDeyMj45O7o69VBeCkzIUOcxbrp2atDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNR6Bbjb1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABkJH65AC90%2Fc5HMt%2FDWwh8HxmiMaqKp22y8g%2FCo9hfgjm4oZfZNJ%2FYCwPsvd5iicd%2FqUPiB0vN2ILlvYDMJ0Ppey%2Bo5mLQNxxMAdmHmULFeiDNXWtOjYv1z2OZXcG%2FOWRuNY3usMqn%2Fkyjo9NSGySzOikCARUq3i1r%2BnG2On1VMsgAA%3D%3D&uploadId=40D45157DFD64860A2166A14D4E69ACE&x-oss-access-key-id=STS.NTFFV8bQoYLVV13w2A5CwAX1V&x-oss-expires=1703522587&x-oss-signature=9kSTFOG99KBT5GEDPFuMKdXLfJIjGOdjYg%2F1Ae6NbmQ%3D&x-oss-signature-version=OSS2
2023-12-25 15:44:29 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /RpJk3UeP%2F889478%2F65252521d9a7edd9884447a5b41ab246ce3156db%2F6589a30b307249bb03d8407696fa43d878596b5d?partNumber=2&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fzDeyMj45O7o69VBeCkzIUOcxbrp2atDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNR6Bbjb1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABkJH65AC90%2Fc5HMt%2FDWwh8HxmiMaqKp22y8g%2FCo9hfgjm4oZfZNJ%2FYCwPsvd5iicd%2FqUPiB0vN2ILlvYDMJ0Ppey%2Bo5mLQNxxMAdmHmULFeiDNXWtOjYv1z2OZXcG%2FOWRuNY3usMqn%2Fkyjo9NSGySzOikCARUq3i1r%2BnG2On1VMsgAA%3D%3D&uploadId=40D45157DFD64860A2166A14D4E69ACE&x-oss-access-key-id=STS.NTFFV8bQoYLVV13w2A5CwAX1V&x-oss-expires=1703522587&x-oss-signature=c2lW019Ze%2B4OYtGsKW9C3Dkw0hkTtRRRwVeEROqOqAE%3D&x-oss-signature-version=OSS2
2023-12-25 15:45:00 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /RpJk3UeP%2F889478%2F65252521d9a7edd9884447a5b41ab246ce3156db%2F6589a30b307249bb03d8407696fa43d878596b5d?partNumber=2&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fzDeyMj45O7o69VBeCkzIUOcxbrp2atDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNR6Bbjb1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABkJH65AC90%2Fc5HMt%2FDWwh8HxmiMaqKp22y8g%2FCo9hfgjm4oZfZNJ%2FYCwPsvd5iicd%2FqUPiB0vN2ILlvYDMJ0Ppey%2Bo5mLQNxxMAdmHmULFeiDNXWtOjYv1z2OZXcG%2FOWRuNY3usMqn%2Fkyjo9NSGySzOikCARUq3i1r%2BnG2On1VMsgAA%3D%3D&uploadId=40D45157DFD64860A2166A14D4E69ACE&x-oss-access-key-id=STS.NTFFV8bQoYLVV13w2A5CwAX1V&x-oss-expires=1703522587&x-oss-signature=c2lW019Ze%2B4OYtGsKW9C3Dkw0hkTtRRRwVeEROqOqAE%3D&x-oss-signature-version=OSS2
2023-12-25 15:58:21 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-25 15:58:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-25 22:14:18 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-25 22:21:10 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/06/05/01/02/00/98832304_p0.jpg
2023-12-25 22:28:54 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-25 22:28:55 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-25 22:40:40 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-25 22:40:41 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-25 22:41:41 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/10/25/00/00/18/112824300_p0.jpg
2023-12-25 23:13:59 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/07/14/10/09/12/109896956_p0.png
2023-12-25 23:47:50 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/03/13/00/04/03/106163215_p0.jpg
2023-12-26 00:13:20 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-26 00:33:02 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/13/05/54/45/110780066_p0.jpg
2023-12-26 00:50:28 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-26 00:50:29 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-26 10:16:03 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-26 10:19:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-26 10:19:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-26 10:48:39 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/04/02/00/00/01/106775671_p0.jpg
2023-12-26 10:51:21 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/10/03/00/00/14/112226083_p0.jpg
2023-12-26 10:57:13 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2021/03/07/00/01/22/88263776_p0.jpg
2023-12-26 11:23:16 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-26 11:23:17 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-26 11:24:39 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/04/28/00/07/05/97926318_p0.jpg
2023-12-26 11:34:08 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/10/00/00/47/110683857_p0.jpg
2023-12-26 11:54:49 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-26 11:54:50 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-26 12:15:04 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-26 22:13:58 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-26 22:36:40 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/03/08/20/08/02/96770135_p0.png
2023-12-26 22:46:46 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-26 22:46:47 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-26 22:56:16 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/06/00/23/29/113985263_p0.jpg
2023-12-26 23:08:26 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/09/07/12/51/16/111515203_p0.jpg
2023-12-26 23:14:30 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/02/00/10/36/113872695_p0.jpg
2023-12-26 23:17:40 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/09/11/00/10/52/111621455_p0.png
2023-12-26 23:22:21 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/11/22/23/39/48/113625731_p0.jpg
2023-12-26 23:51:39 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-26 23:51:40 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-26 23:54:27 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /b8JrbE3V%2F889478%2F64f32ec18e3b8a5b89fd4750a165a9a2704c8841%2F658b6795d15ae2dd617e4cb8b3b22991b209261d?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5eBAPCNi5VSwquYTnT8s2E3RMVvhPbuoDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNQj0Kgf1qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABfD2oAA%2FNXIhLEFA%2F8DDr8fwUtVkNwdmPqUOfj8wTAMV3Lvqr3CqH4MaatEhLNPj9rc6Qaj0a9Z9N9EEEpLSVDJjx1AVLGAvHiHxz03dBWNMTO4Jihpik1Em5NE9qgspeCKg0vCRiEB9iWOzQjVoc2OUeiss5VzWTifdw10Tl218gAA%3D%3D&uploadId=3421E7E3A2464856BA810F06F20D8EE8&x-oss-access-key-id=STS.NT4KJ9fJsuisLRMWabHJCk3EB&x-oss-expires=1703638437&x-oss-signature=XHVSmtogNXy7q6eUhNq3IipDruooKsJqcsxPsuUlHME%3D&x-oss-signature-version=OSS2
2023-12-26 23:58:32 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/03/00/00/30/113901295_p0.jpg
2023-12-27 00:12:59 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-27 00:16:11 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/11/30/00/35/08/113820032_p0.jpg
2023-12-27 00:32:57 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/02/00/01/28/113872199_p0.png
2023-12-27 00:34:44 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/27/19/34/04/111099918_p0.jpg
2023-12-27 00:36:59 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /nWhou8QA%2F889478%2F65801f40c95ded7c01f0451fb49d7c9937a44d8d%2F658b718ca40e27bc71e24187862a1a192b5222aa?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5DEeo7sgudz%2F6%2BRdVX9oncYae5ulZzPujz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNX%2FdCX70qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABtRu3%2BaN3Z%2FRvffkEt3HG1u8FVEEiXm%2BoRJ6nlAwcrNQtM%2FWGDs2VXHRDUruSUvrWwxj8mYqiwOwHCsxaVS3GdkSbhN%2BS63IpM9raGk4IReRJdoAbwZfPubG7U%2FsL6%2FaiLP4x6YUjRX%2FiIFi3XlotSb%2BsphGAWT3ouryI9UlmwR0gAA%3D%3D&uploadId=1852D34DD1C54ACCB6FF73FDED96454B&x-oss-access-key-id=STS.NSq14Xo8RHmzwsLFwMeaBzYdX&x-oss-expires=1703640988&x-oss-signature=tt77YT7iLPZcNsKtkQM5KjAVZqnI%2BD3nVbhjsDVaoUQ%3D&x-oss-signature-version=OSS2
2023-12-27 00:43:21 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /AlTdJmTO%2F889478%2F621f446f898dd47bbe2f47239a762ba0a015f0dc%2F658b730b2e6be50db7d74ad1afe1edf662a68dcc?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fyDYzitYtrxPXdSWvQ10gQZN9p16f%2FgTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNWKIH370qFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABLi1je5hqglRhAplNm26ZIuGCbnU6LlpdwjQgy3J%2FvwazfcE%2BLiEpPE7oI3mTsCWm%2Be06azf1YRtfPQsJBqYJ5bV2srmGqXrzbKwqFOFKLLA%2ByxzzMj1FQXgv%2B6W%2BlLicLSi1lW7RzG0CQ%2BPK4uHEl%2FBEHwAVAj2ihIIQxrQL5tMgAA%3D%3D&uploadId=74E8E0A1A5FE444C821FBD0DC2213F62&x-oss-access-key-id=STS.NTGF6VXTJs76KMa3HEhPE8bTc&x-oss-expires=1703641371&x-oss-signature=Ov%2Fz4UuWmTgc%2BlxD%2Bw5FYkF1Ti%2Fi7eL6pRYllmBW854%3D&x-oss-signature-version=OSS2
2023-12-27 10:16:14 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-27 10:35:46 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/12/00/00/35/114150421_p0.jpg
2023-12-27 11:19:50 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-27 11:19:51 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-27 11:28:19 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/09/20/35/51/114084009_p0.jpg
2023-12-27 11:41:56 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/09/20/13/31/43/111878768_p0.jpg
2023-12-27 11:46:07 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/04/09/00/09/28/97496509_p0.png
2023-12-27 11:55:08 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/06/12/42/43/110575312_p0.png
2023-12-27 12:03:37 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-27 12:03:38 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-27 12:12:52 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/10/00/16/01/114091646_p0.jpg
2023-12-27 12:14:27 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-27 12:14:28 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-27 12:15:15 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-27 12:21:48 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-27 12:21:49 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-27 12:24:48 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/07/10/00/00/114018412_p0.png
2023-12-27 22:14:18 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-27 22:30:58 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/04/11/00/03/23/107064072_p0.jpg
2023-12-27 22:34:12 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/10/04/19/55/26/112269716_p0.jpg
2023-12-27 22:46:20 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/03/29/08/06/37/106659954_p0.jpg
2023-12-27 22:54:40 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/09/26/15/28/43/101501492_p0.jpg
2023-12-27 23:14:02 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/31/04/54/03/111309457_p0.jpg
2023-12-27 23:57:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-27 23:57:53 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-28 00:13:18 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-28 00:21:45 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-28 00:21:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-28 10:16:17 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-28 10:21:07 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-28 10:21:08 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-28 10:51:30 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/26/17/06/23/114573429_p0.jpg
2023-12-28 11:21:16 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/21/16/44/27/114411082_p0.jpg
2023-12-28 11:21:48 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2023-12-28 11:21:48 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2023-12-28 11:21:49 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-28 11:23:52 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/05/00/00/44/113959204_p0.jpg
2023-12-28 11:25:30 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-28 11:25:31 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-28 11:36:13 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-28 11:36:14 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-28 12:15:18 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-28 22:14:12 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-28 22:28:30 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/23/00/12/23/111076126_p0.jpg
2023-12-28 22:30:34 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-28 22:30:35 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-28 23:04:00 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/10/09/00/00/06/112388340_p0.jpg
2023-12-28 23:31:55 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://api.aliyundrive.com/adrive/v2/file/createWithFolders</td>
</tr>
<tr>
<td>Server:</td>
<td>security-pgw-90b2f6b7d69951d209f28a873243d040-s46d9</td>
</tr>
<tr>
<td>Date:</td>
<td>2023/12/29 07:31:55</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

2023-12-28 23:31:55 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2023-12-28 23:31:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-28 23:32:28 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://api.aliyundrive.com/v2/file/complete</td>
</tr>
<tr>
<td>Server:</td>
<td>security-pgw-90b2f6b7d69951d209f28a873243d040-s46d9</td>
</tr>
<tr>
<td>Date:</td>
<td>2023/12/29 07:32:28</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

2023-12-28 23:32:28 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2023-12-28 23:32:29 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-28 23:46:57 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/03/00/07/35/110475198_p0.jpg
2023-12-29 00:13:12 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-29 10:16:12 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-29 10:17:22 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 10:17:23 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-29 10:18:27 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:429:
2023-12-29 10:18:27 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2023-12-29 10:18:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-29 10:19:33 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 10:19:34 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-29 10:29:22 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 10:29:23 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-29 10:51:33 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/11/29/00/00/47/113792751_p0.jpg
2023-12-29 10:51:57 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/01/18/05/56/45/104608220_p0.jpg
2023-12-29 10:53:01 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 10:53:02 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-29 10:55:38 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/27/08/53/09/111189950_p0.jpg
2023-12-29 11:40:10 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2021/02/11/10/29/15/87680885_p0.jpg
2023-12-29 11:42:19 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 11:42:20 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-29 11:44:33 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 11:44:34 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-29 11:46:54 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 11:46:55 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-29 11:52:55 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 11:52:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-29 11:55:16 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 11:55:17 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-29 12:09:30 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 12:09:31 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-29 12:11:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 12:11:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-29 12:14:33 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 12:14:34 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-29 12:15:13 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-29 12:25:45 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 12:25:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-29 12:28:04 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 12:28:05 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-29 12:30:20 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 12:30:21 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-29 12:32:57 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 12:32:58 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-29 12:36:10 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 12:36:11 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-29 12:37:34 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/07/04/00/36/59/109597339_p0.png
2023-12-29 12:44:26 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/04/06/13/00/01/106914958_p0.jpg
2023-12-29 12:48:34 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/01/05/18/00/10/104259313_p0.jpg
2023-12-29 12:51:44 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/11/07/18/00/09/113217217_p0.jpg
2023-12-29 22:14:15 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-29 23:30:32 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 23:30:33 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-29 23:32:23 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-29 23:32:24 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-30 10:14:59 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-30 11:01:15 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/10/09/17/08/29/112407096_p0.jpg
2023-12-30 11:03:39 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/11/27/00/00/36/113741651_p0.jpg
2023-12-30 11:15:48 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-30 11:15:49 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-30 11:23:43 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/09/11/08/00/01/101144405_p0.jpg
2023-12-30 11:54:12 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/10/22/00/00/12/112742030_p0.jpg
2023-12-30 11:58:27 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-30 11:58:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-30 12:06:23 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /CqOsGFYE%2F889478%2F6577a11980a126dbd1fc42f399d171d88d7862c2%2F659007a1263c65b1d760475d8195178c33b35732?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fhPNnnrrVlx4S9bBTXhTYsOctVioucpTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNU3DYG3zqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABKthOCWr5CDBUkx035pTrNTTj9U7KNGMDXFelldANl8cAMgfGo%2FJZWSJOAnZLkYCbG4xmxjhoeVkni9LlCHEG75bA1Acy8Yv1hy3L4p8%2Fd68INbUThYSmoKoz9B4buxRhqHZJhcId1raHP2vommC2rk58jvygfCZFIEUb7fN4AvMgAA%3D%3D&uploadId=096994279D6A44899ECA34C1B49E66CD&x-oss-access-key-id=STS.NTTwcSCjDpFVn2fa6y5DyeN7G&x-oss-expires=1703941553&x-oss-signature=nALKmmAqFHFBQ%2FoWUrWQmHiq0lLMcjS4Ou44UjhRXPc%3D&x-oss-signature-version=OSS2
2023-12-30 12:06:25 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/CqOsGFYE%2F889478%2F6577a11980a126dbd1fc42f399d171d88d7862c2%2F659007a1263c65b1d760475d8195178c33b35732?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fhPNnnrrVlx4S9bBTXhTYsOctVioucpTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNU3DYG3zqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABKthOCWr5CDBUkx035pTrNTTj9U7KNGMDXFelldANl8cAMgfGo%2FJZWSJOAnZLkYCbG4xmxjhoeVkni9LlCHEG75bA1Acy8Yv1hy3L4p8%2Fd68INbUThYSmoKoz9B4buxRhqHZJhcId1raHP2vommC2rk58jvygfCZFIEUb7fN4AvMgAA%3D%3D&uploadId=096994279D6A44899ECA34C1B49E66CD&x-oss-access-key-id=STS.NTTwcSCjDpFVn2fa6y5DyeN7G&x-oss-expires=1703941553&x-oss-signature=nALKmmAqFHFBQ%2FoWUrWQmHiq0lLMcjS4Ou44UjhRXPc%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>659007C130486B3330849242</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"3BA39DAEE8310F14EFA68A75A8F3CA0A"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-30 12:06:25 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/CqOsGFYE%2F889478%2F6577a11980a126dbd1fc42f399d171d88d7862c2%2F659007a1263c65b1d760475d8195178c33b35732?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fhPNnnrrVlx4S9bBTXhTYsOctVioucpTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNU3DYG3zqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABKthOCWr5CDBUkx035pTrNTTj9U7KNGMDXFelldANl8cAMgfGo%2FJZWSJOAnZLkYCbG4xmxjhoeVkni9LlCHEG75bA1Acy8Yv1hy3L4p8%2Fd68INbUThYSmoKoz9B4buxRhqHZJhcId1raHP2vommC2rk58jvygfCZFIEUb7fN4AvMgAA%3D%3D&uploadId=096994279D6A44899ECA34C1B49E66CD&x-oss-access-key-id=STS.NTTwcSCjDpFVn2fa6y5DyeN7G&x-oss-expires=1703941553&x-oss-signature=nALKmmAqFHFBQ%2FoWUrWQmHiq0lLMcjS4Ou44UjhRXPc%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>659007C130486B3330EE9242</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"3BA39DAEE8310F14EFA68A75A8F3CA0A"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-30 12:06:26 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/CqOsGFYE%2F889478%2F6577a11980a126dbd1fc42f399d171d88d7862c2%2F659007a1263c65b1d760475d8195178c33b35732?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fhPNnnrrVlx4S9bBTXhTYsOctVioucpTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNU3DYG3zqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABKthOCWr5CDBUkx035pTrNTTj9U7KNGMDXFelldANl8cAMgfGo%2FJZWSJOAnZLkYCbG4xmxjhoeVkni9LlCHEG75bA1Acy8Yv1hy3L4p8%2Fd68INbUThYSmoKoz9B4buxRhqHZJhcId1raHP2vommC2rk58jvygfCZFIEUb7fN4AvMgAA%3D%3D&uploadId=096994279D6A44899ECA34C1B49E66CD&x-oss-access-key-id=STS.NTTwcSCjDpFVn2fa6y5DyeN7G&x-oss-expires=1703941553&x-oss-signature=nALKmmAqFHFBQ%2FoWUrWQmHiq0lLMcjS4Ou44UjhRXPc%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>659007C130486B3330279342</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"3BA39DAEE8310F14EFA68A75A8F3CA0A"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2023-12-30 12:06:26 - ERROR - aliyundrive.py - 1077 - File tmp/114150535/114150535.json.txt Part 1 upload failed.
2023-12-30 12:14:11 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /7kkcXZct%2F889478%2F64f1d38aba6c14e6fea64be083b4bc8367134815%2F65900974ac32c605a2994b97839e2d6858b8622f?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fkGY6MrIhQgq2gaRPU3VMvXNx01q7MoDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNXTZQ23zqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABU%2BJClSduf5X%2B2MDgjzy62hPxImMb9qs0ajfrMQudlpkLJ6n3lDrAOTo6kIi6wtyIFh8nU%2FtVPWqRD%2FHaPBpVJfTt6o8JMjhTFTbfOtwcAgeiyTttdMQ%2FP%2Fm%2BnSs%2F3okBygU8FluiVO%2B9qiBpl2uKJAa0MLhLybEZMdQGMrzAGoAgAA%3D%3D&uploadId=0BCB710C1413461686A9B76510D56DFB&x-oss-access-key-id=STS.NTQR48AWq5oKk5e9SzPSX9kgB&x-oss-expires=1703942020&x-oss-signature=NLvzfeu%2B08XWfKTPFGImI1T%2F4LD%2FOqO4J%2BYBb%2FZJ9u8%3D&x-oss-signature-version=OSS2
2023-12-30 12:14:14 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-30 12:30:34 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-30 12:30:35 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-30 12:44:36 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /q1JiXrS3%2F889478%2F659010961e32a0a4518347dd974ba2cf8243106f%2F65901096a130672bdfaa4797a90a9c545fe0def6?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5DADPv3rqps2pLSRRfkkDUYQfpFofL4ljz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNRjAU23zqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABkig%2BUY7b8vpNqKGuUszsD%2F%2FaWVEWsplJPE1zG7Qk95YLCenYMFdBVp5HwEx6q8kG72TmkxXGybSeeR25%2F8QmJta7CJ7ScKST%2BHqTIkcnZyB1nZqwHCZ3Nh3Vo1HMYpbX5SIL2N8uRDcMiov7R4BpuNMB0tTFFILIvBAGu9y039YgAA%3D%3D&uploadId=8F8887FFB1C041029C5497AFBC573B3E&x-oss-access-key-id=STS.NSuGACCuMmP9G1Ut5MMuiN7St&x-oss-expires=1703943846&x-oss-signature=moOGdnbSBZL%2F4jD4v%2F%2BekbjbGS89Du66EXgqrV61U3A%3D&x-oss-signature-version=OSS2
2023-12-30 12:48:05 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /F1MH3oBw%2F889478%2F6249745c58e780090cbb415186eda74e35993b81%2F65901167d345067a0c5441a2b4b893a7649e0a9b?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5WGKs3QqI5s07LcbxDWlkQyQPYUqqbzizz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNTGlNG3zqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABiZDajfCWrkMqXUEezWTKOowWCQ6A%2BOvF5N6WqY5IF1FA2DJY%2FpSb%2F86muMkAmakOnYjN5fWy0p3Reotnb8N9JKCUiOm%2Bu6T%2B7OGecUSC9DjGqwSGCNnGgFfeJfJk0MkKrepiQZ7U1KU4sK0iTIrfOD0KoLiFPtXKEd737M36AbEgAA%3D%3D&uploadId=493007A1F2B1403AA5302049F0DAA676&x-oss-access-key-id=STS.NV3awdEQMdp7m6grDgLy8EcXi&x-oss-expires=1703944055&x-oss-signature=bbtgr31fgsKB4u4K8g%2BmCYjACk6lYGR1z9ngLS2z3Do%3D&x-oss-signature-version=OSS2
2023-12-30 12:48:49 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/11/22/09/14/15/113608478_p0.jpg
2023-12-30 13:00:05 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2023-12-30 13:00:05 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2023-12-30 13:00:06 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-30 13:07:20 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/01/03/00/00/13/104180146_p0.jpg
2023-12-30 13:11:45 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-30 13:11:46 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-30 22:13:54 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-30 23:51:02 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-30 23:51:03 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-30 23:59:12 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/09/26/00/00/36/112035654_p0.png
2023-12-31 00:05:05 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/11/22/01/07/23/113602622_p0.jpg
2023-12-31 00:12:54 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-31 00:12:55 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-31 00:12:58 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-31 00:29:35 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-31 00:29:36 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-31 10:15:20 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-31 10:20:56 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/03/00/01/04/113901374_p0.jpg
2023-12-31 10:23:56 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/07/08/21/37/45/109739773_p0.jpg
2023-12-31 10:58:31 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/10/31/00/00/25/112988602_p0.jpg
2023-12-31 12:14:20 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-31 12:32:23 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-31 12:32:24 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2023-12-31 13:04:50 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /evOsK1hN%2F889478%2F658ac264ea0c3c1944d147ddbee9b48b07c44a08%2F659166d4d7c2a6a874ef40bda41173538df2a8b0?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5eDI%2F2Hjo9L3IrcZWfAr1QReNtCmpLjizz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNVawJkfzqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABTsZzFAfziM1tu2y%2BN%2BofWlLWydoi3KEIdSfjgvaogOQG4Qt6eW74YPOzrLMwgsyWSZfd7Ig86K%2By3pdt%2F9EffhR%2FRKFvxI6lt00o4ZbbUDxE96PPzYYJ7qaFPq6c8y%2Fb1%2FadUeCdQ4BDVAH67q54haJ933I6%2FrYOEYpZXReQ714gAA%3D%3D&uploadId=62070B1F7CB84E03B5AC019181FD52B1&x-oss-access-key-id=STS.NT6hG3cPjkH7gAqKTDtTnuWHi&x-oss-expires=1704031460&x-oss-signature=NA3fpVNmQHgK0k8RCvg%2B989ww3jzkn4K2yDmZo8y%2Bgg%3D&x-oss-signature-version=OSS2
2023-12-31 13:26:38 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/19/13/59/46/114356855_p0.png
2023-12-31 22:13:49 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2023-12-31 22:17:18 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/03/21/15/51/113926885_p0.jpg
2023-12-31 22:33:41 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-31 22:33:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-12-31 22:54:31 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/04/08/00/28/53/106963527_p0.png
2023-12-31 22:54:56 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2021/05/27/21/08/13/90133156_p0.jpg
2023-12-31 23:16:40 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/06/24/00/00/32/109281305_p0.jpg
2023-12-31 23:17:27 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-12-31 23:17:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-01-01 00:12:49 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-01-01 22:14:43 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-01-01 22:18:56 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-01-01 22:18:57 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-01-01 22:31:59 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/109140616/109140616_ugoira0.gif, upload original page.
2024-01-01 22:33:16 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /7Y22h9Sw%2F889478%2F629f38a1da539433ca9e4210b862a750d3e5a3a4%2F65933d8e0d24dc5a707749c4bb9706534733b4ab?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5aEA9jArI5Mx5ilVEXlgVM7bfUen%2F3Ppjz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNWSnFg7zqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABH%2B80vwndGmDTj6vjyukva1ULe01FKp8jBq7%2B4Jiu3W58vV1%2FgEIPxfAWUUU9DyFi7VP3XvC8dK3GqvxuDSISMI7aaTTdzhnDbR3KsAZM85sRapzwgjgzVFvtJQoKJzq803MTicRMGOwsZUpKahroZF4exHCiGtcFeTrjTjFCelUgAA%3D%3D&uploadId=7762F7BBC6D542169752A2F6EBBECCFE&x-oss-access-key-id=STS.NU1HbtAQmpZNVcTeSnaz2p8dD&x-oss-expires=1704151966&x-oss-signature=Wnmii%2Faw91wqyJlc88C2r0BlhXvZRY7K66IsODHjXOo%3D&x-oss-signature-version=OSS2
2024-01-01 23:00:36 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-01-01 23:00:37 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-01-01 23:01:35 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/10/28/18/21/16/112919036_p0.png
2024-01-01 23:16:27 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/09/08/23/54/14/111556748_p0.jpg
2024-01-01 23:17:30 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/12/00/05/03/114150784_p0.png
2024-01-01 23:32:56 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-01-01 23:32:57 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-01-01 23:34:07 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /YuEb13UO%2F889478%2F6280d3d317e8d5271bd44557a1bcac59c7ae23db%2F65934bd077c130f9038c47e987dbc4597145536b?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5b2eumChucX3LuZM2P3vkEZfup1lY3ImDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNTq%2FGw7zqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABPKVeFBKrhlFU%2B%2FmEMmKczGCWq2%2B8qTwYMDJf6TN7mYY2Czy7vN3n%2B%2F5a1Mu%2B38%2Bra0VfSkDBk1MmUCm434SvuX6HS9fgXIh0%2B6TXfMfFDBHV%2FXoO0tkKw6uM55TOO90v0stvYxtS29prmW987b4CST%2FiR1FNNJKZS5DDmYKp1hQgAA%3D%3D&uploadId=A803C8D6AC5B474FB64F18E6CF364257&x-oss-access-key-id=STS.NUC1S6k86kyr1EFZALreYzHcz&x-oss-expires=1704155616&x-oss-signature=oTY2wnm%2B%2Biw3%2FXdyTYQqTwutMCmAOpkR4BffACvI6kc%3D&x-oss-signature-version=OSS2
2024-01-02 00:11:51 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/01/18/00/00/02/95598895_p0.jpg
2024-01-02 00:13:43 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-01-02 00:19:16 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/10/16/13/06/39/112596627_p0.png
2024-01-02 01:25:48 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-01-02 01:25:49 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
