2021-11-16 08:03:27 - INFO - bot.py - 245 - Create ranking dynamic Success!
2021-11-16 10:04:22 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:04:59 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:05:01 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:05:02 - ERROR - base.py - 25 - All retries failed in func _post_draw_image_upload.
2021-11-16 10:05:07 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:05:09 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:05:11 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:05:12 - ERROR - base.py - 25 - All retries failed in func _post_draw_image_upload.
2021-11-16 10:06:01 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:07 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:17 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:18 - ERROR - base.py - 25 - All retries failed in func _post_draw_image_upload.
2021-11-16 10:06:24 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:29 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:36 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:37 - ERROR - base.py - 25 - All retries failed in func _post_draw_image_upload.
2021-11-16 10:06:38 - INFO - bot.py - 245 - Create ranking dynamic Success!
2021-11-16 12:22:21 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-16 14:19:23 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-16 16:19:47 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-16 18:18:39 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-16 20:08:08 - ERROR - base.py - 51 - https://i.pximg.net/img-original/img/2021/08/05/23/13/46/91751463_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-16 20:08:08 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/05/23/13/46/91751463_p0.png.
2021-11-16 20:19:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-16 22:12:26 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-17 04:02:54 - INFO - __main__.py - 38 - 22237.386504 seconds before last successful new update, try create new one.
2021-11-17 04:03:28 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-17 10:02:45 - INFO - __main__.py - 38 - 22192 seconds before last successful new update, try create new one.
2021-11-17 10:15:33 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-17 10:15:33 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png.
2021-11-17 10:15:34 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-17 10:17:07 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-17 12:05:55 - INFO - __main__.py - 60 - Last dynamic don't exist, redo create dynamic task.
2021-11-17 12:20:26 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-17 18:02:11 - INFO - __main__.py - 38 - 21977 seconds before last successful new update, try create new one.
2021-11-17 18:17:29 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 00:16:08 - INFO - __main__.py - 38 - 23036 seconds before last successful new update, try create new one.
2021-11-18 00:21:28 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-18 00:21:28 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg.
2021-11-18 00:21:29 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-18 00:31:30 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 02:19:16 - INFO - __main__.py - 60 - Last dynamic don't exist, redo create dynamic task.
2021-11-18 02:29:09 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 04:02:28 - INFO - __main__.py - 60 - Last dynamic don't exist, redo create dynamic task.
2021-11-18 04:03:03 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 10:02:18 - INFO - __main__.py - 38 - 22191 seconds before last successful new update, try create new one.
2021-11-18 10:07:23 - ERROR - base.py - 60 - https://www.pixiv.net/ajax/illust/91049805:('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2021-11-18 10:07:24 - WARNING - base.py - 23 - Retry func _get_illust 2 time.
2021-11-18 10:12:18 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 16:03:06 - INFO - __main__.py - 38 - 22247 seconds before last successful new update, try create new one.
2021-11-18 16:04:35 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/27/18/21/23/93058710_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-18 16:04:35 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/27/18/21/23/93058710_p0.jpg.
2021-11-18 16:04:36 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-18 16:19:32 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 22:02:07 - INFO - __main__.py - 38 - 22142 seconds before last successful new update, try create new one.
2021-11-18 22:16:56 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-19 04:02:31 - INFO - __main__.py - 38 - 22225 seconds before last successful new update, try create new one.
2021-11-19 04:03:15 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-19 10:02:15 - INFO - __main__.py - 38 - 22184 seconds before last successful new update, try create new one.
2021-11-19 10:18:23 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-19 16:02:59 - INFO - __main__.py - 38 - 22245 seconds before last successful new update, try create new one.
2021-11-19 16:10:27 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/05/19/34/44/91035045_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-19 16:10:27 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/05/19/34/44/91035045_p0.png.
2021-11-19 16:10:28 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-19 16:17:50 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-19 22:02:20 - INFO - __main__.py - 38 - 22162 seconds before last successful new update, try create new one.
2021-11-19 22:09:20 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/05/19/34/44/91035045_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-19 22:09:20 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/05/19/34/44/91035045_p0.png.
2021-11-19 22:09:21 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-19 22:16:15 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 04:02:35 - INFO - __main__.py - 38 - 22215 seconds before last successful new update, try create new one.
2021-11-20 04:03:13 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 10:02:17 - INFO - __main__.py - 38 - 22183 seconds before last successful new update, try create new one.
2021-11-20 10:02:44 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 12:03:51 - INFO - __main__.py - 60 - Last dynamic don't exist, redo create dynamic task.
2021-11-20 12:18:48 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 18:02:19 - INFO - __main__.py - 37 - 22109 seconds before last successful new update, try create new one.
2021-11-20 18:17:32 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 20:02:03 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-20 20:09:41 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/03/00/00/06/90966760_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-20 20:09:41 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/03/00/00/06/90966760_p0.jpg.
2021-11-20 20:09:42 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-20 20:17:57 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 22:02:07 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-20 22:12:37 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-21 04:02:31 - INFO - __main__.py - 37 - 22223 seconds before last successful new update, try create new one.
2021-11-21 04:03:07 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-21 06:02:34 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-21 06:07:33 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-21 06:07:33 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg.
2021-11-21 06:07:34 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-21 06:16:20 - INFO - bot.py - 248 - Create ranking dynamic Success!
