2021-11-16 08:03:27 - INFO - bot.py - 245 - Create ranking dynamic Success!
2021-11-16 10:04:22 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:04:59 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:05:01 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:05:02 - ERROR - base.py - 25 - All retries failed in func _post_draw_image_upload.
2021-11-16 10:05:07 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:05:09 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:05:11 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:05:12 - ERROR - base.py - 25 - All retries failed in func _post_draw_image_upload.
2021-11-16 10:06:01 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:07 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:17 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:18 - ERROR - base.py - 25 - All retries failed in func _post_draw_image_upload.
2021-11-16 10:06:24 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:29 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:36 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:37 - ERROR - base.py - 25 - All retries failed in func _post_draw_image_upload.
2021-11-16 10:06:38 - INFO - bot.py - 245 - Create ranking dynamic Success!
2021-11-16 12:22:21 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-16 14:19:23 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-16 16:19:47 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-16 18:18:39 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-16 20:08:08 - ERROR - base.py - 51 - https://i.pximg.net/img-original/img/2021/08/05/23/13/46/91751463_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-16 20:08:08 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/05/23/13/46/91751463_p0.png.
2021-11-16 20:19:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-16 22:12:26 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-17 04:02:54 - INFO - __main__.py - 38 - 22237.386504 seconds before last successful new update, try create new one.
2021-11-17 04:03:28 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-17 10:02:45 - INFO - __main__.py - 38 - 22192 seconds before last successful new update, try create new one.
2021-11-17 10:15:33 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-17 10:15:33 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png.
2021-11-17 10:15:34 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-17 10:17:07 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-17 12:05:55 - INFO - __main__.py - 60 - Last dynamic don't exist, redo create dynamic task.
2021-11-17 12:20:26 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-17 18:02:11 - INFO - __main__.py - 38 - 21977 seconds before last successful new update, try create new one.
2021-11-17 18:17:29 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 00:16:08 - INFO - __main__.py - 38 - 23036 seconds before last successful new update, try create new one.
2021-11-18 00:21:28 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-18 00:21:28 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg.
2021-11-18 00:21:29 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-18 00:31:30 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 02:19:16 - INFO - __main__.py - 60 - Last dynamic don't exist, redo create dynamic task.
2021-11-18 02:29:09 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 04:02:28 - INFO - __main__.py - 60 - Last dynamic don't exist, redo create dynamic task.
2021-11-18 04:03:03 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 10:02:18 - INFO - __main__.py - 38 - 22191 seconds before last successful new update, try create new one.
2021-11-18 10:07:23 - ERROR - base.py - 60 - https://www.pixiv.net/ajax/illust/91049805:('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2021-11-18 10:07:24 - WARNING - base.py - 23 - Retry func _get_illust 2 time.
2021-11-18 10:12:18 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 16:03:06 - INFO - __main__.py - 38 - 22247 seconds before last successful new update, try create new one.
2021-11-18 16:04:35 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/27/18/21/23/93058710_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-18 16:04:35 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/27/18/21/23/93058710_p0.jpg.
2021-11-18 16:04:36 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-18 16:19:32 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 22:02:07 - INFO - __main__.py - 38 - 22142 seconds before last successful new update, try create new one.
2021-11-18 22:16:56 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-19 04:02:31 - INFO - __main__.py - 38 - 22225 seconds before last successful new update, try create new one.
2021-11-19 04:03:15 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-19 10:02:15 - INFO - __main__.py - 38 - 22184 seconds before last successful new update, try create new one.
2021-11-19 10:18:23 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-19 16:02:59 - INFO - __main__.py - 38 - 22245 seconds before last successful new update, try create new one.
2021-11-19 16:10:27 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/05/19/34/44/91035045_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-19 16:10:27 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/05/19/34/44/91035045_p0.png.
2021-11-19 16:10:28 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-19 16:17:50 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-19 22:02:20 - INFO - __main__.py - 38 - 22162 seconds before last successful new update, try create new one.
2021-11-19 22:09:20 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/05/19/34/44/91035045_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-19 22:09:20 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/05/19/34/44/91035045_p0.png.
2021-11-19 22:09:21 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-19 22:16:15 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 04:02:35 - INFO - __main__.py - 38 - 22215 seconds before last successful new update, try create new one.
2021-11-20 04:03:13 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 10:02:17 - INFO - __main__.py - 38 - 22183 seconds before last successful new update, try create new one.
2021-11-20 10:02:44 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 12:03:51 - INFO - __main__.py - 60 - Last dynamic don't exist, redo create dynamic task.
2021-11-20 12:18:48 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 18:02:19 - INFO - __main__.py - 37 - 22109 seconds before last successful new update, try create new one.
2021-11-20 18:17:32 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 20:02:03 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-20 20:09:41 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/03/00/00/06/90966760_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-20 20:09:41 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/03/00/00/06/90966760_p0.jpg.
2021-11-20 20:09:42 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-20 20:17:57 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 22:02:07 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-20 22:12:37 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-21 04:02:31 - INFO - __main__.py - 37 - 22223 seconds before last successful new update, try create new one.
2021-11-21 04:03:07 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-21 06:02:34 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-21 06:07:33 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-21 06:07:33 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg.
2021-11-21 06:07:34 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-21 06:16:20 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-21 12:03:19 - INFO - __main__.py - 37 - 22245 seconds before last successful new update, try create new one.
2021-11-21 12:11:06 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/03/00/00/06/90966760_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-21 12:11:06 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/03/00/00/06/90966760_p0.jpg.
2021-11-21 12:11:07 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-21 12:19:12 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-21 18:02:31 - INFO - __main__.py - 37 - 22152 seconds before last successful new update, try create new one.
2021-11-21 18:07:55 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/06/20/16/02/05/90685484_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-21 18:07:55 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/06/20/16/02/05/90685484_p0.jpg.
2021-11-21 18:07:56 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-21 18:12:35 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-22 00:16:13 - INFO - __main__.py - 37 - 23022 seconds before last successful new update, try create new one.
2021-11-22 00:31:08 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-22 06:03:44 - INFO - __main__.py - 37 - 21451 seconds before last successful new update, try create new one.
2021-11-22 06:04:18 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-22 12:03:56 - INFO - __main__.py - 37 - 22212 seconds before last successful new update, try create new one.
2021-11-22 12:19:44 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-22 18:02:37 - INFO - __main__.py - 37 - 22122 seconds before last successful new update, try create new one.
2021-11-22 18:16:31 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-23 00:16:05 - INFO - __main__.py - 37 - 23009 seconds before last successful new update, try create new one.
2021-11-23 00:33:07 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-23 06:02:56 - INFO - __main__.py - 37 - 21412 seconds before last successful new update, try create new one.
2021-11-23 06:03:40 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-23 08:02:41 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-23 08:19:07 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-23 14:01:57 - INFO - __main__.py - 37 - 22157 seconds before last successful new update, try create new one.
2021-11-23 14:15:55 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-23 14:15:55 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png.
2021-11-23 14:15:56 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-11-23 14:18:01 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-23 20:02:26 - INFO - __main__.py - 37 - 22229 seconds before last successful new update, try create new one.
2021-11-23 20:19:57 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-23 22:02:03 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-23 22:08:26 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/06/13/15/08/37/90523989_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-23 22:08:26 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/06/13/15/08/37/90523989_p0.jpg.
2021-11-23 22:08:27 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-11-23 22:12:50 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-24 04:02:40 - INFO - __main__.py - 37 - 22236 seconds before last successful new update, try create new one.
2021-11-24 04:03:17 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-24 10:02:00 - INFO - __main__.py - 37 - 22161 seconds before last successful new update, try create new one.
2021-11-24 10:02:22 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-24 16:03:19 - INFO - __main__.py - 37 - 22279 seconds before last successful new update, try create new one.
2021-11-24 16:18:18 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-24 22:02:03 - INFO - __main__.py - 37 - 22124 seconds before last successful new update, try create new one.
2021-11-24 22:18:36 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-25 00:15:54 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-25 00:32:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-25 06:03:58 - INFO - __main__.py - 37 - 21484 seconds before last successful new update, try create new one.
2021-11-25 06:04:24 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-25 12:05:32 - INFO - __main__.py - 37 - 22295 seconds before last successful new update, try create new one.
2021-11-25 12:16:19 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-25 14:02:00 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-25 14:18:24 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-25 20:02:15 - INFO - __main__.py - 37 - 22216 seconds before last successful new update, try create new one.
2021-11-25 20:13:03 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-26 02:19:45 - INFO - __main__.py - 37 - 23250 seconds before last successful new update, try create new one.
2021-11-26 02:34:47 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-26 08:02:37 - INFO - __main__.py - 37 - 21172 seconds before last successful new update, try create new one.
2021-11-26 08:03:28 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-26 14:01:53 - INFO - __main__.py - 37 - 22156 seconds before last successful new update, try create new one.
2021-11-26 14:02:20 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-26 20:02:11 - INFO - __main__.py - 37 - 22219 seconds before last successful new update, try create new one.
2021-11-26 20:17:49 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-27 02:20:51 - INFO - __main__.py - 37 - 23320 seconds before last successful new update, try create new one.
2021-11-27 02:39:10 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-27 08:02:46 - INFO - __main__.py - 37 - 21116 seconds before last successful new update, try create new one.
2021-11-27 08:03:14 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-27 14:01:51 - INFO - __main__.py - 37 - 22145 seconds before last successful new update, try create new one.
2021-11-27 14:02:17 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-27 20:02:00 - INFO - __main__.py - 37 - 22209 seconds before last successful new update, try create new one.
2021-11-27 20:10:24 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/06/13/00/00/07/90510982_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-27 20:10:24 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/06/13/00/00/07/90510982_p0.png.
2021-11-27 20:10:25 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-11-27 20:16:33 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:502
2021-11-27 20:16:34 - WARNING - base.py - 23 - Retry func _post_draw_image_upload 1 time.
2021-11-27 20:16:34 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:502
2021-11-27 20:16:35 - WARNING - base.py - 23 - Retry func _post_draw_image_upload 2 time.
2021-11-27 20:16:35 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:502
2021-11-27 20:16:36 - WARNING - base.py - 23 - Retry func _post_draw_image_upload 3 time.
2021-11-27 20:16:36 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:502
2021-11-27 20:16:37 - ERROR - base.py - 34 - All retries failed in func _post_draw_image_upload.
2021-11-27 20:16:37 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:502
2021-11-27 20:16:38 - WARNING - base.py - 23 - Retry func _post_draw_image_upload 1 time.
2021-11-27 20:16:38 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:502
2021-11-27 20:16:39 - WARNING - base.py - 23 - Retry func _post_draw_image_upload 2 time.
2021-11-27 20:16:40 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:502
2021-11-27 20:16:41 - WARNING - base.py - 23 - Retry func _post_draw_image_upload 3 time.
2021-11-27 20:16:41 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:502
2021-11-27 20:16:42 - ERROR - base.py - 34 - All retries failed in func _post_draw_image_upload.
2021-11-27 20:16:50 - ERROR - bilibili.py - 434 - Failed to upload all pictures.
2021-11-27 20:16:50 - ERROR - bot.py - 239 - Failed to create ranking dynamic.
2021-11-27 23:12:49 - INFO - __main__.py - 37 - 33659 seconds before last successful new update, try create new one.
2021-11-27 23:29:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-28 06:03:57 - INFO - __main__.py - 37 - 25268 seconds before last successful new update, try create new one.
2021-11-28 06:04:36 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-28 08:02:18 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-28 08:02:41 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-28 10:02:18 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-28 10:08:39 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-28 16:02:46 - INFO - __main__.py - 37 - 22228 seconds before last successful new update, try create new one.
2021-11-28 16:11:39 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-28 22:02:15 - INFO - __main__.py - 37 - 22169 seconds before last successful new update, try create new one.
2021-11-28 22:07:17 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/22/00/00/06/92161858_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-28 22:07:17 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/22/00/00/06/92161858_p0.png.
2021-11-28 22:07:18 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-11-28 22:17:04 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-28 22:17:04 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png.
2021-11-28 22:17:05 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-11-28 22:19:27 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-29 04:02:45 - INFO - __main__.py - 37 - 22231 seconds before last successful new update, try create new one.
2021-11-29 04:03:19 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-29 10:02:23 - INFO - __main__.py - 37 - 22179 seconds before last successful new update, try create new one.
2021-11-29 10:02:50 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-29 16:03:26 - INFO - __main__.py - 37 - 22264 seconds before last successful new update, try create new one.
2021-11-29 16:22:36 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-29 22:02:23 - INFO - __main__.py - 37 - 22138 seconds before last successful new update, try create new one.
2021-11-29 22:18:11 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-30 00:16:21 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-30 00:31:37 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-30 00:31:37 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png.
2021-11-30 00:31:38 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-11-30 00:34:15 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-30 06:02:07 - INFO - __main__.py - 37 - 21347 seconds before last successful new update, try create new one.
2021-11-30 06:02:42 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-30 08:02:22 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-30 08:12:32 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-30 14:01:59 - INFO - __main__.py - 37 - 22177 seconds before last successful new update, try create new one.
2021-11-30 14:24:57 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-30 20:02:30 - INFO - __main__.py - 37 - 22232 seconds before last successful new update, try create new one.
2021-11-30 20:14:50 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-01 02:25:28 - INFO - __main__.py - 37 - 23578 seconds before last successful new update, try create new one.
2021-12-01 02:45:05 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-01 04:03:10 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-01 04:03:34 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-01 06:02:35 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-01 06:17:08 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-01 12:06:52 - INFO - __main__.py - 37 - 22457 seconds before last successful new update, try create new one.
2021-12-01 12:19:34 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-01 14:02:09 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-01 14:20:36 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-01 20:02:16 - INFO - __main__.py - 37 - 22208 seconds before last successful new update, try create new one.
2021-12-01 20:14:36 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-01 22:01:57 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-01 22:14:26 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-02 04:02:27 - INFO - __main__.py - 37 - 22231 seconds before last successful new update, try create new one.
2021-12-02 04:03:04 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-02 10:02:07 - INFO - __main__.py - 37 - 22180 seconds before last successful new update, try create new one.
2021-12-02 10:08:49 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/01/00/00/15/91634762_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:08:49 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/01/00/00/15/91634762_p0.jpg.
2021-12-02 10:08:50 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-02 10:16:02 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/24/00/10/35/89345687_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:02 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/24/00/10/35/89345687_p0.png.
2021-12-02 10:16:03 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-02 10:16:03 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/24/00/10/35/89345687_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:03 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/24/00/10/35/89345687_p0.png.
2021-12-02 10:16:04 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-12-02 10:16:05 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/24/00/10/35/89345687_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:05 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/24/00/10/35/89345687_p0.png.
2021-12-02 10:16:06 - WARNING - base.py - 23 - Retry func _get_page 3 time.
2021-12-02 10:16:06 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/24/00/10/35/89345687_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:06 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/24/00/10/35/89345687_p0.png.
2021-12-02 10:16:07 - ERROR - base.py - 34 - All retries failed in func _get_page.
2021-12-02 10:16:07 - ERROR - pixiv.py - 382 - Failed to download page https://i.pximg.net/img-original/img/2021/04/24/00/10/35/89345687_p0.png.
2021-12-02 10:16:18 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:18 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-02 10:16:19 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-02 10:16:19 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:19 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-02 10:16:20 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-12-02 10:16:21 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:21 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-02 10:16:22 - WARNING - base.py - 23 - Retry func _get_page 3 time.
2021-12-02 10:16:22 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:22 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-02 10:16:23 - ERROR - base.py - 34 - All retries failed in func _get_page.
2021-12-02 10:16:23 - ERROR - pixiv.py - 382 - Failed to download page https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-02 10:16:27 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:27 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-02 10:16:28 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-02 10:16:29 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:29 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-02 10:16:30 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-12-02 10:16:30 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:30 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-02 10:16:31 - WARNING - base.py - 23 - Retry func _get_page 3 time.
2021-12-02 10:16:32 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:32 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-02 10:16:33 - ERROR - base.py - 34 - All retries failed in func _get_page.
2021-12-02 10:16:33 - ERROR - pixiv.py - 382 - Failed to download page https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-02 10:16:33 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:33 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png.
2021-12-02 10:16:34 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-02 10:16:35 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:35 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png.
2021-12-02 10:16:36 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-12-02 10:16:36 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:36 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png.
2021-12-02 10:16:37 - WARNING - base.py - 23 - Retry func _get_page 3 time.
2021-12-02 10:16:38 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:38 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png.
2021-12-02 10:16:39 - ERROR - base.py - 34 - All retries failed in func _get_page.
2021-12-02 10:16:39 - ERROR - pixiv.py - 382 - Failed to download page https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png.
2021-12-02 10:16:45 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:45 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-02 10:16:46 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-02 10:16:47 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:47 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-02 10:16:48 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-12-02 10:16:48 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:48 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-02 10:16:49 - WARNING - base.py - 23 - Retry func _get_page 3 time.
2021-12-02 10:16:49 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:49 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-02 10:16:50 - ERROR - base.py - 34 - All retries failed in func _get_page.
2021-12-02 10:16:50 - ERROR - pixiv.py - 382 - Failed to download page https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-02 10:16:51 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:51 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png.
2021-12-02 10:16:52 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-02 10:16:52 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:52 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png.
2021-12-02 10:16:53 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-12-02 10:16:54 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:54 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png.
2021-12-02 10:16:55 - WARNING - base.py - 23 - Retry func _get_page 3 time.
2021-12-02 10:16:55 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:55 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png.
2021-12-02 10:16:56 - ERROR - base.py - 34 - All retries failed in func _get_page.
2021-12-02 10:16:56 - ERROR - pixiv.py - 382 - Failed to download page https://i.pximg.net/img-original/img/2021/04/18/00/00/04/89217834_p0.png.
2021-12-02 10:16:57 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/17/00/03/38/89193621_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:57 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/17/00/03/38/89193621_p0.jpg.
2021-12-02 10:16:58 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-02 10:16:58 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/17/00/03/38/89193621_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:16:58 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/17/00/03/38/89193621_p0.jpg.
2021-12-02 10:16:59 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-12-02 10:17:00 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/17/00/03/38/89193621_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:17:00 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/17/00/03/38/89193621_p0.jpg.
2021-12-02 10:17:01 - WARNING - base.py - 23 - Retry func _get_page 3 time.
2021-12-02 10:17:57 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/01/22/43/21/88862794_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 10:17:57 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/01/22/43/21/88862794_p0.png.
2021-12-02 10:17:58 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-02 10:20:05 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-02 16:03:32 - INFO - __main__.py - 37 - 22285 seconds before last successful new update, try create new one.
2021-12-02 16:23:03 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-02 22:02:12 - INFO - __main__.py - 37 - 22120 seconds before last successful new update, try create new one.
2021-12-02 22:07:52 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-02 22:07:52 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg.
2021-12-02 22:07:53 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-02 22:18:02 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-03 04:03:12 - INFO - __main__.py - 37 - 22260 seconds before last successful new update, try create new one.
2021-12-03 04:15:08 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-03 10:02:15 - INFO - __main__.py - 37 - 22144 seconds before last successful new update, try create new one.
2021-12-03 10:03:06 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-03 16:03:21 - INFO - __main__.py - 37 - 22267 seconds before last successful new update, try create new one.
2021-12-03 16:03:51 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-03 22:02:07 - INFO - __main__.py - 37 - 22126 seconds before last successful new update, try create new one.
2021-12-03 22:14:10 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-04 00:16:30 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-04 00:33:32 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-04 06:02:45 - INFO - __main__.py - 37 - 21375 seconds before last successful new update, try create new one.
2021-12-04 06:03:20 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-04 12:04:56 - INFO - __main__.py - 37 - 22332 seconds before last successful new update, try create new one.
2021-12-04 12:05:25 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-04 18:02:56 - INFO - __main__.py - 37 - 22080 seconds before last successful new update, try create new one.
2021-12-04 18:11:41 - WARNING - base.py - 65 - https://www.pixiv.net/ajax/illust/91247177:502
2021-12-04 18:11:41 - ERROR - pixiv.py - 58 - https://www.pixiv.net/ajax/illust/91247177:JsonValueError.
2021-12-04 18:11:42 - WARNING - base.py - 23 - Retry func _get_illust 1 time.
2021-12-04 18:21:31 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-05 00:17:53 - INFO - __main__.py - 37 - 23097 seconds before last successful new update, try create new one.
2021-12-05 00:37:15 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-05 06:02:56 - INFO - __main__.py - 37 - 21304 seconds before last successful new update, try create new one.
2021-12-05 06:03:29 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-05 12:03:48 - INFO - __main__.py - 37 - 22252 seconds before last successful new update, try create new one.
2021-12-05 12:22:26 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-05 18:02:40 - INFO - __main__.py - 37 - 22133 seconds before last successful new update, try create new one.
2021-12-05 18:05:28 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/16/00/07/08/92014228_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-05 18:05:28 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/16/00/07/08/92014228_p0.jpg.
2021-12-05 18:05:29 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-05 18:12:51 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-06 00:16:58 - INFO - __main__.py - 37 - 23058 seconds before last successful new update, try create new one.
2021-12-06 00:36:30 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-06 06:03:29 - INFO - __main__.py - 37 - 21392 seconds before last successful new update, try create new one.
2021-12-06 06:04:04 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-06 12:07:10 - INFO - __main__.py - 37 - 22420 seconds before last successful new update, try create new one.
2021-12-06 12:07:51 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-06 18:02:10 - INFO - __main__.py - 37 - 21901 seconds before last successful new update, try create new one.
2021-12-06 18:08:09 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-07 00:17:00 - INFO - __main__.py - 37 - 23091 seconds before last successful new update, try create new one.
2021-12-07 00:23:58 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-07 02:28:07 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-07 02:44:27 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-07 04:03:31 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-07 04:04:02 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-07 10:02:58 - INFO - __main__.py - 37 - 22168 seconds before last successful new update, try create new one.
2021-12-07 10:03:23 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-07 16:04:01 - INFO - __main__.py - 37 - 22264 seconds before last successful new update, try create new one.
2021-12-07 16:22:17 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-07 22:02:09 - INFO - __main__.py - 37 - 22088 seconds before last successful new update, try create new one.
2021-12-07 22:20:12 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/02/17/03/22/31/87837671_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-07 22:20:12 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/02/17/03/22/31/87837671_p0.jpg.
2021-12-07 22:20:13 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-07 22:20:43 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-08 04:02:59 - INFO - __main__.py - 37 - 22250 seconds before last successful new update, try create new one.
2021-12-08 04:03:30 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-08 10:02:35 - INFO - __main__.py - 37 - 22176 seconds before last successful new update, try create new one.
2021-12-08 10:03:05 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-08 16:02:42 - INFO - __main__.py - 37 - 22207 seconds before last successful new update, try create new one.
2021-12-08 16:18:56 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-08 22:02:01 - INFO - __main__.py - 37 - 22160 seconds before last successful new update, try create new one.
2021-12-08 22:20:54 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-09 04:03:07 - INFO - __main__.py - 37 - 22265 seconds before last successful new update, try create new one.
2021-12-09 04:11:23 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-09 10:02:24 - INFO - __main__.py - 37 - 22157 seconds before last successful new update, try create new one.
2021-12-09 10:03:13 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-09 16:04:00 - INFO - __main__.py - 37 - 22296 seconds before last successful new update, try create new one.
2021-12-09 16:15:30 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-09 18:02:59 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-09 18:14:28 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-09 20:02:17 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-09 20:15:16 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-10 02:20:44 - INFO - __main__.py - 37 - 23308 seconds before last successful new update, try create new one.
2021-12-10 02:32:49 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/02/14/00/12/33/87746715_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-10 02:32:49 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/02/14/00/12/33/87746715_p0.jpg.
2021-12-10 02:32:50 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-10 02:33:08 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-10 04:02:41 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-10 04:03:16 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-10 06:03:44 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-10 06:04:10 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-10 12:05:19 - INFO - __main__.py - 37 - 22294 seconds before last successful new update, try create new one.
2021-12-10 12:14:09 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/16/00/00/13/89864502_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-10 12:14:09 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/16/00/00/13/89864502_p0.png.
2021-12-10 12:14:10 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-10 12:19:04 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-10 18:02:40 - INFO - __main__.py - 37 - 22042 seconds before last successful new update, try create new one.
2021-12-10 18:20:46 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-11 00:15:20 - INFO - __main__.py - 37 - 22960 seconds before last successful new update, try create new one.
2021-12-11 00:29:09 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-11 06:03:07 - INFO - __main__.py - 37 - 21467 seconds before last successful new update, try create new one.
2021-12-11 06:03:35 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-11 12:04:42 - INFO - __main__.py - 37 - 22296 seconds before last successful new update, try create new one.
2021-12-11 12:09:52 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/22/00/00/06/92161858_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-11 12:09:52 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/22/00/00/06/92161858_p0.png.
2021-12-11 12:09:53 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-11 12:22:01 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-11 18:02:27 - INFO - __main__.py - 37 - 22066 seconds before last successful new update, try create new one.
2021-12-11 18:16:22 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-12 00:18:02 - INFO - __main__.py - 37 - 23134 seconds before last successful new update, try create new one.
2021-12-12 00:20:53 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/27/18/21/23/93058710_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-12 00:20:53 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/27/18/21/23/93058710_p0.jpg.
2021-12-12 00:20:54 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-12 00:34:31 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-12 06:02:29 - INFO - __main__.py - 37 - 21268 seconds before last successful new update, try create new one.
2021-12-12 06:03:00 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-12 12:04:16 - INFO - __main__.py - 37 - 22307 seconds before last successful new update, try create new one.
2021-12-12 12:04:42 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-12 14:02:20 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-12 14:08:50 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-12 16:03:16 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-12 16:10:36 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/05/23/13/46/91751463_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-12 16:10:36 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/05/23/13/46/91751463_p0.png.
2021-12-12 16:10:37 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-12 16:21:40 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-12 18:02:23 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-12 18:15:48 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-13 00:16:46 - INFO - __main__.py - 37 - 23062 seconds before last successful new update, try create new one.
2021-12-13 00:34:28 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-13 02:23:54 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-13 02:36:51 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-13 08:02:40 - INFO - __main__.py - 37 - 20926 seconds before last successful new update, try create new one.
2021-12-13 08:03:13 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-13 14:02:28 - INFO - __main__.py - 37 - 22189 seconds before last successful new update, try create new one.
2021-12-13 14:02:53 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-13 20:02:30 - INFO - __main__.py - 37 - 22203 seconds before last successful new update, try create new one.
2021-12-13 20:19:23 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-14 02:25:46 - INFO - __main__.py - 37 - 23597 seconds before last successful new update, try create new one.
2021-12-14 02:42:37 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-14 08:05:12 - INFO - __main__.py - 37 - 20967 seconds before last successful new update, try create new one.
2021-12-14 08:05:43 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-14 10:02:30 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-14 10:16:34 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-14 16:03:58 - INFO - __main__.py - 37 - 22288 seconds before last successful new update, try create new one.
2021-12-14 16:09:26 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/27/00/00/04/92283526_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-14 16:09:26 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/27/00/00/04/92283526_p0.jpg.
2021-12-14 16:09:27 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-14 16:18:58 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-14 16:18:58 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-14 16:18:59 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-14 16:24:15 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-14 22:02:08 - INFO - __main__.py - 37 - 22090 seconds before last successful new update, try create new one.
2021-12-14 22:20:32 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-15 04:02:41 - INFO - __main__.py - 37 - 22234 seconds before last successful new update, try create new one.
2021-12-15 04:03:15 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-15 10:03:04 - INFO - __main__.py - 37 - 22222 seconds before last successful new update, try create new one.
2021-12-15 10:04:45 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-15 16:03:37 - INFO - __main__.py - 37 - 22233 seconds before last successful new update, try create new one.
2021-12-15 16:08:21 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/03/20/02/01/92456455_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-15 16:08:21 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/03/20/02/01/92456455_p0.jpg.
2021-12-15 16:08:22 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-15 16:13:39 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-15 18:02:40 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-15 18:20:01 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-16 00:16:13 - INFO - __main__.py - 37 - 23012 seconds before last successful new update, try create new one.
2021-12-16 00:21:33 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/27/00/00/04/92283526_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-16 00:21:33 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/27/00/00/04/92283526_p0.jpg.
2021-12-16 00:21:34 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-16 00:34:09 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-16 02:22:53 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-16 02:39:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-16 04:02:34 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-16 04:02:57 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-16 10:02:01 - INFO - __main__.py - 37 - 22168 seconds before last successful new update, try create new one.
2021-12-16 10:02:25 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/11/13/12/29/34/94101036_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-16 10:02:25 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/11/13/12/29/34/94101036_p0.png.
2021-12-16 10:02:26 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-16 10:08:07 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/27/00/00/04/92283526_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-16 10:08:07 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/27/00/00/04/92283526_p0.jpg.
2021-12-16 10:08:08 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-16 10:23:04 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-16 16:03:51 - INFO - __main__.py - 37 - 22311 seconds before last successful new update, try create new one.
2021-12-16 16:14:56 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-16 22:02:03 - INFO - __main__.py - 37 - 22092 seconds before last successful new update, try create new one.
2021-12-16 22:18:02 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-17 04:03:04 - INFO - __main__.py - 37 - 22262 seconds before last successful new update, try create new one.
2021-12-17 04:03:27 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-17 10:02:12 - INFO - __main__.py - 37 - 22149 seconds before last successful new update, try create new one.
2021-12-17 10:02:38 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-17 12:06:43 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-17 12:16:23 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/29/00/00/08/90158416_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-17 12:16:23 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/29/00/00/08/90158416_p0.jpg.
2021-12-17 12:16:24 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-17 12:21:44 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-17 18:02:58 - INFO - __main__.py - 37 - 21976 seconds before last successful new update, try create new one.
2021-12-17 18:11:19 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-17 18:11:19 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg.
2021-12-17 18:11:20 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-17 18:12:09 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/30/00/00/12/91587582_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-17 18:12:09 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/30/00/00/12/91587582_p0.png.
2021-12-17 18:12:10 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-17 18:22:05 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-18 00:16:57 - INFO - __main__.py - 37 - 23039 seconds before last successful new update, try create new one.
2021-12-18 00:35:07 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-18 06:02:48 - INFO - __main__.py - 37 - 21352 seconds before last successful new update, try create new one.
2021-12-18 06:03:19 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-18 12:03:43 - INFO - __main__.py - 37 - 22256 seconds before last successful new update, try create new one.
2021-12-18 12:09:10 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-18 18:02:56 - INFO - __main__.py - 37 - 22154 seconds before last successful new update, try create new one.
2021-12-18 18:10:30 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-19 00:18:34 - INFO - __main__.py - 37 - 23138 seconds before last successful new update, try create new one.
2021-12-19 00:27:24 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-19 06:02:33 - INFO - __main__.py - 37 - 21239 seconds before last successful new update, try create new one.
2021-12-19 06:03:04 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-19 08:02:55 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-19 08:11:05 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-19 14:02:12 - INFO - __main__.py - 37 - 22157 seconds before last successful new update, try create new one.
2021-12-19 14:09:44 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/06/13/15/08/37/90523989_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-19 14:09:44 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/06/13/15/08/37/90523989_p0.jpg.
2021-12-19 14:09:45 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-19 14:10:22 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/29/00/00/08/90158416_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-19 14:10:22 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/29/00/00/08/90158416_p0.jpg.
2021-12-19 14:10:23 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-19 14:15:35 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-19 20:02:12 - INFO - __main__.py - 37 - 22200 seconds before last successful new update, try create new one.
2021-12-19 20:19:21 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-20 02:27:24 - INFO - __main__.py - 37 - 23713 seconds before last successful new update, try create new one.
2021-12-20 02:40:30 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-20 08:03:18 - INFO - __main__.py - 37 - 20753 seconds before last successful new update, try create new one.
2021-12-20 08:03:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-20 14:02:19 - INFO - __main__.py - 37 - 22141 seconds before last successful new update, try create new one.
2021-12-20 14:12:59 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/16/00/00/13/89864502_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-20 14:12:59 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/16/00/00/13/89864502_p0.png.
2021-12-20 14:13:00 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-20 14:18:17 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-20 20:02:21 - INFO - __main__.py - 37 - 22202 seconds before last successful new update, try create new one.
2021-12-20 20:19:41 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-21 02:28:37 - INFO - __main__.py - 37 - 23776 seconds before last successful new update, try create new one.
2021-12-21 02:37:54 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/21/20/42/52/89993524_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-21 02:37:54 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/21/20/42/52/89993524_p0.jpg.
2021-12-21 02:37:55 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-21 02:42:36 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-21 04:03:05 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-21 04:03:41 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-21 10:02:59 - INFO - __main__.py - 37 - 22194 seconds before last successful new update, try create new one.
2021-12-21 10:03:30 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/11/17/00/00/03/94181219_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-21 10:03:30 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/11/17/00/00/03/94181219_p0.jpg.
2021-12-21 10:03:31 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-21 10:15:39 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/27/20/24/43/90132257_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-21 10:15:39 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/27/20/24/43/90132257_p0.png.
2021-12-21 10:15:40 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-21 10:22:14 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-21 16:03:48 - INFO - __main__.py - 37 - 22249 seconds before last successful new update, try create new one.
2021-12-21 16:20:42 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-21 22:02:25 - INFO - __main__.py - 37 - 22118 seconds before last successful new update, try create new one.
2021-12-21 22:17:20 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-22 04:03:27 - INFO - __main__.py - 37 - 22263 seconds before last successful new update, try create new one.
2021-12-22 04:04:07 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-22 10:02:43 - INFO - __main__.py - 37 - 22157 seconds before last successful new update, try create new one.
2021-12-22 10:20:15 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-22 16:03:51 - INFO - __main__.py - 37 - 22269 seconds before last successful new update, try create new one.
2021-12-22 16:16:17 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/16/00/00/13/89864502_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-22 16:16:17 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/16/00/00/13/89864502_p0.png.
2021-12-22 16:16:18 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-22 16:22:33 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-22 22:02:10 - INFO - __main__.py - 37 - 22099 seconds before last successful new update, try create new one.
2021-12-22 22:19:11 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-23 04:03:27 - INFO - __main__.py - 37 - 22278 seconds before last successful new update, try create new one.
2021-12-23 04:17:17 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-23 10:02:10 - INFO - __main__.py - 37 - 22124 seconds before last successful new update, try create new one.
2021-12-23 10:02:44 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-23 16:03:29 - INFO - __main__.py - 37 - 22280 seconds before last successful new update, try create new one.
2021-12-23 16:23:41 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-23 18:02:49 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-23 18:16:37 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/29/00/00/08/90158416_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-23 18:16:37 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/29/00/00/08/90158416_p0.jpg.
2021-12-23 18:16:38 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-23 18:23:03 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-24 00:17:09 - INFO - __main__.py - 37 - 23061 seconds before last successful new update, try create new one.
2021-12-24 00:25:50 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/03/00/00/06/90966760_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-24 00:25:50 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/03/00/00/06/90966760_p0.jpg.
2021-12-24 00:25:51 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-24 00:35:08 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-24 06:03:28 - INFO - __main__.py - 37 - 21379 seconds before last successful new update, try create new one.
2021-12-24 06:04:06 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-24 12:03:55 - INFO - __main__.py - 37 - 22228 seconds before last successful new update, try create new one.
2021-12-24 12:24:41 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-24 18:02:33 - INFO - __main__.py - 37 - 22119 seconds before last successful new update, try create new one.
2021-12-24 18:08:36 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/27/00/00/04/92283526_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-24 18:08:36 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/27/00/00/04/92283526_p0.jpg.
2021-12-24 18:08:37 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-24 18:21:58 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-25 00:16:52 - INFO - __main__.py - 37 - 23060 seconds before last successful new update, try create new one.
2021-12-25 00:25:36 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/05/19/34/44/91035045_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-25 00:25:36 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/05/19/34/44/91035045_p0.png.
2021-12-25 00:25:37 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-25 00:34:24 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-25 06:03:07 - INFO - __main__.py - 37 - 21376 seconds before last successful new update, try create new one.
2021-12-25 06:03:41 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-25 08:02:59 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-25 08:09:11 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-25 10:02:09 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-25 10:07:51 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/22/00/00/06/92161858_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-25 10:07:51 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/22/00/00/06/92161858_p0.png.
2021-12-25 10:07:52 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-25 10:19:59 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-25 16:03:08 - INFO - __main__.py - 37 - 22259 seconds before last successful new update, try create new one.
2021-12-25 16:20:48 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-25 22:02:14 - INFO - __main__.py - 37 - 22145 seconds before last successful new update, try create new one.
2021-12-25 22:15:20 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-26 00:19:22 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-26 00:39:36 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-26 02:29:59 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-26 02:46:29 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-26 08:03:05 - INFO - __main__.py - 37 - 20585 seconds before last successful new update, try create new one.
2021-12-26 08:11:05 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-26 08:11:05 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg.
2021-12-26 08:11:06 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-26 08:13:23 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/03/00/00/06/90966760_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-26 08:13:23 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/03/00/00/06/90966760_p0.jpg.
2021-12-26 08:13:24 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-26 08:22:10 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-26 14:02:49 - INFO - __main__.py - 37 - 22184 seconds before last successful new update, try create new one.
2021-12-26 14:20:45 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-26 20:02:10 - INFO - __main__.py - 37 - 22162 seconds before last successful new update, try create new one.
2021-12-26 20:06:30 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/06/00/00/06/92540677_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-26 20:06:30 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/06/00/00/06/92540677_p0.jpg.
2021-12-26 20:06:31 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-26 20:17:26 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-27 02:26:42 - INFO - __main__.py - 37 - 23672 seconds before last successful new update, try create new one.
2021-12-27 02:28:13 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/11/04/00/00/02/93901392_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-27 02:28:13 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/11/04/00/00/02/93901392_p0.png.
2021-12-27 02:28:14 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-27 02:37:28 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-27 08:05:27 - INFO - __main__.py - 37 - 20926 seconds before last successful new update, try create new one.
2021-12-27 08:05:54 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-27 14:11:55 - INFO - __main__.py - 37 - 22589 seconds before last successful new update, try create new one.
2021-12-27 14:25:44 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-27 16:12:21 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-27 16:30:54 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-27 22:02:21 - INFO - __main__.py - 37 - 21600 seconds before last successful new update, try create new one.
2021-12-27 22:21:07 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-28 04:03:16 - INFO - __main__.py - 37 - 22255 seconds before last successful new update, try create new one.
2021-12-28 04:03:48 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-28 10:02:15 - INFO - __main__.py - 37 - 22140 seconds before last successful new update, try create new one.
2021-12-28 10:02:40 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-28 16:04:02 - INFO - __main__.py - 37 - 22308 seconds before last successful new update, try create new one.
2021-12-28 16:23:50 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-28 22:02:16 - INFO - __main__.py - 37 - 22093 seconds before last successful new update, try create new one.
2021-12-28 22:21:54 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-29 00:17:08 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-29 00:30:41 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-29 06:04:07 - INFO - __main__.py - 37 - 21419 seconds before last successful new update, try create new one.
2021-12-29 06:04:44 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-29 12:07:12 - INFO - __main__.py - 37 - 22385 seconds before last successful new update, try create new one.
2021-12-29 12:28:58 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-29 18:02:44 - INFO - __main__.py - 37 - 21932 seconds before last successful new update, try create new one.
2021-12-29 18:22:30 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-29 20:02:21 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-29 20:20:19 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-29 22:02:21 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-29 22:17:34 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-29 22:17:34 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-29 22:17:35 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-29 22:23:42 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-30 00:17:26 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-30 00:36:13 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-30 06:03:11 - INFO - __main__.py - 37 - 21346 seconds before last successful new update, try create new one.
2021-12-30 06:03:43 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-30 12:07:16 - INFO - __main__.py - 37 - 22445 seconds before last successful new update, try create new one.
2021-12-30 12:07:47 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-30 18:02:34 - INFO - __main__.py - 37 - 21919 seconds before last successful new update, try create new one.
2021-12-30 18:12:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-30 20:02:17 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-30 20:17:18 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-30 20:17:18 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/18/00/01/33/89218035_p0.png.
2021-12-30 20:17:19 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-30 20:18:25 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-30 20:18:25 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png.
2021-12-30 20:18:26 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-30 20:22:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-31 02:28:44 - INFO - __main__.py - 37 - 23786 seconds before last successful new update, try create new one.
2021-12-31 02:46:34 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-31 04:03:10 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-31 04:13:52 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/31/19/34/47/90228374_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-31 04:13:52 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/31/19/34/47/90228374_p0.png.
2021-12-31 04:13:53 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-31 04:14:06 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/27/20/24/43/90132257_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-31 04:14:06 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/27/20/24/43/90132257_p0.png.
2021-12-31 04:14:07 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-31 04:14:20 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/26/00/00/08/90097063_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-31 04:14:20 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/26/00/00/08/90097063_p0.png.
2021-12-31 04:14:21 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-31 04:21:00 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-31 06:03:11 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-31 06:03:38 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-31 12:06:58 - INFO - __main__.py - 37 - 22428 seconds before last successful new update, try create new one.
2021-12-31 12:20:22 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-31 14:02:07 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-31 14:21:35 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-31 16:03:38 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-31 16:23:44 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-31 22:02:18 - INFO - __main__.py - 37 - 22119 seconds before last successful new update, try create new one.
2021-12-31 22:13:39 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/27/20/24/43/90132257_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-31 22:13:39 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/27/20/24/43/90132257_p0.png.
2021-12-31 22:13:40 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-12-31 22:20:00 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-01 00:18:09 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-01 00:39:30 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-01 06:03:23 - INFO - __main__.py - 37 - 21314 seconds before last successful new update, try create new one.
2022-01-01 06:04:02 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-01 12:06:27 - INFO - __main__.py - 37 - 22385 seconds before last successful new update, try create new one.
2022-01-01 12:07:06 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-01 18:02:41 - INFO - __main__.py - 37 - 21974 seconds before last successful new update, try create new one.
2022-01-01 18:21:52 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-02 00:18:27 - INFO - __main__.py - 37 - 23147 seconds before last successful new update, try create new one.
2022-01-02 00:36:44 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-02 06:02:39 - INFO - __main__.py - 37 - 21253 seconds before last successful new update, try create new one.
2022-01-02 06:03:27 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-02 12:05:19 - INFO - __main__.py - 37 - 22360 seconds before last successful new update, try create new one.
2022-01-02 12:05:49 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-02 18:02:37 - INFO - __main__.py - 37 - 22039 seconds before last successful new update, try create new one.
2022-01-02 18:25:49 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-03 00:17:49 - INFO - __main__.py - 37 - 23112 seconds before last successful new update, try create new one.
2022-01-03 00:31:45 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-03 06:03:44 - INFO - __main__.py - 37 - 21355 seconds before last successful new update, try create new one.
2022-01-03 06:04:14 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-03 08:03:56 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-03 08:04:27 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/11/23/00/03/17/94309473_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-03 08:04:27 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/11/23/00/03/17/94309473_p0.jpg.
2022-01-03 08:04:28 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-03 08:17:36 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-03 10:02:51 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-03 10:23:31 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-03 12:07:15 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-03 12:12:48 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/06/00/00/06/92540677_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-03 12:12:48 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/06/00/00/06/92540677_p0.jpg.
2022-01-03 12:12:49 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-03 12:17:35 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-03 18:03:13 - INFO - __main__.py - 37 - 21957 seconds before last successful new update, try create new one.
2022-01-03 18:12:45 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-04 00:17:25 - INFO - __main__.py - 37 - 23053 seconds before last successful new update, try create new one.
2022-01-04 00:31:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-04 06:03:50 - INFO - __main__.py - 37 - 21386 seconds before last successful new update, try create new one.
2022-01-04 06:04:28 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-04 12:07:09 - INFO - __main__.py - 37 - 22399 seconds before last successful new update, try create new one.
2022-01-04 12:17:06 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/03/00/00/06/90966760_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-04 12:17:06 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/03/00/00/06/90966760_p0.jpg.
2022-01-04 12:17:07 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-04 12:26:59 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-04 18:02:40 - INFO - __main__.py - 37 - 21932 seconds before last successful new update, try create new one.
2022-01-04 18:21:33 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-05 00:19:06 - INFO - __main__.py - 37 - 23186 seconds before last successful new update, try create new one.
2022-01-05 00:38:06 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-05 06:04:22 - INFO - __main__.py - 37 - 21317 seconds before last successful new update, try create new one.
2022-01-05 06:05:05 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-05 12:07:19 - INFO - __main__.py - 37 - 22378 seconds before last successful new update, try create new one.
2022-01-05 12:26:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-05 18:03:08 - INFO - __main__.py - 37 - 21950 seconds before last successful new update, try create new one.
2022-01-05 18:09:23 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/22/00/00/06/92161858_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-05 18:09:23 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/22/00/00/06/92161858_p0.png.
2022-01-05 18:09:24 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-05 18:22:15 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-05 20:01:42 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-01-06 00:18:41 - INFO - __main__.py - 37 - 23133 seconds before last successful new update, try create new one.
2022-01-06 00:36:18 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-06 06:03:23 - INFO - __main__.py - 37 - 21282 seconds before last successful new update, try create new one.
2022-01-06 06:04:05 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-06 12:07:43 - INFO - __main__.py - 37 - 22461 seconds before last successful new update, try create new one.
2022-01-06 12:13:56 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/27/00/00/04/92283526_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-06 12:13:56 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/27/00/00/04/92283526_p0.jpg.
2022-01-06 12:13:57 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-06 12:18:11 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-06 18:03:10 - INFO - __main__.py - 37 - 21927 seconds before last successful new update, try create new one.
2022-01-06 18:04:36 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/11/22/00/00/09/94288120_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-06 18:04:36 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/11/22/00/00/09/94288120_p0.png.
2022-01-06 18:04:37 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-06 18:12:15 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-06 18:12:15 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg.
2022-01-06 18:12:16 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-06 18:17:59 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/16/00/00/13/89864502_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-06 18:17:59 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/16/00/00/13/89864502_p0.png.
2022-01-06 18:18:00 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-06 18:24:58 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-06 20:02:12 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-01-07 00:19:30 - INFO - __main__.py - 37 - 23180 seconds before last successful new update, try create new one.
2022-01-07 00:42:40 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-07 06:03:19 - INFO - __main__.py - 37 - 21229 seconds before last successful new update, try create new one.
2022-01-07 06:03:48 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-07 08:03:13 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-07 08:25:25 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-07 10:03:03 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-07 10:18:21 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-07 12:07:19 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-07 12:22:38 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-07 14:02:20 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-07 14:24:40 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-07 16:03:55 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-01-07 18:03:15 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-07 18:18:22 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-07 20:02:37 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-01-07 22:02:11 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-01-08 00:18:29 - INFO - __main__.py - 37 - 23114 seconds before last successful new update, try create new one.
2022-01-08 00:19:08 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/11/27/11/18/38/94400778_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-08 00:19:08 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/11/27/11/18/38/94400778_p0.png.
2022-01-08 00:19:09 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-08 00:41:58 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-08 02:30:41 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-08 02:49:28 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-08 04:03:05 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-08 04:20:11 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-08 10:02:13 - INFO - __main__.py - 37 - 22148 seconds before last successful new update, try create new one.
2022-01-08 10:02:49 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-08 12:05:50 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-08 12:06:19 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-08 18:02:48 - INFO - __main__.py - 37 - 22018 seconds before last successful new update, try create new one.
2022-01-08 18:22:42 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-09 00:18:58 - INFO - __main__.py - 37 - 23170 seconds before last successful new update, try create new one.
2022-01-09 00:28:42 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-09 00:28:42 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg.
2022-01-09 00:28:43 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-09 00:43:41 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-09 06:03:37 - INFO - __main__.py - 37 - 21280 seconds before last successful new update, try create new one.
2022-01-09 06:04:11 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-09 12:05:48 - INFO - __main__.py - 37 - 22331 seconds before last successful new update, try create new one.
2022-01-09 12:06:24 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-09 18:02:33 - INFO - __main__.py - 37 - 22006 seconds before last successful new update, try create new one.
2022-01-09 18:15:21 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-09 20:02:14 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-09 20:16:31 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-10 02:29:20 - INFO - __main__.py - 37 - 23827 seconds before last successful new update, try create new one.
2022-01-10 02:32:28 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/19/00/02/10/92843456_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-10 02:32:28 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/19/00/02/10/92843456_p0.png.
2022-01-10 02:32:29 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-10 02:37:50 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-10 08:03:57 - INFO - __main__.py - 37 - 20677 seconds before last successful new update, try create new one.
2022-01-10 08:05:56 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:504
2022-01-10 08:05:57 - WARNING - base.py - 23 - Retry func _post_draw_image_upload 1 time.
2022-01-10 08:06:03 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-10 14:02:14 - INFO - __main__.py - 37 - 22097 seconds before last successful new update, try create new one.
2022-01-10 14:13:00 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-10 20:02:20 - INFO - __main__.py - 37 - 22207 seconds before last successful new update, try create new one.
2022-01-10 20:16:29 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-11 02:29:34 - INFO - __main__.py - 37 - 23835 seconds before last successful new update, try create new one.
2022-01-11 02:43:23 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-11 08:04:08 - INFO - __main__.py - 37 - 20675 seconds before last successful new update, try create new one.
2022-01-11 08:04:43 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-11 14:02:24 - INFO - __main__.py - 37 - 22096 seconds before last successful new update, try create new one.
2022-01-11 14:03:01 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-11 16:04:24 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-01-11 18:02:40 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-11 18:24:39 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-11 20:02:52 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-01-12 00:19:09 - INFO - __main__.py - 37 - 23189 seconds before last successful new update, try create new one.
2022-01-12 00:27:49 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/06/01/07/19/91044278_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-12 00:27:49 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/06/01/07/19/91044278_p0.png.
2022-01-12 00:27:50 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-12 00:37:11 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-12 02:29:07 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-12 02:39:38 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/21/20/42/52/89993524_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-12 02:39:38 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/21/20/42/52/89993524_p0.jpg.
2022-01-12 02:39:39 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-12 02:46:12 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-12 08:03:32 - INFO - __main__.py - 37 - 20666 seconds before last successful new update, try create new one.
2022-01-12 08:04:11 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-12 14:02:10 - INFO - __main__.py - 37 - 22118 seconds before last successful new update, try create new one.
2022-01-12 14:23:56 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-12 20:02:11 - INFO - __main__.py - 37 - 22202 seconds before last successful new update, try create new one.
2022-01-12 20:21:03 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-13 02:31:32 - INFO - __main__.py - 37 - 23962 seconds before last successful new update, try create new one.
2022-01-13 02:35:49 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/16/00/07/08/92014228_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-13 02:35:49 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/16/00/07/08/92014228_p0.jpg.
2022-01-13 02:35:50 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-13 02:39:35 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/27/20/24/43/90132257_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-13 02:39:35 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/27/20/24/43/90132257_p0.png.
2022-01-13 02:39:36 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-13 02:45:53 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/create_draw:2003:error
2022-01-13 02:45:53 - ERROR - bilibili.py - 439 - Failed to create dynamic.
2022-01-13 02:45:53 - ERROR - bot.py - 239 - Failed to create ranking dynamic.
2022-01-13 04:03:41 - INFO - __main__.py - 37 - 29491 seconds before last successful new update, try create new one.
2022-01-13 04:04:11 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-13 10:02:31 - INFO - __main__.py - 37 - 22129 seconds before last successful new update, try create new one.
2022-01-13 10:24:30 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-13 16:04:02 - INFO - __main__.py - 37 - 22292 seconds before last successful new update, try create new one.
2022-01-13 16:26:22 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-13 22:02:20 - INFO - __main__.py - 37 - 22098 seconds before last successful new update, try create new one.
2022-01-13 22:07:19 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/27/00/00/14/93045075_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-13 22:07:19 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/27/00/00/14/93045075_p0.png.
2022-01-13 22:07:20 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-13 22:24:09 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-14 04:03:07 - INFO - __main__.py - 37 - 22247 seconds before last successful new update, try create new one.
2022-01-14 04:03:39 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-14 10:02:52 - INFO - __main__.py - 37 - 22185 seconds before last successful new update, try create new one.
2022-01-14 10:25:56 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-14 12:07:15 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-14 12:25:34 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-14 14:02:02 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-14 14:11:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-14 20:02:34 - INFO - __main__.py - 37 - 22232 seconds before last successful new update, try create new one.
2022-01-14 20:19:06 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-15 02:31:14 - INFO - __main__.py - 37 - 23920 seconds before last successful new update, try create new one.
2022-01-15 02:51:03 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-15 08:03:21 - INFO - __main__.py - 37 - 20528 seconds before last successful new update, try create new one.
2022-01-15 08:03:49 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-15 14:01:44 - INFO - __main__.py - 37 - 22103 seconds before last successful new update, try create new one.
2022-01-15 14:02:06 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-15 20:02:02 - INFO - __main__.py - 37 - 22219 seconds before last successful new update, try create new one.
2022-01-15 20:14:37 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/27/20/24/43/90132257_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-15 20:14:37 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/27/20/24/43/90132257_p0.png.
2022-01-15 20:14:38 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-15 20:22:15 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-16 02:32:28 - INFO - __main__.py - 37 - 24027 seconds before last successful new update, try create new one.
2022-01-16 02:42:08 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-16 02:42:08 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg.
2022-01-16 02:42:09 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-16 02:55:37 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-16 04:02:57 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-16 04:03:30 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-16 06:02:42 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-16 06:03:05 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-16 12:05:30 - INFO - __main__.py - 37 - 22367 seconds before last successful new update, try create new one.
2022-01-16 12:27:54 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-16 18:02:55 - INFO - __main__.py - 37 - 22046 seconds before last successful new update, try create new one.
2022-01-16 18:13:08 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-16 18:13:08 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg.
2022-01-16 18:13:09 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-16 18:26:30 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-16 20:02:22 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-16 20:07:04 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/27/00/00/14/93045075_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-16 20:07:04 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/27/00/00/14/93045075_p0.png.
2022-01-16 20:07:05 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-16 20:14:28 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/27/20/24/43/90132257_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-16 20:14:28 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/27/20/24/43/90132257_p0.png.
2022-01-16 20:14:29 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-16 20:22:59 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-16 22:02:15 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-16 22:17:42 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-17 04:04:02 - INFO - __main__.py - 37 - 22307 seconds before last successful new update, try create new one.
2022-01-17 04:04:27 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-17 10:02:29 - INFO - __main__.py - 37 - 22107 seconds before last successful new update, try create new one.
2022-01-17 10:02:53 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-17 12:07:30 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-17 12:08:32 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/11/27/11/18/38/94400778_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-17 12:08:32 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/11/27/11/18/38/94400778_p0.png.
2022-01-17 12:08:33 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-17 12:23:27 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-17 18:03:15 - INFO - __main__.py - 37 - 21945 seconds before last successful new update, try create new one.
2022-01-17 18:21:00 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-18 00:19:31 - INFO - __main__.py - 37 - 23177 seconds before last successful new update, try create new one.
2022-01-18 00:39:48 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/02/17/03/22/31/87837671_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-18 00:39:48 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/02/17/03/22/31/87837671_p0.jpg.
2022-01-18 00:39:49 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-18 00:42:57 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-18 06:03:52 - INFO - __main__.py - 37 - 21261 seconds before last successful new update, try create new one.
2022-01-18 06:04:25 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-18 08:04:42 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-18 08:05:18 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-18 14:02:05 - INFO - __main__.py - 37 - 22044 seconds before last successful new update, try create new one.
2022-01-18 14:16:01 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-18 20:02:47 - INFO - __main__.py - 37 - 22243 seconds before last successful new update, try create new one.
2022-01-18 20:25:31 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-18 22:12:21 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-18 22:28:52 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-19 04:03:07 - INFO - __main__.py - 37 - 21646 seconds before last successful new update, try create new one.
2022-01-19 04:03:49 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-19 10:02:04 - INFO - __main__.py - 37 - 22138 seconds before last successful new update, try create new one.
2022-01-19 10:02:34 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-19 12:06:40 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-19 12:31:08 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-19 14:01:57 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-19 14:24:43 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-19 20:02:09 - INFO - __main__.py - 37 - 22213 seconds before last successful new update, try create new one.
2022-01-19 20:26:34 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-20 02:31:03 - INFO - __main__.py - 37 - 23935 seconds before last successful new update, try create new one.
2022-01-20 02:32:08 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/11/23/00/03/17/94309473_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-20 02:32:08 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/11/23/00/03/17/94309473_p0.jpg.
2022-01-20 02:32:09 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-20 02:46:12 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/create_draw:2003:error
2022-01-20 02:46:12 - ERROR - bilibili.py - 439 - Failed to create dynamic.
2022-01-20 02:46:12 - ERROR - bot.py - 239 - Failed to create ranking dynamic.
2022-01-20 04:02:25 - INFO - __main__.py - 37 - 29417 seconds before last successful new update, try create new one.
2022-01-20 04:05:51 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/19/00/02/10/92843456_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-20 04:05:51 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/19/00/02/10/92843456_p0.png.
2022-01-20 04:05:52 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-20 04:11:06 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/29/00/00/08/90158416_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-20 04:11:06 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/29/00/00/08/90158416_p0.jpg.
2022-01-20 04:11:07 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-20 04:11:31 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/26/00/00/08/90097063_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-20 04:11:31 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/26/00/00/08/90097063_p0.png.
2022-01-20 04:11:32 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-20 04:17:47 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-20 10:02:16 - INFO - __main__.py - 37 - 22192 seconds before last successful new update, try create new one.
2022-01-20 10:02:47 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-20 16:03:38 - INFO - __main__.py - 37 - 22283 seconds before last successful new update, try create new one.
2022-01-20 16:26:03 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-20 22:02:21 - INFO - __main__.py - 37 - 22124 seconds before last successful new update, try create new one.
2022-01-20 22:21:31 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-21 00:16:33 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-21 00:34:06 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-21 06:06:48 - INFO - __main__.py - 37 - 21616 seconds before last successful new update, try create new one.
2022-01-21 06:07:13 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-21 12:07:13 - INFO - __main__.py - 37 - 22224 seconds before last successful new update, try create new one.
2022-01-21 12:07:38 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/create_draw:2003:error
2022-01-21 12:07:38 - ERROR - bilibili.py - 439 - Failed to create dynamic.
2022-01-21 12:07:38 - ERROR - bot.py - 239 - Failed to create ranking dynamic.
2022-01-21 14:02:02 - INFO - __main__.py - 37 - 29114 seconds before last successful new update, try create new one.
2022-01-21 14:02:25 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-21 16:03:19 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-21 16:21:27 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-21 18:02:34 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-21 18:03:54 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/11/27/11/18/38/94400778_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-21 18:03:54 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/11/27/11/18/38/94400778_p0.png.
2022-01-21 18:03:55 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-21 18:08:34 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/03/20/02/01/92456455_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-21 18:08:34 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/03/20/02/01/92456455_p0.jpg.
2022-01-21 18:08:35 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-21 18:12:15 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-22 00:17:55 - INFO - __main__.py - 37 - 23121 seconds before last successful new update, try create new one.
2022-01-22 00:29:48 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-22 06:02:33 - INFO - __main__.py - 37 - 21279 seconds before last successful new update, try create new one.
2022-01-22 06:03:07 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-22 12:04:56 - INFO - __main__.py - 37 - 22343 seconds before last successful new update, try create new one.
2022-01-22 12:05:18 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-22 14:01:52 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-22 14:17:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-22 20:02:05 - INFO - __main__.py - 37 - 22213 seconds before last successful new update, try create new one.
2022-01-22 20:20:08 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2020/12/21/14/31/47/86435035_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-22 20:20:08 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2020/12/21/14/31/47/86435035_p0.jpg.
2022-01-22 20:20:09 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-22 20:20:40 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-23 02:18:15 - INFO - __main__.py - 37 - 23170 seconds before last successful new update, try create new one.
2022-01-23 02:38:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-23 08:02:25 - INFO - __main__.py - 37 - 21250 seconds before last successful new update, try create new one.
2022-01-23 08:02:51 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-23 14:01:49 - INFO - __main__.py - 37 - 22164 seconds before last successful new update, try create new one.
2022-01-23 14:03:15 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/11/27/11/18/38/94400778_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-23 14:03:15 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/11/27/11/18/38/94400778_p0.png.
2022-01-23 14:03:16 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-23 14:20:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-23 20:03:00 - INFO - __main__.py - 37 - 22273 seconds before last successful new update, try create new one.
2022-01-23 20:17:20 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-24 02:25:03 - INFO - __main__.py - 37 - 23524 seconds before last successful new update, try create new one.
2022-01-24 02:45:44 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-24 04:02:46 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-24 04:23:46 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-24 10:02:24 - INFO - __main__.py - 37 - 22179 seconds before last successful new update, try create new one.
2022-01-24 10:02:52 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-24 16:03:20 - INFO - __main__.py - 37 - 22256 seconds before last successful new update, try create new one.
2022-01-24 16:26:32 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-24 22:01:48 - INFO - __main__.py - 37 - 22109 seconds before last successful new update, try create new one.
2022-01-24 22:22:34 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-25 04:02:56 - INFO - __main__.py - 37 - 22268 seconds before last successful new update, try create new one.
2022-01-25 04:08:20 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/27/00/00/14/93045075_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-25 04:08:20 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/27/00/00/14/93045075_p0.png.
2022-01-25 04:08:21 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-25 04:21:30 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/02/17/03/22/31/87837671_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-25 04:21:30 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/02/17/03/22/31/87837671_p0.jpg.
2022-01-25 04:21:31 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-25 04:26:03 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:504
2022-01-25 04:26:04 - WARNING - base.py - 23 - Retry func _post_draw_image_upload 1 time.
2022-01-25 04:26:15 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-25 10:01:58 - INFO - __main__.py - 37 - 22142 seconds before last successful new update, try create new one.
2022-01-25 10:02:26 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-25 16:03:46 - INFO - __main__.py - 37 - 22308 seconds before last successful new update, try create new one.
2022-01-25 16:15:41 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-25 22:02:07 - INFO - __main__.py - 37 - 22102 seconds before last successful new update, try create new one.
2022-01-25 22:10:39 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-26 00:18:28 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-26 00:37:23 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-26 06:02:49 - INFO - __main__.py - 37 - 21262 seconds before last successful new update, try create new one.
2022-01-26 06:03:16 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-26 12:05:31 - INFO - __main__.py - 37 - 22362 seconds before last successful new update, try create new one.
2022-01-26 12:29:34 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-26 18:02:23 - INFO - __main__.py - 37 - 22013 seconds before last successful new update, try create new one.
2022-01-26 18:22:35 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-27 00:17:06 - INFO - __main__.py - 37 - 23083 seconds before last successful new update, try create new one.
2022-01-27 00:40:54 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-27 06:02:25 - INFO - __main__.py - 37 - 21320 seconds before last successful new update, try create new one.
2022-01-27 06:02:51 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-27 12:04:32 - INFO - __main__.py - 37 - 22328 seconds before last successful new update, try create new one.
2022-01-27 12:21:38 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2020/12/21/14/31/47/86435035_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-27 12:21:38 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2020/12/21/14/31/47/86435035_p0.jpg.
2022-01-27 12:21:39 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-27 12:22:18 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-27 18:02:39 - INFO - __main__.py - 37 - 22086 seconds before last successful new update, try create new one.
2022-01-27 18:27:13 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-27 20:01:41 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-27 20:18:22 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/02/17/03/22/31/87837671_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-27 20:18:22 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/02/17/03/22/31/87837671_p0.jpg.
2022-01-27 20:18:23 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-27 20:21:22 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/create_draw:2003:error
2022-01-27 20:21:22 - ERROR - bilibili.py - 439 - Failed to create dynamic.
2022-01-27 20:21:22 - ERROR - bot.py - 239 - Failed to create ranking dynamic.
2022-01-27 22:01:55 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-27 22:13:23 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/29/00/00/08/90158416_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-27 22:13:23 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/29/00/00/08/90158416_p0.jpg.
2022-01-27 22:13:24 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-27 22:14:17 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/16/00/00/13/89864502_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-27 22:14:17 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/16/00/00/13/89864502_p0.png.
2022-01-27 22:14:18 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-27 22:21:18 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-28 04:04:05 - INFO - __main__.py - 37 - 22330 seconds before last successful new update, try create new one.
2022-01-28 04:06:38 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/11/04/00/00/07/93901440_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-28 04:06:38 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/11/04/00/00/07/93901440_p0.png.
2022-01-28 04:06:39 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-28 04:23:07 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-28 10:02:13 - INFO - __main__.py - 37 - 22089 seconds before last successful new update, try create new one.
2022-01-28 10:02:40 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-28 16:03:09 - INFO - __main__.py - 37 - 22256 seconds before last successful new update, try create new one.
2022-01-28 16:13:03 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-28 22:01:56 - INFO - __main__.py - 37 - 22127 seconds before last successful new update, try create new one.
2022-01-28 22:10:39 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/27/00/00/04/92283526_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-28 22:10:39 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/27/00/00/04/92283526_p0.jpg.
2022-01-28 22:10:40 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-28 22:14:43 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-29 00:16:01 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-29 00:24:42 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/10/19/18/49/91147521_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-29 00:24:42 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/10/19/18/49/91147521_p0.jpg.
2022-01-29 00:24:43 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-29 00:34:23 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-29 06:02:40 - INFO - __main__.py - 37 - 21399 seconds before last successful new update, try create new one.
2022-01-29 06:03:31 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-29 12:04:19 - INFO - __main__.py - 37 - 22300 seconds before last successful new update, try create new one.
2022-01-29 12:04:50 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-29 18:03:47 - INFO - __main__.py - 37 - 22168 seconds before last successful new update, try create new one.
2022-01-29 18:18:19 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/26/00/00/08/90097063_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-29 18:18:19 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/26/00/00/08/90097063_p0.png.
2022-01-29 18:18:20 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-29 18:28:11 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-30 00:17:54 - INFO - __main__.py - 37 - 23047 seconds before last successful new update, try create new one.
2022-01-30 00:40:46 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-30 06:02:30 - INFO - __main__.py - 37 - 21276 seconds before last successful new update, try create new one.
2022-01-30 06:02:56 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-30 08:02:22 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-30 08:02:50 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-30 14:01:22 - INFO - __main__.py - 37 - 22140 seconds before last successful new update, try create new one.
2022-01-30 14:20:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-30 16:02:43 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-30 16:12:16 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/06/13/15/08/37/90523989_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-30 16:12:16 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/06/13/15/08/37/90523989_p0.jpg.
2022-01-30 16:12:17 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-30 16:20:31 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-30 18:01:55 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-30 18:25:44 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/create_draw:2003:error
2022-01-30 18:25:44 - ERROR - bilibili.py - 439 - Failed to create dynamic.
2022-01-30 18:25:44 - ERROR - bot.py - 239 - Failed to create ranking dynamic.
2022-01-30 20:01:58 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-01-30 20:18:38 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-31 02:17:43 - INFO - __main__.py - 37 - 23146 seconds before last successful new update, try create new one.
2022-01-31 02:29:13 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/30/00/00/12/91587582_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-31 02:29:13 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/30/00/00/12/91587582_p0.png.
2022-01-31 02:29:14 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-31 02:32:52 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/26/00/00/08/90097063_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-31 02:32:52 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/26/00/00/08/90097063_p0.png.
2022-01-31 02:32:53 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-31 02:42:04 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-31 08:02:56 - INFO - __main__.py - 37 - 21314 seconds before last successful new update, try create new one.
2022-01-31 08:03:32 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-31 14:02:02 - INFO - __main__.py - 37 - 22147 seconds before last successful new update, try create new one.
2022-01-31 14:02:22 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-01-31 20:02:20 - INFO - __main__.py - 37 - 22218 seconds before last successful new update, try create new one.
2022-01-31 20:08:59 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/22/00/00/06/92161858_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-01-31 20:08:59 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/22/00/00/06/92161858_p0.png.
2022-01-31 20:09:00 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-01-31 20:12:37 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-01 02:21:54 - INFO - __main__.py - 37 - 23374 seconds before last successful new update, try create new one.
2022-02-01 02:31:28 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-01 08:03:06 - INFO - __main__.py - 37 - 21073 seconds before last successful new update, try create new one.
2022-02-01 08:03:36 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-01 14:02:14 - INFO - __main__.py - 37 - 22148 seconds before last successful new update, try create new one.
2022-02-01 14:02:43 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-01 20:02:21 - INFO - __main__.py - 37 - 22208 seconds before last successful new update, try create new one.
2022-02-01 20:02:43 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-02 02:19:44 - INFO - __main__.py - 37 - 23243 seconds before last successful new update, try create new one.
2022-02-02 02:30:44 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/26/00/00/08/90097063_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-02 02:30:44 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/26/00/00/08/90097063_p0.png.
2022-02-02 02:30:45 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-02 02:38:33 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/create_draw:2003:error
2022-02-02 02:38:33 - ERROR - bilibili.py - 439 - Failed to create dynamic.
2022-02-02 02:38:33 - ERROR - bot.py - 239 - Failed to create ranking dynamic.
2022-02-02 04:02:28 - INFO - __main__.py - 37 - 29408 seconds before last successful new update, try create new one.
2022-02-02 04:02:53 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-02 10:03:09 - INFO - __main__.py - 37 - 22242 seconds before last successful new update, try create new one.
2022-02-02 10:03:37 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-02 16:03:13 - INFO - __main__.py - 37 - 22204 seconds before last successful new update, try create new one.
2022-02-02 16:18:06 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-02 22:02:11 - INFO - __main__.py - 37 - 22139 seconds before last successful new update, try create new one.
2022-02-02 22:12:34 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/06/20/16/02/05/90685484_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-02 22:12:34 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/06/20/16/02/05/90685484_p0.jpg.
2022-02-02 22:12:35 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-02 22:22:03 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-03 04:02:35 - INFO - __main__.py - 37 - 22224 seconds before last successful new update, try create new one.
2022-02-03 04:19:04 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/create_draw:2003:error
2022-02-03 04:19:04 - ERROR - bilibili.py - 439 - Failed to create dynamic.
2022-02-03 04:19:04 - ERROR - bot.py - 239 - Failed to create ranking dynamic.
2022-02-03 06:02:55 - INFO - __main__.py - 37 - 29444 seconds before last successful new update, try create new one.
2022-02-03 06:03:27 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-03 12:06:35 - INFO - __main__.py - 37 - 22421 seconds before last successful new update, try create new one.
2022-02-03 12:09:40 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/11/04/00/00/02/93901392_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 12:09:40 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/11/04/00/00/02/93901392_p0.png.
2022-02-03 12:09:41 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-03 12:12:56 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/06/00/00/06/92540677_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 12:12:56 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/06/00/00/06/92540677_p0.jpg.
2022-02-03 12:12:57 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-03 12:16:34 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-03 14:01:57 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-03 14:11:42 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-03 16:03:06 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-03 16:23:33 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-03 22:02:12 - INFO - __main__.py - 37 - 22145 seconds before last successful new update, try create new one.
2022-02-03 22:13:26 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/31/19/34/47/90228374_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 22:13:26 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/31/19/34/47/90228374_p0.png.
2022-02-03 22:13:27 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-03 22:21:42 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-04 04:02:05 - INFO - __main__.py - 37 - 22194 seconds before last successful new update, try create new one.
2022-02-04 04:20:39 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-04 06:01:55 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-04 06:02:50 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-04 12:05:24 - INFO - __main__.py - 37 - 22408 seconds before last successful new update, try create new one.
2022-02-04 12:05:56 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-04 18:02:08 - INFO - __main__.py - 37 - 22005 seconds before last successful new update, try create new one.
2022-02-04 18:06:00 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/19/00/02/10/92843456_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-04 18:06:00 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/19/00/02/10/92843456_p0.png.
2022-02-04 18:06:01 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-04 18:18:11 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-04 20:01:35 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-02-04 22:01:43 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-04 22:19:19 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-05 04:03:42 - INFO - __main__.py - 37 - 22320 seconds before last successful new update, try create new one.
2022-02-05 04:04:12 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-05 10:01:33 - INFO - __main__.py - 37 - 22071 seconds before last successful new update, try create new one.
2022-02-05 10:02:02 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-05 16:02:10 - INFO - __main__.py - 37 - 22237 seconds before last successful new update, try create new one.
2022-02-05 16:10:44 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-05 18:02:08 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-05 18:03:46 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/11/27/11/18/38/94400778_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-05 18:03:46 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/11/27/11/18/38/94400778_p0.png.
2022-02-05 18:03:47 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-05 18:12:16 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-06 00:22:56 - INFO - __main__.py - 37 - 23449 seconds before last successful new update, try create new one.
2022-02-06 00:31:44 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/06/30/19/15/48/90915938_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-06 00:31:44 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/06/30/19/15/48/90915938_p0.png.
2022-02-06 00:31:45 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-06 00:39:52 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-06 06:02:35 - INFO - __main__.py - 37 - 20979 seconds before last successful new update, try create new one.
2022-02-06 06:03:21 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-06 12:04:04 - INFO - __main__.py - 37 - 22290 seconds before last successful new update, try create new one.
2022-02-06 12:04:33 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-06 14:01:43 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-06 14:02:07 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/create_draw:2003:error
2022-02-06 14:02:07 - ERROR - bilibili.py - 439 - Failed to create dynamic.
2022-02-06 14:02:07 - ERROR - bot.py - 239 - Failed to create ranking dynamic.
2022-02-06 16:02:22 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-06 16:02:41 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-06 18:01:54 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-02-06 22:02:10 - INFO - __main__.py - 37 - 22187 seconds before last successful new update, try create new one.
2022-02-06 22:22:41 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-07 04:03:23 - INFO - __main__.py - 37 - 22273 seconds before last successful new update, try create new one.
2022-02-07 04:07:24 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/19/00/02/10/92843456_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-07 04:07:24 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/19/00/02/10/92843456_p0.png.
2022-02-07 04:07:25 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-07 04:20:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-07 10:02:00 - INFO - __main__.py - 37 - 22118 seconds before last successful new update, try create new one.
2022-02-07 10:03:09 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-07 16:02:53 - INFO - __main__.py - 37 - 22254 seconds before last successful new update, try create new one.
2022-02-07 16:03:17 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-07 22:02:17 - INFO - __main__.py - 37 - 22165 seconds before last successful new update, try create new one.
2022-02-07 22:23:34 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-08 04:02:41 - INFO - __main__.py - 37 - 22224 seconds before last successful new update, try create new one.
2022-02-08 04:03:07 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-08 10:01:52 - INFO - __main__.py - 37 - 22152 seconds before last successful new update, try create new one.
2022-02-08 10:02:17 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-08 12:04:16 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-08 12:25:19 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-08 18:02:45 - INFO - __main__.py - 37 - 22110 seconds before last successful new update, try create new one.
2022-02-08 18:09:05 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/06/00/00/06/92540677_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-08 18:09:05 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/06/00/00/06/92540677_p0.jpg.
2022-02-08 18:09:06 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-08 18:20:46 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/02/17/03/22/31/87837671_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-08 18:20:46 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/02/17/03/22/31/87837671_p0.jpg.
2022-02-08 18:20:47 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-08 18:25:12 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-09 00:17:24 - INFO - __main__.py - 37 - 23079 seconds before last successful new update, try create new one.
2022-02-09 00:39:08 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-09 02:24:45 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-09 02:41:09 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-09 04:03:10 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-02-09 08:05:30 - INFO - __main__.py - 37 - 21045 seconds before last successful new update, try create new one.
2022-02-09 08:06:02 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-09 10:02:05 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-02-09 14:01:47 - INFO - __main__.py - 37 - 21976 seconds before last successful new update, try create new one.
2022-02-09 14:02:13 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-09 16:04:13 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-02-09 18:02:34 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-02-09 20:02:08 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-09 20:03:46 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/11/27/11/18/38/94400778_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-09 20:03:46 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/11/27/11/18/38/94400778_p0.png.
2022-02-09 20:03:47 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-09 20:11:31 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-09 22:02:10 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-02-10 00:19:16 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-02-10 02:18:57 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-02-10 04:02:15 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-02-10 06:02:56 - INFO - __main__.py - 37 - 36647 seconds before last successful new update, try create new one.
2022-02-10 06:03:36 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-10 08:04:09 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-02-10 10:04:02 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-10 10:04:51 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-10 12:05:43 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-10 12:08:34 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/11/04/00/00/02/93901392_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-10 12:08:34 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/11/04/00/00/02/93901392_p0.png.
2022-02-10 12:08:35 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-10 12:14:37 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-10 14:02:08 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-10 14:22:12 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-10 20:02:13 - INFO - __main__.py - 37 - 22205 seconds before last successful new update, try create new one.
2022-02-10 20:03:07 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/12/11/20/10/16/94711497_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-10 20:03:07 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/12/11/20/10/16/94711497_p0.jpg.
2022-02-10 20:03:08 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-10 20:21:08 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-10 22:01:54 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-02-11 00:18:21 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-11 00:28:28 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/26/00/00/08/90097063_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-11 00:28:28 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/26/00/00/08/90097063_p0.png.
2022-02-11 00:28:29 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-11 00:35:24 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-11 06:06:34 - INFO - __main__.py - 37 - 21492 seconds before last successful new update, try create new one.
2022-02-11 06:07:00 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-11 12:06:04 - INFO - __main__.py - 37 - 22170 seconds before last successful new update, try create new one.
2022-02-11 12:27:41 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-11 18:02:48 - INFO - __main__.py - 37 - 22004 seconds before last successful new update, try create new one.
2022-02-11 18:12:02 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/31/19/34/47/90228374_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-11 18:12:02 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/31/19/34/47/90228374_p0.png.
2022-02-11 18:12:03 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-11 18:20:21 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-12 00:19:14 - INFO - __main__.py - 37 - 23187 seconds before last successful new update, try create new one.
2022-02-12 00:36:53 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-12 06:02:21 - INFO - __main__.py - 37 - 21186 seconds before last successful new update, try create new one.
2022-02-12 06:02:59 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-12 12:04:27 - INFO - __main__.py - 37 - 22327 seconds before last successful new update, try create new one.
2022-02-12 12:04:50 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-12 14:01:30 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-12 14:10:39 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-12 16:02:45 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-12 16:23:58 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-12 22:01:43 - INFO - __main__.py - 37 - 22138 seconds before last successful new update, try create new one.
2022-02-12 22:08:02 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/06/00/00/06/92540677_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-12 22:08:02 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/06/00/00/06/92540677_p0.jpg.
2022-02-12 22:08:04 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-12 22:23:22 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-13 04:02:25 - INFO - __main__.py - 37 - 22242 seconds before last successful new update, try create new one.
2022-02-13 04:22:20 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-13 06:02:22 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-13 06:02:53 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-13 12:05:33 - INFO - __main__.py - 37 - 22392 seconds before last successful new update, try create new one.
2022-02-13 12:06:00 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-13 18:02:30 - INFO - __main__.py - 37 - 22016 seconds before last successful new update, try create new one.
2022-02-13 18:17:57 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2020/12/21/14/31/47/86435035_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-13 18:17:57 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2020/12/21/14/31/47/86435035_p0.jpg.
2022-02-13 18:17:58 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-13 18:19:13 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-13 20:02:14 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-13 20:04:01 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/11/27/11/18/38/94400778_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-13 20:04:01 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/11/27/11/18/38/94400778_p0.png.
2022-02-13 20:04:02 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-13 20:21:05 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2020/12/21/14/31/47/86435035_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-13 20:21:05 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2020/12/21/14/31/47/86435035_p0.jpg.
2022-02-13 20:21:06 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-13 20:22:31 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-13 22:01:54 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-13 22:22:57 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-14 04:03:03 - INFO - __main__.py - 37 - 22268 seconds before last successful new update, try create new one.
2022-02-14 04:03:39 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-14 06:03:15 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-14 06:12:42 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-14 08:04:48 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-14 08:15:12 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-14 10:02:42 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-14 10:23:52 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-14 12:07:14 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-14 12:23:45 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-14 18:02:35 - INFO - __main__.py - 37 - 21921 seconds before last successful new update, try create new one.
2022-02-14 18:23:05 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-15 00:18:19 - INFO - __main__.py - 37 - 23144 seconds before last successful new update, try create new one.
2022-02-15 00:39:10 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-15 06:05:03 - INFO - __main__.py - 37 - 21404 seconds before last successful new update, try create new one.
2022-02-15 06:05:27 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-15 12:07:11 - INFO - __main__.py - 37 - 22327 seconds before last successful new update, try create new one.
2022-02-15 12:28:11 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-15 18:02:21 - INFO - __main__.py - 37 - 21912 seconds before last successful new update, try create new one.
2022-02-15 18:25:32 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-15 20:03:23 - INFO - __main__.py - 31 - Last dynamic being auditing.
2022-02-16 00:19:10 - INFO - __main__.py - 37 - 23209 seconds before last successful new update, try create new one.
2022-02-16 00:24:25 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/27/18/21/23/93058710_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-16 00:24:25 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/27/18/21/23/93058710_p0.jpg.
2022-02-16 00:24:26 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-16 00:30:02 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/06/20/16/02/05/90685484_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-16 00:30:02 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/06/20/16/02/05/90685484_p0.jpg.
2022-02-16 00:30:03 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-16 00:40:30 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-16 02:25:08 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-16 02:46:34 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-16 08:03:16 - INFO - __main__.py - 37 - 20888 seconds before last successful new update, try create new one.
2022-02-16 08:03:47 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-16 14:02:11 - INFO - __main__.py - 37 - 22134 seconds before last successful new update, try create new one.
2022-02-16 14:13:04 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-16 20:01:50 - INFO - __main__.py - 37 - 22180 seconds before last successful new update, try create new one.
2022-02-16 20:10:59 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/06/20/16/02/05/90685484_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-16 20:10:59 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/06/20/16/02/05/90685484_p0.jpg.
2022-02-16 20:11:00 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-16 20:20:00 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-16 22:01:56 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-16 22:08:00 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/06/00/00/06/92540677_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-16 22:08:00 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/06/00/00/06/92540677_p0.jpg.
2022-02-16 22:08:01 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-16 22:13:23 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/05/31/19/34/47/90228374_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-16 22:13:23 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/05/31/19/34/47/90228374_p0.png.
2022-02-16 22:13:24 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2022-02-16 22:22:00 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-17 04:05:10 - INFO - __main__.py - 37 - 22394 seconds before last successful new update, try create new one.
2022-02-17 04:05:41 - INFO - bot.py - 248 - Create ranking dynamic Success!
2022-02-17 06:06:32 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2022-02-17 06:07:00 - INFO - bot.py - 248 - Create ranking dynamic Success!
