2021-11-16 08:03:27 - INFO - bot.py - 245 - Create ranking dynamic Success!
2021-11-16 10:04:22 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:04:59 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:05:01 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:05:02 - ERROR - base.py - 25 - All retries failed in func _post_draw_image_upload.
2021-11-16 10:05:07 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:05:09 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:05:11 - WARNING - base.py - 56 - https://api.vc.bilibili.com/api/v1/drawImage/upload:413
2021-11-16 10:05:12 - ERROR - base.py - 25 - All retries failed in func _post_draw_image_upload.
2021-11-16 10:06:01 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:07 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:17 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:18 - ERROR - base.py - 25 - All retries failed in func _post_draw_image_upload.
2021-11-16 10:06:24 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:29 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:36 - ERROR - bilibili.py - 74 - https://api.vc.bilibili.com/api/v1/drawImage/upload:-3:请上传<20MB的图片
2021-11-16 10:06:37 - ERROR - base.py - 25 - All retries failed in func _post_draw_image_upload.
2021-11-16 10:06:38 - INFO - bot.py - 245 - Create ranking dynamic Success!
2021-11-16 12:22:21 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-16 14:19:23 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-16 16:19:47 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-16 18:18:39 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-16 20:08:08 - ERROR - base.py - 51 - https://i.pximg.net/img-original/img/2021/08/05/23/13/46/91751463_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-16 20:08:08 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/05/23/13/46/91751463_p0.png.
2021-11-16 20:19:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-16 22:12:26 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-17 04:02:54 - INFO - __main__.py - 38 - 22237.386504 seconds before last successful new update, try create new one.
2021-11-17 04:03:28 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-17 10:02:45 - INFO - __main__.py - 38 - 22192 seconds before last successful new update, try create new one.
2021-11-17 10:15:33 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-17 10:15:33 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png.
2021-11-17 10:15:34 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-17 10:17:07 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-17 12:05:55 - INFO - __main__.py - 60 - Last dynamic don't exist, redo create dynamic task.
2021-11-17 12:20:26 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-17 18:02:11 - INFO - __main__.py - 38 - 21977 seconds before last successful new update, try create new one.
2021-11-17 18:17:29 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 00:16:08 - INFO - __main__.py - 38 - 23036 seconds before last successful new update, try create new one.
2021-11-18 00:21:28 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-18 00:21:28 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg.
2021-11-18 00:21:29 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-18 00:31:30 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 02:19:16 - INFO - __main__.py - 60 - Last dynamic don't exist, redo create dynamic task.
2021-11-18 02:29:09 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 04:02:28 - INFO - __main__.py - 60 - Last dynamic don't exist, redo create dynamic task.
2021-11-18 04:03:03 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 10:02:18 - INFO - __main__.py - 38 - 22191 seconds before last successful new update, try create new one.
2021-11-18 10:07:23 - ERROR - base.py - 60 - https://www.pixiv.net/ajax/illust/91049805:('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2021-11-18 10:07:24 - WARNING - base.py - 23 - Retry func _get_illust 2 time.
2021-11-18 10:12:18 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 16:03:06 - INFO - __main__.py - 38 - 22247 seconds before last successful new update, try create new one.
2021-11-18 16:04:35 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/09/27/18/21/23/93058710_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-18 16:04:35 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/09/27/18/21/23/93058710_p0.jpg.
2021-11-18 16:04:36 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-18 16:19:32 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-18 22:02:07 - INFO - __main__.py - 38 - 22142 seconds before last successful new update, try create new one.
2021-11-18 22:16:56 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-19 04:02:31 - INFO - __main__.py - 38 - 22225 seconds before last successful new update, try create new one.
2021-11-19 04:03:15 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-19 10:02:15 - INFO - __main__.py - 38 - 22184 seconds before last successful new update, try create new one.
2021-11-19 10:18:23 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-19 16:02:59 - INFO - __main__.py - 38 - 22245 seconds before last successful new update, try create new one.
2021-11-19 16:10:27 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/05/19/34/44/91035045_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-19 16:10:27 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/05/19/34/44/91035045_p0.png.
2021-11-19 16:10:28 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-19 16:17:50 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-19 22:02:20 - INFO - __main__.py - 38 - 22162 seconds before last successful new update, try create new one.
2021-11-19 22:09:20 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/05/19/34/44/91035045_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-19 22:09:20 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/05/19/34/44/91035045_p0.png.
2021-11-19 22:09:21 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-19 22:16:15 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 04:02:35 - INFO - __main__.py - 38 - 22215 seconds before last successful new update, try create new one.
2021-11-20 04:03:13 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 10:02:17 - INFO - __main__.py - 38 - 22183 seconds before last successful new update, try create new one.
2021-11-20 10:02:44 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 12:03:51 - INFO - __main__.py - 60 - Last dynamic don't exist, redo create dynamic task.
2021-11-20 12:18:48 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 18:02:19 - INFO - __main__.py - 37 - 22109 seconds before last successful new update, try create new one.
2021-11-20 18:17:32 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 20:02:03 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-20 20:09:41 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/03/00/00/06/90966760_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-20 20:09:41 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/03/00/00/06/90966760_p0.jpg.
2021-11-20 20:09:42 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-20 20:17:57 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-20 22:02:07 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-20 22:12:37 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-21 04:02:31 - INFO - __main__.py - 37 - 22223 seconds before last successful new update, try create new one.
2021-11-21 04:03:07 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-21 06:02:34 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-21 06:07:33 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-21 06:07:33 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/06/00/00/01/91752626_p0.jpg.
2021-11-21 06:07:34 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-21 06:16:20 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-21 12:03:19 - INFO - __main__.py - 37 - 22245 seconds before last successful new update, try create new one.
2021-11-21 12:11:06 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/07/03/00/00/06/90966760_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-21 12:11:06 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/07/03/00/00/06/90966760_p0.jpg.
2021-11-21 12:11:07 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-21 12:19:12 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-21 18:02:31 - INFO - __main__.py - 37 - 22152 seconds before last successful new update, try create new one.
2021-11-21 18:07:55 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/06/20/16/02/05/90685484_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-21 18:07:55 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/06/20/16/02/05/90685484_p0.jpg.
2021-11-21 18:07:56 - WARNING - base.py - 23 - Retry func _get_page 2 time.
2021-11-21 18:12:35 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-22 00:16:13 - INFO - __main__.py - 37 - 23022 seconds before last successful new update, try create new one.
2021-11-22 00:31:08 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-22 06:03:44 - INFO - __main__.py - 37 - 21451 seconds before last successful new update, try create new one.
2021-11-22 06:04:18 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-22 12:03:56 - INFO - __main__.py - 37 - 22212 seconds before last successful new update, try create new one.
2021-11-22 12:19:44 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-22 18:02:37 - INFO - __main__.py - 37 - 22122 seconds before last successful new update, try create new one.
2021-11-22 18:16:31 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-23 00:16:05 - INFO - __main__.py - 37 - 23009 seconds before last successful new update, try create new one.
2021-11-23 00:33:07 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-23 06:02:56 - INFO - __main__.py - 37 - 21412 seconds before last successful new update, try create new one.
2021-11-23 06:03:40 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-23 08:02:41 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-23 08:19:07 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-23 14:01:57 - INFO - __main__.py - 37 - 22157 seconds before last successful new update, try create new one.
2021-11-23 14:15:55 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-23 14:15:55 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png.
2021-11-23 14:15:56 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-11-23 14:18:01 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-23 20:02:26 - INFO - __main__.py - 37 - 22229 seconds before last successful new update, try create new one.
2021-11-23 20:19:57 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-23 22:02:03 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-23 22:08:26 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/06/13/15/08/37/90523989_p0.jpg:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-23 22:08:26 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/06/13/15/08/37/90523989_p0.jpg.
2021-11-23 22:08:27 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-11-23 22:12:50 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-24 04:02:40 - INFO - __main__.py - 37 - 22236 seconds before last successful new update, try create new one.
2021-11-24 04:03:17 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-24 10:02:00 - INFO - __main__.py - 37 - 22161 seconds before last successful new update, try create new one.
2021-11-24 10:02:22 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-24 16:03:19 - INFO - __main__.py - 37 - 22279 seconds before last successful new update, try create new one.
2021-11-24 16:18:18 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-24 22:02:03 - INFO - __main__.py - 37 - 22124 seconds before last successful new update, try create new one.
2021-11-24 22:18:36 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-25 00:15:54 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-25 00:32:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-25 06:03:58 - INFO - __main__.py - 37 - 21484 seconds before last successful new update, try create new one.
2021-11-25 06:04:24 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-25 12:05:32 - INFO - __main__.py - 37 - 22295 seconds before last successful new update, try create new one.
2021-11-25 12:16:19 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-25 14:02:00 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-25 14:18:24 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-25 20:02:15 - INFO - __main__.py - 37 - 22216 seconds before last successful new update, try create new one.
2021-11-25 20:13:03 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-26 02:19:45 - INFO - __main__.py - 37 - 23250 seconds before last successful new update, try create new one.
2021-11-26 02:34:47 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-26 08:02:37 - INFO - __main__.py - 37 - 21172 seconds before last successful new update, try create new one.
2021-11-26 08:03:28 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-26 14:01:53 - INFO - __main__.py - 37 - 22156 seconds before last successful new update, try create new one.
2021-11-26 14:02:20 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-26 20:02:11 - INFO - __main__.py - 37 - 22219 seconds before last successful new update, try create new one.
2021-11-26 20:17:49 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-27 02:20:51 - INFO - __main__.py - 37 - 23320 seconds before last successful new update, try create new one.
2021-11-27 02:39:10 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-27 08:02:46 - INFO - __main__.py - 37 - 21116 seconds before last successful new update, try create new one.
2021-11-27 08:03:14 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-27 14:01:51 - INFO - __main__.py - 37 - 22145 seconds before last successful new update, try create new one.
2021-11-27 14:02:17 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-27 20:02:00 - INFO - __main__.py - 37 - 22209 seconds before last successful new update, try create new one.
2021-11-27 20:10:24 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/06/13/00/00/07/90510982_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-27 20:10:24 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/06/13/00/00/07/90510982_p0.png.
2021-11-27 20:10:25 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-11-27 20:16:33 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:502
2021-11-27 20:16:34 - WARNING - base.py - 23 - Retry func _post_draw_image_upload 1 time.
2021-11-27 20:16:34 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:502
2021-11-27 20:16:35 - WARNING - base.py - 23 - Retry func _post_draw_image_upload 2 time.
2021-11-27 20:16:35 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:502
2021-11-27 20:16:36 - WARNING - base.py - 23 - Retry func _post_draw_image_upload 3 time.
2021-11-27 20:16:36 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:502
2021-11-27 20:16:37 - ERROR - base.py - 34 - All retries failed in func _post_draw_image_upload.
2021-11-27 20:16:37 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:502
2021-11-27 20:16:38 - WARNING - base.py - 23 - Retry func _post_draw_image_upload 1 time.
2021-11-27 20:16:38 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:502
2021-11-27 20:16:39 - WARNING - base.py - 23 - Retry func _post_draw_image_upload 2 time.
2021-11-27 20:16:40 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:502
2021-11-27 20:16:41 - WARNING - base.py - 23 - Retry func _post_draw_image_upload 3 time.
2021-11-27 20:16:41 - WARNING - base.py - 65 - https://api.vc.bilibili.com/api/v1/drawImage/upload:502
2021-11-27 20:16:42 - ERROR - base.py - 34 - All retries failed in func _post_draw_image_upload.
2021-11-27 20:16:50 - ERROR - bilibili.py - 434 - Failed to upload all pictures.
2021-11-27 20:16:50 - ERROR - bot.py - 239 - Failed to create ranking dynamic.
2021-11-27 23:12:49 - INFO - __main__.py - 37 - 33659 seconds before last successful new update, try create new one.
2021-11-27 23:29:55 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-28 06:03:57 - INFO - __main__.py - 37 - 25268 seconds before last successful new update, try create new one.
2021-11-28 06:04:36 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-28 08:02:18 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-28 08:02:41 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-28 10:02:18 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-28 10:08:39 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-28 16:02:46 - INFO - __main__.py - 37 - 22228 seconds before last successful new update, try create new one.
2021-11-28 16:11:39 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-28 22:02:15 - INFO - __main__.py - 37 - 22169 seconds before last successful new update, try create new one.
2021-11-28 22:07:17 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/08/22/00/00/06/92161858_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-28 22:07:17 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/08/22/00/00/06/92161858_p0.png.
2021-11-28 22:07:18 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-11-28 22:17:04 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-28 22:17:04 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png.
2021-11-28 22:17:05 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-11-28 22:19:27 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-29 04:02:45 - INFO - __main__.py - 37 - 22231 seconds before last successful new update, try create new one.
2021-11-29 04:03:19 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-29 10:02:23 - INFO - __main__.py - 37 - 22179 seconds before last successful new update, try create new one.
2021-11-29 10:02:50 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-29 16:03:26 - INFO - __main__.py - 37 - 22264 seconds before last successful new update, try create new one.
2021-11-29 16:22:36 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-29 22:02:23 - INFO - __main__.py - 37 - 22138 seconds before last successful new update, try create new one.
2021-11-29 22:18:11 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-30 00:16:21 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-30 00:31:37 - ERROR - base.py - 60 - https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-11-30 00:31:37 - ERROR - pixiv.py - 111 - Failed to get page from https://i.pximg.net/img-original/img/2021/04/02/00/00/05/88865143_p0.png.
2021-11-30 00:31:38 - WARNING - base.py - 23 - Retry func _get_page 1 time.
2021-11-30 00:34:15 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-30 06:02:07 - INFO - __main__.py - 37 - 21347 seconds before last successful new update, try create new one.
2021-11-30 06:02:42 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-30 08:02:22 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-11-30 08:12:32 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-30 14:01:59 - INFO - __main__.py - 37 - 22177 seconds before last successful new update, try create new one.
2021-11-30 14:24:57 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-11-30 20:02:30 - INFO - __main__.py - 37 - 22232 seconds before last successful new update, try create new one.
2021-11-30 20:14:50 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-01 02:25:28 - INFO - __main__.py - 37 - 23578 seconds before last successful new update, try create new one.
2021-12-01 02:45:05 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-01 04:03:10 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-01 04:03:34 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-01 06:02:35 - INFO - __main__.py - 59 - Last dynamic don't exist, redo create dynamic task.
2021-12-01 06:17:08 - INFO - bot.py - 248 - Create ranking dynamic Success!
2021-12-01 12:06:52 - INFO - __main__.py - 37 - 22457 seconds before last successful new update, try create new one.
2021-12-01 12:19:34 - INFO - bot.py - 248 - Create ranking dynamic Success!
